### ISSUE TITLE
[错误报告]WEB UI下载失败

### ISSUE THREAD

**Issue by yzjmxy** [EstrellaXD/Auto_Bangumi#108]
### 当前程序版本

2.5.25

### 问题类型

WebUI

### 问题描述

程序无限循环，webui下载失败

### 发生问题时系统日志

```shell
![image](https://user-images.githubusercontent.com/39520103/187853743-1a0b1bbf-248c-4eaa-90a0-5f6abbb09971.png)

```

**Comment by yzjmxy** [comment]
![QQ截图20220901150823](https://user-images.githubusercontent.com/39520103/187853847-a7d7e9a9-43cb-4898-b9a6-1c93c4c2f6d5.png)

**Comment by Rewrite0** [comment]
已更换为ghproxy #106 请等待下版本更新.
目前你可以先停止容器, 在宿主机准备一个目录放置webui, 同时创建一个version文件, 内容为v1.0.4, 然后把这个目录绑定到容器的/templates即可

**Comment by yzjmxy** [comment]
> 已更换为ghproxy #106 请等待下版本更新. 目前你可以先停止容器， 在宿主机准备一个目录放置webui， 同时创建一个version文件， 内容为v1.0.4， 然后把这个目录绑定到容器的/templates即可

目前是暂时解决了循环报错，但是webui是无法访问的。下个版本是否需要删除version文件进行更新？

**Comment by Rewrite0** [comment]
version文件是辅助shell脚本检测目前的webui版本的, 有新版本会重新下载新版本的webui.
无法访问的问题是你没有把webui放进去吧.

**Comment by yzjmxy** [comment]
> version文件是辅助shell脚本检测目前的webui版本的， 有新版本会重新下载新版本的webui. 无法访问的问题是你没有把webui放进去吧.

我还以为这只是暂时用来解决报错呢，明白了

**Comment by Rewrite0** [comment]
> > version文件是辅助shell脚本检测目前的webui版本的， 有新版本会重新下载新版本的webui. 无法访问的问题是你没有把webui放进去吧.
> 
> 我还以为这只是暂时用来解决报错呢，明白了

这其实就是手动放置webui的操作, 这个issues就留到新版本更新再关闭吧

**Comment by yzjmxy** [comment]
> > > version文件是辅助shell脚本检测目前的webui版本的， 有新版本会重新下载新版本的webui.无法访问的问题是你没有把webui放进去吧.
> > 
> > 
> > 我还以为这只是暂时用来解决报错呢，明白了
> 
> 这其实就是手动放置webui的操作， 这个issues就留到新版本更新再关闭吧

OKK

**Comment by herjik** [comment]
我是权限问题，设置uid和pid都是0
