### ISSUE TITLE
无法解析dns但是ip可以ping通

### ISSUE THREAD

**Issue by FierceKing** [EstrellaXD/Auto_Bangumi#112]
### 当前程序版本

estrellaxd/auto_bangumi docker latest, (大概是2.5.25-fix)

### 问题类型

程序运行问题

### 问题描述

进入docker的shell，发现wget的进程无法完成。查明原因是无法解析dns域名。
尝试 ping百度，不行
<pre><code>/src # ping baidu.com
ping: bad address 'baidu.com'
</code></pre>
尝试ping 110.242.68.66 （百度的IP），可以
<pre><code>
/src # ping 110.242.68.66
PING 110.242.68.66 (110.242.68.66): 56 data bytes
64 bytes from 110.242.68.66: seq=0 ttl=52 time=14.835 ms
64 bytes from 110.242.68.66: seq=1 ttl=52 time=14.709 ms
64 bytes from 110.242.68.66: seq=2 ttl=52 time=14.657 ms
64 bytes from 110.242.68.66: seq=3 ttl=52 time=14.700 ms
^C
--- 110.242.68.66 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 14.657/14.725/14.835 ms
</code></pre>
查看dns服务器设置，没问题
<pre><code>
/src # cat /etc/resolv.conf
nameserver 192.168.1.1   #路由器ip，这个是正确的dns
</code></pre>

在网上搜索相似情况，发现是busybox的问题。1.28以上版本都有发生，Github上很多人说可以用1.27或者1.28版。
https://github.com/docker-library/busybox/issues/48
https://unix.stackexchange.com/questions/124283/busybox-ping-ip-works-but-hostname-nslookup-fails-with-bad-address
https://stackoverflow.com/questions/52663711/how-should-i-interpret-a-cant-find-from-nslookup-inside-a-docker-busybox-c

照上文尝试测试，限定A记录是可以解析正确的IP的，符合其他人的情况。
<pre><code>
/src # busybox nslookup -type=a google.com
Server:         192.168.1.1
Address:        192.168.1.1:53

Non-authoritative answer:
Name:   google.com
Address: 142.250.196.142

/src # busybox
BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
</code></pre>

请关注busybox对此问题的跟进，在修复之前希望您能重新打包一个1.27/1.28版busybox的docker image.
🙏感谢！

### 发生问题时系统日志

```shell
/src # ping baidu.com
ping: bad address 'baidu.com'

尝试ping 110.242.68.66 （百度的IP），可以

/src # ping 110.242.68.66
PING 110.242.68.66 (110.242.68.66): 56 data bytes
64 bytes from 110.242.68.66: seq=0 ttl=52 time=14.835 ms
64 bytes from 110.242.68.66: seq=1 ttl=52 time=14.709 ms
64 bytes from 110.242.68.66: seq=2 ttl=52 time=14.657 ms
64 bytes from 110.242.68.66: seq=3 ttl=52 time=14.700 ms
^C
--- 110.242.68.66 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 14.657/14.725/14.835 ms

查看dns服务器设置，没问题

/src # cat /etc/resolv.conf
nameserver 192.168.1.1   #路由器ip，这个是正确的dns

限定A记录是可以解析正确的IP的，符合其他人的情况。

/src # busybox nslookup -type=a google.com
Server:         192.168.1.1
Address:        192.168.1.1:53

Non-authoritative answer:
Name:   google.com
Address: 142.250.196.142

/src # busybox
BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2015.
Licensed under GPLv2. See source distribution for detailed
copyright notices.
```

**Comment by FierceKing** [comment]
不好意思markdown把我打的分割线翻译成超大字体了，竟然搞的那么乱。

**Comment by EstrellaXD** [comment]
正在关注，下个版本修复

**Comment by FierceKing** [comment]
哈哈，我是来催更的，今天又试了一下，还是不行。不会自己封装，麻烦大神给弄一个。

**Comment by 1834423612** [comment]
> 正在关注，下个版本修复

请问大佬怎么样了,现在依然是这个问题.目前这个程序已经用不了了

**Comment by saltfish13** [comment]
同样的问题，从2月1号后就没正确获取到订阅的番剧了
