### ISSUE TITLE
[错误报告]2.5.22以上版本在armv7上无法获取RSS列表

### ISSUE THREAD

**Issue by czlizy** [EstrellaXD/Auto_Bangumi#125]
### 当前程序版本

2.5.22以上

### 问题类型

程序运行问题

### 问题描述

armv7版本的docker，2.5.22以上版本包括最新的2.5.25-fix，运行时无法获得或解析RSS内容。qbittorrent中可以添加mikanRSS的订阅，但是不会添加下载规则，config目录下的json文件中"bangumi_info"一直为空，日志上也没有任何错误信息。

拉取以前的版本发现2.5.21-5可以正常工作……

--------------------------------------------------------------------------------

**### 问题解决了，还是lxml的问题，bs4无法解析xml内容，把request.py里的BS4的解析格式改成html.parser目前是可以用了**

**Comment by czlizy** [comment]
试了一下还是xml的问题orz
`>>> soup=BeautifulSoup(req.text, "xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/bs4/__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?`

**Comment by czlizy** [comment]
我试了把request.py里的
`if content == "xml":
return BeautifulSoup(self.get_url(url).text, content)`
改成
`if content == "xml":
return BeautifulSoup(self.get_url(url).text, "html.parser")`
这样似乎就可以用了，就是日志里会多出一条警告
`/usr/local/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.`

**Comment by Number-85** [comment]
我也遇到了类似问题，不过我的是群晖上部署的···
