### ISSUE TITLE
[错误报告]关于字幕组发布合集类bt的处理方法

### ISSUE THREAD

**Issue by yzjmxy** [EstrellaXD/Auto_Bangumi#128]
### 当前程序版本

2.5.25

### 问题类型

其他问题

### 问题描述

![image](https://user-images.githubusercontent.com/39520103/195236216-d832904c-3e00-4610-954a-612ef8171b69.png)
针对类似上图字幕组发布合集类bt时，是否可以提供不下载选项，或者自动移动文件夹覆盖原先下载完成的集数。
另外还有一点就是，是否可以提供针对特定番剧，自定义修改规则的选择。
否则每次在qb中修改后，都会被改回去= =

**Comment by EstrellaXD** [comment]
可以在过滤选项中输入 `\d+-\d+` 过滤合集
针对特定 bangumi 可以在 qb 中单独设定过滤规则

**Comment by yzjmxy** [comment]
> 可以在过滤选项中输入 `\d+-\d+` 过滤合集 针对特定 bangumi 可以在 qb 中单独设定过滤规则

主要是有些字幕组会莫名其妙的，几集突然一起发个合集。然后不发单个的
