### ISSUE TITLE
[Feature Request]: 希望能在dockerhub或者unraid应用商店上传一份，方便unraid用户安装部署

### ISSUE THREAD

**Issue by LeederThree** [EstrellaXD/Auto_Bangumi#132]
### 功能改进

目前只能用docker compose在unraid终端手动部署，不仅参数设置比较麻烦而且出错了也很难发现问题，希望能提交一份方便部署的官方版本

**Comment by greenhat616** [comment]
```xml
<?xml version="1.0"?>
<Container version="2">
  <Name>AutoBangumi</Name>
  <Repository>estrellaxd/auto_bangumi:latest</Repository>
  <Registry>https://hub.docker.com/r/estrellaxd/auto_bangumi</Registry>
  <Network>bridge</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support/>
  <Project/>
  <Overview>AutoBangumi &#x662F;&#x57FA;&#x4E8E; Mikan Project&#x3001;qBittorrent &#x7684;&#x5168;&#x81EA;&#x52A8;&#x8FFD;&#x756A;&#x6574;&#x7406;&#x4E0B;&#x8F7D;&#x5DE5;&#x5177;&#x3002;&#x53EA;&#x9700;&#x8981;&#x5728; Mikan Project &#x4E0A;&#x8BA2;&#x9605;&#x756A;&#x5267;&#xFF0C;&#x5C31;&#x53EF;&#x4EE5;&#x5168;&#x81EA;&#x52A8;&#x8FFD;&#x756A;&#x3002;&#x5E76;&#x4E14;&#x6574;&#x7406;&#x5B8C;&#x6210;&#x7684;&#x540D;&#x79F0;&#x548C;&#x76EE;&#x5F55;&#x53EF;&#x4EE5;&#x76F4;&#x63A5;&#x88AB; Plex&#x3001;Jellyfin &#x7B49;&#x5A92;&#x4F53;&#x5E93;&#x8F6F;&#x4EF6;&#x8BC6;&#x522B;&#xFF0C;&#x65E0;&#x9700;&#x4E8C;&#x6B21;&#x522E;&#x524A;&#x3002;</Overview>
  <Category/>
  <WebUI>http://[IP]:[PORT:7892]/</WebUI>
  <TemplateURL/>
  <Icon>https://camo.githubusercontent.com/69be62a391b91f9938ae4d2f1a419a7bcb094ead1029faf6733c915f5887cc1a/68747470733a2f2f6d696b616e616e692e6d652f696d616765732f6d696b616e2d7069632e706e67</Icon>
  <ExtraParams>--dns 8.8.8.8 --dns 223.5.5.5</ExtraParams>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1676642898</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="QBittorrent &#x4E3B;&#x673A;" Target="AB_DOWNLOADER_HOST" Default="[host]:8080" Mode="" Description="QBittorrent &#x4E3B;&#x673A;&#x540D;&#xFF0C;&#x4F8B;&#x5982;&#xFF1A;192.168.123.1:8080" Type="Variable" Display="always" Required="true" Mask="false">192.168.63.190:8080</Config>
  <Config Name="QBittorent WebUI &#x7528;&#x6237;&#x540D;" Target="AB_DOWNLOADER_USERNAME" Default="adminadmin" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">admin</Config>
  <Config Name="QBittorrent WEBUI &#x5BC6;&#x7801;" Target="AB_DOWNLOADER_PASSWORD" Default="adminadmin" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="true">tue2wrq!PAW9enk8mzh</Config>
  <Config Name="&#x4E0B;&#x8F7D;&#x8DEF;&#x5F84;" Target="AB_DOWNLOAD_PATH" Default="/downloads/Bangumi" Mode="" Description="qBittorrent &#x4E2D;&#x7684;&#x4E0B;&#x8F7D;&#x8DEF;&#x5F84;" Type="Variable" Display="always" Required="false" Mask="false">/downloads/Bangumi</Config>
  <Config Name="RSS &#x8BA2;&#x9605;&#x5730;&#x5740;" Target="AB_RSS" Default="" Mode="" Description="RSS &#x8BA2;&#x9605;&#x5730;&#x5740;&#xFF0C;&#x5982;&#x679C;&#x6CA1;&#x6709;&#xFF0C;&#x8BF7;&#x5230; mikanani.me &#x83B7;&#x53D6;" Type="Variable" Display="always" Required="true" Mask="false">https://mikanani.me/RSS/MyBangumi?token=IEBQyEC7uQ5%2faQAedtAyZw%3d%3d</Config>
  <Config Name="WEB UI &#x7AEF;&#x53E3;" Target="AB_WEBUI_PORT" Default="7892" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">7892</Config>
  <Config Name="WEBUI &#x7AEF;&#x53E3;" Target="7892" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">7892</Config>
  <Config Name="&#x65F6;&#x533A;" Target="TZ" Default="Asia/Shanghai" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">Asia/Shanghai</Config>
  <Config Name="PUID" Target="PUID" Default="99" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">99</Config>
  <Config Name="PGID" Target="PGID" Default="100" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">100</Config>
  <Config Name="Appconfig &#x8BBE;&#x7F6E;" Target="/config" Default="/mnt/user/appdata/auto-bangumi" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/auto-bangumi</Config>
  <Config Name="&#x4FEE;&#x590D;&#x9519;&#x8BEF;&#x547D;&#x540D;&#x6587;&#x4EF6;&#x5939;" Target="AB_RESET_FOLDER" Default="False" Mode="" Description="&#x4FEE;&#x590D;&#x9519;&#x8BEF;&#x547D;&#x540D;&#x6587;&#x4EF6;&#x5939;&#xFF0C;&#x5982; S01 &amp;gt;&amp;gt; Season 1" Type="Variable" Display="advanced" Required="false" Mask="false">False</Config>
  <Config Name="RSS &#x89E3;&#x6790;&#x5668;" Target="AB_RSS_COLLECTOR" Default="True" Mode="" Description="RSS &#x89E3;&#x6790;&#x5668;&#x5F00;&#x5173;" Type="Variable" Display="advanced" Required="false" Mask="false">True</Config>
  <Config Name="&#x81EA;&#x52A8;&#x91CD;&#x547D;&#x540D;" Target="AB_RENAME" Default="True" Mode="" Description="RENAME &#x5F00;&#x5173;" Type="Variable" Display="advanced" Required="false" Mask="false">True</Config>
  <Config Name="SOCKS &#x4EE3;&#x7406;" Target="AB_SOCKS" Default="" Mode="" Description="HOST,PORT,USR,PWD" Type="Variable" Display="advanced" Required="false" Mask="false"/>
  <Config Name="HTTP &#x4EE3;&#x7406;" Target="AB_HTTP_PROXY" Default="" Mode="" Description="127.0.0.1:6352" Type="Variable" Display="advanced" Required="false" Mask="false"/>
  <Config Name="&#x5220;&#x9664;&#x4E0D;&#x826F;&#x79CD;&#x5B50;" Target="AB_REMOVE_BAD_BT" Default="False" Mode="" Description="&#x78B0;&#x5230;&#x65E0;&#x6CD5;&#x91CD;&#x547D;&#x540D;&#x7684;&#x5408;&#x96C6;&#x7B49;&#xFF0C;&#x81EA;&#x52A8;&#x5220;&#x9664;&#x79CD;&#x5B50;" Type="Variable" Display="advanced" Required="false" Mask="false">False</Config>
  <Config Name="&#x5386;&#x53F2;&#x756A;&#x5267;&#x4E0B;&#x8F7D;" Target="AB_EP_COMPLETE" Default="False" Mode="" Description="" Type="Variable" Display="advanced" Required="false" Mask="false">True</Config>
  <Config Name="&#x8C03;&#x8BD5;&#x6A21;&#x5F0F;" Target="AB_DEBUG_MODE" Default="False" Mode="" Description="" Type="Variable" Display="advanced" Required="false" Mask="false">False</Config>
  <Config Name="&#x8FC7;&#x6EE4;&#x5143;&#x7D20;" Target="AB_NOT_CONTAIN" Default="720" Mode="" Description="&#x8F93;&#x5165;&#x60F3;&#x8981;&#x8FC7;&#x6EE4;&#x7684;&#x5143;&#x7D20;&#xFF0C;&#x5982; 720&#xFF0C;1080&#xFF0C;&#x7B49;&#x3002;&#13;&#10;&#13;&#10;    &#x4E0D;&#x540C;&#x7684;&#x5143;&#x7D20;&#x7528; | &#x5206;&#x9694;&#xFF0C;&#x4F8B;&#x5982; 720|CHT&#13;&#10;    &#x53EF;&#x4EE5;&#x4F7F;&#x7528;&#x6B63;&#x5219;&#x8868;&#x8FBE;&#x5F0F;&#xFF0C;&#x4F46;&#x662F;&#x9700;&#x8981;&#x6CE8;&#x610F;&#xFF0C;&#x7279;&#x6B8A;&#x7B26;&#x53F7;&#x9700;&#x8981;&#x8F6C;&#x4E49;&#xFF0C;&#x4F8B;&#x5982; \( &#x8868;&#x793A; (&#x3002;&#13;&#10;    &#x8FD9;&#x4E2A;&#x9009;&#x9879;&#x5EFA;&#x8BAE;&#x586B;&#x5199;&#xFF1A;720|\d+-\d+&#xFF0C;&#x5982;&#x679C;&#x8FC7;&#x6EE4;&#x9009;&#x9879;&#x6DFB;&#x52A0;&#x8FC7;&#x591A;&#xFF0C;&#x4F1A;&#x5F71;&#x54CD;&#x5230;&#x6B63;&#x5E38;&#x7684; RSS &#x8BC6;&#x522B;&#x3002;&#x5BF9;&#x4E8E;&#x756A;&#x5267;&#x5355;&#x72EC;&#x7684;&#x81EA;&#x5B9A;&#x4E49;&#x53EF;&#x4EE5;&#x5728; qBitorrent &#x4E2D;&#x81EA;&#x5B9A;&#x4E49;&#x3002;&#13;&#10;" Type="Variable" Display="advanced" Required="false" Mask="false">720</Config>
  <Config Name="&#x542F;&#x7528; TMDB&#xFF1F;" Target="AB_ENABLE_TMDB" Default="False" Mode="" Description="&#x542F;&#x52A8; TMDB &#x89E3;&#x6790;" Type="Variable" Display="advanced" Required="false" Mask="false">True</Config>
  <Config Name="&#x8BED;&#x8A00;" Target="AB_LANGUAGE" Default="zh" Mode="" Description="TMDB &#x89E3;&#x6790;&#x540E;&#x9009;&#x62E9;&#x8BED;&#x8A00;&#xFF0C;&#x4EC5;&#x5728; TMDB &#x5F00;&#x542F;&#x65F6;&#x6709;&#x6548;&#x3002;&#13;&#10;&#x652F;&#x6301; zh&#x3001;jp&#x3002;" Type="Variable" Display="advanced" Required="false" Mask="false">zh</Config>
  <Config Name="&#x91CD;&#x547D;&#x540D;&#x65B9;&#x6CD5;" Target="AB_METHOD" Default="pn" Mode="" Description="&#x91CD;&#x547D;&#x540D;&#x65B9;&#x6CD5; normal &#x4FDD;&#x7559;&#x5B57;&#x5E55;&#x7EC4;&#x4FE1;&#x606F;&#xFF0C; pn &#x4E3A;&#x7EAF;&#x51C0;&#x6A21;&#x5F0F;&#xFF0C;advance &#x4E3A;&#x9AD8;&#x7EA7;&#x6A21;&#x5F0F;&#xFF0C;none &#x4E3A;&#x7A7A;&#x6A21;&#x5F0F;&#xFF0C;&#x4E0D;&#x91CD;&#x547D;&#x540D;" Type="Variable" Display="advanced" Required="false" Mask="false">advance</Config>
  <Config Name="&#x6DFB;&#x52A0;&#x7EC4;&#x540D;&#xFF1F;" Target="AB_GROUP_TAG" Default="False" Mode="" Description="&#x662F;&#x5426;&#x5728;&#x4E0B;&#x8F7D;&#x89C4;&#x5219;&#x4E2D;&#x6DFB;&#x52A0;&#x7EC4;&#x540D;&#xFF0C;&#x65B9;&#x4FBF;&#x67E5;&#x770B;&#x3002;&#x5F00;&#x542F;&#x540E;&#x89C4;&#x5219;&#x547D;&#x540D;&#x4E3A; [&#x7EC4;&#x540D;]&#x89C4;&#x5219;&#x540D;&#xFF0C;&#x5173;&#x95ED;&#x540E;&#x89C4;&#x5219;&#x547D;&#x540D;&#x4E3A; [&#x89C4;&#x5219;&#x540D;]" Type="Variable" Display="advanced" Required="false" Mask="false">True</Config>
  <Config Name="&#x8BF7;&#x6C42;&#x95F4;&#x9694;&#x65F6;&#x95F4;" Target="AB_INTERVAL_TIME" Default="7200" Mode="" Description="" Type="Variable" Display="advanced" Required="false" Mask="false">1800</Config>
  <Config Name="&#x91CD;&#x547D;&#x540D;&#x9891;&#x7387;" Target="AB_RENAME_FREQ" Default="20" Mode="" Description="&#x5728;&#x4E00;&#x4E2A;&#x8FD0;&#x884C;&#x5468;&#x671F;&#x5185;&#x91CD;&#x547D;&#x540D;&#x9891;&#x7387;" Type="Variable" Display="advanced" Required="false" Mask="false">20</Config>
</Container>
```

我自己写的模板，有需要的大家可以用我的这份。我把环境变量全配置进去了。

**Comment by EstrellaXD** [comment]
没有用过 unraid，具体怎么个发布流程

**Comment by LeederThree** [comment]
原来dockerhub上已经有镜像了，之前搜的关键词不对，有模板就好用多了，现在已经可以正常拉取了，谢谢！

**Comment by LeederThree** [comment]
unraid官方商店的上传流程我也不太清楚，目前这样就已经可以用了，谢谢大佬

**Comment by greenhat616** [comment]
> @EstrellaXD 没有用过 unraid，具体怎么个发布流程

这个是 Unraid Docker 配置文件的格式：https://wiki.unraid.net/DockerTemplateSchema
有关如何发布的信息（我不确定是否失效了，但应该值得尝试）：https://forums.unraid.net/topic/57181-docker-faq/?do=findComment&comment=566084

>  Publishing to CA

    Create a GitHub repository and upload the XML(s).  Use a separate repository for your xml files.  (Keep it separate from the docker associated files if you've built your own container).  If you have multiple templates, put them all into the same repository.   NOTE:  The XML files must be within the "master" or "main" branch of the repository
    Drop myself (squid)  a PM asking for it to be published with a link to the github repo.
    I'm going to  insist you create a <Support> thread.  Just create it anywhere (as you won't be able to create in the docker Containers) and a moderator will move it.  Update the XML with the support link.  I will also insist on Categories being set.  
    I do a quick check on the xml(s) and then add it to CA.  If there are no major problems, within 2 hours all users of CA will have access to it under normal circumstances.
    Time permitting after its available to all users of CA, I will update the Repositories thread


简言之：
1. 创建一个独立的 Github 仓库，用于单独存储 XML 文件（可以是多个）。
2. 注册一个 unraid forum 账户，然后私聊 `@squid` 和他说明需要申请加入 Community Apps。
3. 他审核无误后，即加入 Community Apps。一般来说 2h 后，所有 unraid 用户都能获取此仓库下所有插件配置了。
4. 除非特殊情况，比如说被用户反馈弃用，或者存在其他一些威胁 unraid 可靠性的问题，仓库将不再被审核。**仓库后续更新将自动同步。**

他建议在 unraid 论坛单独开一个贴用于支持（我觉得 gh issue 应该也是符合的，他在模板的 `Support` 字段中）
他也建议补全 unraid 的开发者信息，参考：https://forums.unraid.net/topic/38619-docker-template-xml-schema/?do=findComment&comment=919111。此配置应该是用于在 Apps 中展示维护者信息的。

**Comment by EstrellaXD** [comment]
@greenhat616 看起来有点复杂，感觉以 AB 的下载量没必要进入 Community Apps，不知道是否可以把你的配置文件放到 Wiki 说明中

**Comment by greenhat616** [comment]
> @greenhat616 看起来有点复杂，感觉以 AB 的下载量没必要进入 Community Apps，不知道是否可以把你的配置文件放到 Wiki 说明中

@EstrellaXD 可以的，在 unraid `6.1x` 后的版本，让他们放在 `/boot/config/plugins/dockerMan/templates-user/` 目录下即可。
![图片](https://user-images.githubusercontent.com/41122242/219942045-08d3821e-9115-40e5-aa6d-62aaeb537884.png)

**Comment by tao08ms** [comment]
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <Container version="2">
>   <Name Default="AutoBangumi">AutoBangumi</Name>
>   <Repository>estrellaxd/auto_bangumi:latest</Repository>
>   <Registry>https://registry.hub.docker.com/r/estrellaxd/auto_bangumi</Registry>
>   <Network Default="bridge">bridge</Network>
>   <Category>MediaServer:Video Tools Productivity</Category>
>   <MyIP/>
>   <Shell>sh</Shell>
>   <Privileged>false</Privileged>
>   <Support>https://github.com/EstrellaXD/Auto_Bangumi/issues</Support>
>   <Project/>
>   <Overview>
>     AutoBangumi 是基于 Mikan Project、qBittorrent 的全自动追番整理下载工具。只需要在 Mikan Project 上订阅番剧，就可以全自动追番。并且整理完成的名称和目录可以直接被 Plex、Jellyfin 等媒体库软件识别，无需二次刮削。
>   </Overview>
>   <Category/>
>   <WebUI>http://[IP]:[PORT:7892]/</WebUI>
>   <TemplateURL/>
>   <Icon>https://camo.githubusercontent.com/69be62a391b91f9938ae4d2f1a419a7bcb094ead1029faf6733c915f5887cc1a/68747470733a2f2f6d696b616e616e692e6d652f696d616765732f6d696b616e2d7069632e706e67</Icon>
>   <ExtraParams>--dns 8.8.8.8 --dns 223.5.5.5</ExtraParams>
>   <PostArgs/>
>   <CPUset/>
>   <DonateText/>
>   <DonateLink/>
>   <Requires/>
>   <Config Name="QBittorrent 主机" Target="AB_DOWNLOADER_HOST" Default="[host]:8080" Mode="" Description="QBittorrent 主机名，例如：192.168.123.1:8080" Type="Variable" Display="always" Required="true" Mask="false"/>
>   <Config Name="QBittorent WebUI 用户名" Target="AB_DOWNLOADER_USERNAME" Default="admin" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false"/>
>   <Config Name="QBittorrent WEBUI 密码" Target="AB_DOWNLOADER_PASSWORD" Default="adminadmin" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="true"/>
>   <Config Name="下载路径" Target="AB_DOWNLOAD_PATH" Default="/downloads/Bangumi" Mode="" Description="qBittorrent 中的下载路径" Type="Variable" Display="always" Required="false" Mask="false"/>
>   <Config Name="RSS 订阅地址" Target="AB_RSS" Default="" Mode="" Description="RSS 订阅地址，如果没有，请到 mikanani.me 获取" Type="Variable" Display="always" Required="true" Mask="false"/>
>   <Config Name="WEB UI 端口" Target="AB_WEBUI_PORT" Default="7892" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false"/>
>   <Config Name="WEBUI 端口" Target="7892" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false"/>
>   <Config Name="时区" Target="TZ" Default="Asia/Shanghai" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false"/>
>   <Config Name="PUID" Target="PUID" Default="99" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false"/>
>   <Config Name="PGID" Target="PGID" Default="100" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false"/>
>   <Config Name="Appconfig 设置" Target="/config" Default="/mnt/user/appdata/auto-bangumi" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false"/>
>   <Config Name="修复错误命名文件夹" Target="AB_RESET_FOLDER" Default="False" Mode="" Description="修复错误命名文件夹，如 S01 &amp;gt;&amp;gt; Season 1" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="RSS 解析器" Target="AB_RSS_COLLECTOR" Default="True" Mode="" Description="RSS 解析器开关" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="自动重命名" Target="AB_RENAME" Default="True" Mode="" Description="RENAME 开关" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="SOCKS 代理" Target="AB_SOCKS" Default="" Mode="" Description="HOST,PORT,USR,PWD" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="HTTP 代理" Target="AB_HTTP_PROXY" Default="" Mode="" Description="127.0.0.1:6352" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="删除不良种子" Target="AB_REMOVE_BAD_BT" Default="False" Mode="" Description="碰到无法重命名的合集等，自动删除种子" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="历史番剧下载" Target="AB_EP_COMPLETE" Default="False" Mode="" Description="" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="调试模式" Target="AB_DEBUG_MODE" Default="False" Mode="" Description="" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="过滤元素" Target="AB_NOT_CONTAIN" Default="720" Mode="" Description="输入想要过滤的元素，如 720，1080，等。&#xD;&#xA;&#xD;&#xA;    不同的元素用 | 分隔，例如 720|CHT&#xD;&#xA;    可以使用正则表达式，但是需要注意，特殊符号需要转义，例如 ( 表示 (。&#xD;&#xA;    这个选项建议填写：720|d+-d+，如果过滤选项添加过多，会影响到正常的 RSS 识别。对于番剧单独的自定义可以在 qBitorrent 中自定义。&#xD;&#xA;" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="启用 TMDB？" Target="AB_ENABLE_TMDB" Default="False" Mode="" Description="启动 TMDB 解析" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="语言" Target="AB_LANGUAGE" Default="zh" Mode="" Description="TMDB 解析后选择语言，仅在 TMDB 开启时有效。&#xD;&#xA;支持 zh、jp。" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="重命名方法" Target="AB_METHOD" Default="pn" Mode="" Description="重命名方法 normal 保留字幕组信息， pn 为纯净模式，advance 为高级模式，none 为空模式，不重命名" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="添加组名？" Target="AB_GROUP_TAG" Default="False" Mode="" Description="是否在下载规则中添加组名，方便查看。开启后规则命名为 [组名]规则名，关闭后规则命名为 [规则名]" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="请求间隔时间" Target="AB_INTERVAL_TIME" Default="7200" Mode="" Description="" Type="Variable" Display="advanced" Required="false" Mask="false"/>
>   <Config Name="重命名频率" Target="AB_RENAME_FREQ" Default="20" Mode="" Description="在一个运行周期内重命名频率" Type="Variable" Display="advanced" Required="false" Mask="false"/>
> </Container>
> ```
> 
> 我自己写的模板，有需要的大家可以用我的这份。我把环境变量全配置进去了。

用这个模板安装ab 后 ab启动完就停止运行

**Comment by greenhat616** [comment]
> 用这个模板安装ab 后 ab启动完就停止运行
@tao08ms 因为 AB 做了 BC，不再检测环境变量是否为空，这也可能是个 bug。
关键代码在：https://github.com/EstrellaXD/Auto_Bangumi/blob/0ed51014c2feedd80039198bb76270c657a3bbf4/backend/src/module/conf/const.py#L85-L100
这里直接对空字符串做了 split，然后立即做了列表访问，因此导致索引溢出，触发 panic。

**修复办法：你只需要移除 <u>HTTP 代理</u>，以及  <u>SOCKS 代理</u> 环境变量即可正常使用。**

cc @EstrellaXD 这个是有意做的 BC 嘛。
