### ISSUE TITLE
[解析器错误] [YYQ字幕组][五等分的新娘 剧场版 / Eiga Go-toubun no Hanayome][简日内嵌字幕][1080P][H264_AVC][WEBRIP][MP4]

### ISSUE THREAD

**Issue by wmyfelix** [EstrellaXD/Auto_Bangumi#136]
### 当前程序版本

estrellaxd/auto_bangumi         latest    eb67309354aa   2 months ago    121MB

### 解析器语言设置

默认：zh

### TMDB 解析

是

### 字幕组提供的名称

[YYQ字幕组][五等分的新娘 剧场版 / Eiga Go-toubun no Hanayome][简日内嵌字幕][1080P][H264_AVC][WEBRIP][MP4]

### 错误识别名称

 ERROR     Parser cannot analyse [YYQ字幕组][五等分的新娘 剧场版 / Eiga Go-toubun no Hanayome][简日内嵌字幕][1080P][H264_AVC][WEBRIP][MP4] 'NoneType' object has no attribute 'groups'

**Comment by EstrellaXD** [comment]
目前不支持剧场版识别，请等待新版本
