### ISSUE TITLE
[解析器错误] 无法解析诸如 07v2 的标题

### ISSUE THREAD

**Issue by Yesterday17** [EstrellaXD/Auto_Bangumi#141]
### 当前程序版本

2.5.25-fix

### 解析器语言设置

默认：zh

### TMDB 解析

否

### 字幕组提供的名称

[SweetSub&LoliHouse] 手工少女!! / Do It Yourself!! - 07v2 [WebRip 1080p HEVC-10bit AAC][简繁日内封字幕]（检索用：DIY）

### 错误识别名称

Parser cannot analyse [SweetSub&LoliHouse] 手工少女!! / Do It Yourself!! - 07v2 [WebRip 1080p HEVC-10bit AAC][简繁日内封字幕]（检索用：DIY） 'NoneType' object has no attribute 'groups'

**Comment by Yesterday17** [comment]
现有的标题规则限定了 `\[\d+.?[vV]\d{1}]`，必须有 `[]` 包裹才会识别 `v\d`，是不是可以把这里的中括号去掉（？

**Comment by shininome** [comment]
解决一个bug增加许多bug的感觉

**Comment by Abcuders** [comment]
> 现有的标题规则限定了 `\[\d+.?[vV]\d{1}]`，必须有 `[]` 包裹才会识别 `v\d`，是不是可以把这里的中括号去掉（？

[ ]不是让v的大小写都可以识别吗,识别的时候忽略大小写就应该可以去掉(不使用)这类[ ]
