### ISSUE TITLE
AB_DOWNLOAD_PATH配置的路径包含中文时，所有下载的文件重命名都会变成"Downloads SxxExx.mp4"

### ISSUE THREAD

**Issue by freedomcatjin** [EstrellaXD/Auto_Bangumi#165]
### 当前程序版本

Version 2.5.25-fix

### 重命名设置

advance

### 种子名称

[Comicat&KissSub][Kubo-san wa Mob wo Yurusanai][02][1080P][GB][MP4].mp4

### 文件路径

 /Downloads/动漫/久保同学不放过我 (2023)\Season 1/

### 错误命名

Downloads S01E02.mp4

**Comment by EstrellaXD** [comment]
为什么文件名和 Season 中间是反斜杠，你用的是什么系统

**Comment by freedomcatjin** [comment]
> 
(⊙﹏⊙)抱歉！斜杠smb复制的时候我忘记订正了。。。

**Comment by freedomcatjin** [comment]
> 为什么文件名和 Season 中间是反斜杠，你用的是什么系统。 AB 部署在哪里，QB 部署在哪里。

(⊙﹏⊙)抱歉！反斜杠是win10环境下smb复制的时候我忘记订正了。。。


AB和QB都部署在威联通的docker中

**Comment by EstrellaXD** [comment]
请确认一下最新版本是否还存在该问题
