### ISSUE TITLE
[Discussion]: 如何实现新番更新后通过上sever酱发送通知到微信

### ISSUE THREAD

**Issue by bearcloney** [EstrellaXD/Auto_Bangumi#168]
### 项目讨论

之前有使用nastoll，其中的这个通知功能我挺喜欢，不用sever酱也行，有什么方法能让微信收到新番更新或者下载好的通知

**Comment by Slinet6056** [comment]
或许可以试试这个带微信推送的qb [https://hub.docker.com/r/nevinee/qbittorrent](https://hub.docker.com/r/nevinee/qbittorrent)
