### ISSUE TITLE
[Feature Request]: 重命名时区分同一发布组的不同片源

### ISSUE THREAD

**Issue by PeterZhenhh** [EstrellaXD/Auto_Bangumi#170]
### 功能改进

在重命名时为同一发布组的不同片源加入"_片源"以解决文件名冲突
例如发布组[神楽坂 まひろ](原[NC-Raws])发布的《呆萌酷男孩》来自CR、Baha两个片源
期待重命名为“[NC-Raws_CR] 呆萌酷男孩 (2022)  S01 - 01 .mp4”和“[NC-Raws_Baha] 呆萌酷男孩 (2022)  S01 - 01 .mp4”两个文件

参考：https://github.com/PeterZhenhh/Auto_Bangumi/commit/b1bd5fa5d78531727150808012c9789a9fe322d4

**Comment by EstrellaXD** [comment]
#279
