### ISSUE TITLE
[Feature Request]: 关于重命名功能

### ISSUE THREAD

**Issue by PiDanShouRouZhouXD** [EstrellaXD/Auto_Bangumi#173]
### 功能改进

请问目前是否有重命名非QB下载的动画的功能？如果有，希望将实现方式加入wiki中；如果没有，希望增加此功能。

**Comment by EstrellaXD** [comment]
没有，可以看这个项目 [miracleyoo/anime_renamer](https://github.com/miracleyoo/anime_renamer)
