### ISSUE TITLE
问下有布署教学吗

### ISSUE THREAD

**Issue by Arcelibs** [EstrellaXD/Auto_Bangumi#18]
docker萌新，实际不怎么会用，有或者参考文件？

**Comment by EstrellaXD** [comment]
![Docker 入门指北](https://sspai.com/post/56893)

**Comment by Arcelibs** [comment]
> [Docker 入门指北](https://sspai.com/post/56893)

相当不错的说明，但是我看完还是不懂
![image](https://user-images.githubusercontent.com/49543451/170965386-cf8e7da7-ad08-4881-85b8-eab8c9557a74.png)

**Comment by EstrellaXD** [comment]
> > [Docker 入门指北](https://sspai.com/post/56893)
> 
> 相当不错的说明，但是我看完还是不懂，跑出一堆錯誤訊息 [error.txt](https://github.com/EstrellaXD/Auto_Bangumi/files/8797333/error.txt)

看起来你并没有链接上 qBittorrent，请检查：
- qBittorrent 是否安装
- qBittorrent 的地址和账户密码是否正确
- qBittorrent 和 AutoBangumi 是否在同一个主机内/同一个局域网内
- qBittorrent 是否开启WebUI，是否开启 HTTPS，如果开启 HTTPS 请关闭
