### ISSUE TITLE
[Feature Request]: 可否支持输出.plexmatch文件

### ISSUE THREAD

**Issue by lersh** [EstrellaXD/Auto_Bangumi#190]
### 功能改进

.plexmatch是plex支持的针对剧集的匹配文件，官方说明：https://support.plex.tv/articles/plexmatch/
好处是不需要改变文件目录结构就能匹配剧集信息，
最基本的使用方法是在剧集目录下新建.plexmatch文件
写入两行：

> tmdbid:剧集的tmdb的id
> season:第几季

只要文件名里有可识别的数字，剧集信息就能被plex很好的识别了
如果文件名也无法识别，可以继续添加：

> ep:第几集的数字:文件名

可否加一个开关，决定是否要输出这个文件帮助plex识别？

**Comment by EstrellaXD** [comment]
当前版本的改名 plex 应该匹配的很好才对啊？为啥还需要额外输出这样的文件？

**Comment by lersh** [comment]
非常抱歉，时间有点久了，我也不记得是哪个番剧有问题了，目前我确实不需要了，谢谢作者回复
