### ISSUE TITLE
[文档]本地部署的文档需要更新？

### ISSUE THREAD

**Issue by yfaimisaka** [EstrellaXD/Auto_Bangumi#194]
### 当前程序版本

v2.6.0-beta5

### 问题类型

其他问题

### 问题描述

[本地部署的文档](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2)似乎有些错误并且信息有些过时（？）
例如：
> `git checkout -n non-docker-deployment`

似乎是`git checkout -b non-docker-deployment`

> 修改 auto_bangumi/api.py 和 auto_bangumi/conf/const.py 中的几个 docker 挂载相关的绝对路径：
处
```
# api.py
14a15,17
> import os
> PKG_DIR = os.path.dirname(os.path.realpath(__file__))
>
58c61
<     json_config.save("/config/config.json", data)
---
>     json_config.save(os.path.join(PKG_DIR, "config/config.json"), data)

# const.py
2a3,5
> import os
> PKG_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
>
14c17
<     "info_path": "/config/bangumi.json",
---
>     "info_path": os.path.join(PKG_DIR, "config/bangumi.json"),
```
需要删除的`json_config.save("/config/config.json", data)`和`"info_path": "/config/bangumi.json",`似乎并不存在？

此处的文档可能需要更新

**Comment by EstrellaXD** [comment]
会在 2.6 正式上线的时候更新文档的

**Comment by yfaimisaka** [comment]
ok
