### ISSUE TITLE
[解析器错误] Nodetype groups

### ISSUE THREAD

**Issue by wzpyh** [EstrellaXD/Auto_Bangumi#197]
### 当前程序版本

最新

### 解析器语言设置

默认：zh

### TMDB 解析

否

### 字幕组提供的名称

【豌豆字幕组&风之圣殿字幕组】★04月新番[鬼灭之刃 刀匠村篇 Kimetsu_no_Yaiba-Katanakaji_no_Sato_Hen][02(46)][简体][1080P][MP4]

### 错误识别名称

throw error

**Comment by wzpyh** [comment]
Title_RE的正则增加一个就可以了(.*|\[.*])( -? \d+|\[\d+]|\[\d+.?[vV]\d{1}]|[第]?\d+[话話集]|\[\d+.?END]|**\[\d+\(\d{2}\)\]**)(.*)

**Comment by EstrellaXD** [comment]
这种奇怪的命名方式暂不作适配，不排除对正常番匹配的影响。
