### ISSUE TITLE
[错误报告] docker dev-latest 版本增加arm

### ISSUE THREAD

**Issue by MrRumpel** [EstrellaXD/Auto_Bangumi#198]
### 当前程序版本

2.6.0-beta5

### 问题类型

其他问题

### 问题描述

docker auto_bangumi:dev-latest 镜像没有arm
![image](https://user-images.githubusercontent.com/20477534/233789480-7de63c39-401c-4e1a-8767-ce3d67224376.png)

**Comment by EstrellaXD** [comment]
测试完功能之后才会加
