### ISSUE TITLE
[解析器错误]  和山田谈场 Lv999 的恋爱 错误识别为 和山田谈场 没了后面的

### ISSUE THREAD

**Issue by ResidualBlood** [EstrellaXD/Auto_Bangumi#206]
### 当前程序版本

V.2.6.0

### 解析器语言设置

默认：zh

### TMDB 解析

否

### 字幕组提供的名称

[ANi] 和山田谈场 Lv999 的恋爱 - 04 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]

### 错误识别名称

和山田谈场

**Comment by EstrellaXD** [comment]
看起来目前的解析器没有办法解决，后续版本手动在 WebUI 调整吧
