### ISSUE TITLE
[解析器错误] ★04月新番★ 似乎不下载解析

### ISSUE THREAD

**Issue by ResidualBlood** [EstrellaXD/Auto_Bangumi#207]
### 当前程序版本

V2.6.0

### 解析器语言设置

默认：zh

### TMDB 解析

否

### 字幕组提供的名称

【喵萌奶茶屋】★04月新番★[我内心的糟糕念头/Boku no Kokoro no Yabai Yatsu][04][1080p][简日双语][招募翻译]

### 错误识别名称

没了直接

**Comment by ResidualBlood** [comment]
同理 
```
[爱恋字幕社][4月新番][放学后失眠的你][Kimi wa Houkago Insomnia][03][1080p][MP4][简日双语]
```
似乎也没有解析

**Comment by MiaoJiawei** [comment]
可巧这俩我都有，都解析了，你看下是不是你设置那里有问题

**Comment by MiaoJiawei** [comment]
> 可巧这俩我都有，都解析了，你看下是不是你设置那里有问题

是不是有可能订阅刷新了但是下载种子的时候被GFW了

**Comment by ResidualBlood** [comment]
> 可巧这俩我都有，都解析了，你看下是不是你设置那里有问题

我老版本也正常, 但更新成新版本就不解析了
设置和上面设置一样

**Comment by ResidualBlood** [comment]
> > 可巧这俩我都有，都解析了，你看下是不是你设置那里有问题
> 
> 是不是有可能订阅刷新了但是下载种子的时候被GFW了

AB 和 QB 都在 国外, AB访问都正常

**Comment by ResidualBlood** [comment]
```
[DAY字幕组][女神的露天咖啡厅/Megami no Café Terrace][第3话「开业!」][简日双语][WEBrip][1080P][MP4][461.7 MB]
```
qb 标蓝未解析
