### ISSUE TITLE
[错误报告]qbtorrent链接地址只允许IP地址导致HTTPS链接失效

### ISSUE THREAD

**Issue by zelphar** [EstrellaXD/Auto_Bangumi#210]
### 当前程序版本

2.6

### 问题类型

WebUI

### 问题描述

填入qbtorrent的链接地址时加入了输入检查，目前只允许IP地址
若开启了HTTPS与域名绑定，则无法正常连接到qbtorrent
希望能允许填入域名

**Comment by EstrellaXD** [comment]
https://github.com/Rewrite0/Auto_Bangumi_WebUI/pull/6
