### ISSUE TITLE
[错误报告] 2.6.1版本连接失败

### ISSUE THREAD

**Issue by SilentC1ty** [EstrellaXD/Auto_Bangumi#213]
### 当前程序版本

2.6.1

### 问题类型

程序运行问题

### 问题描述

[2023-04-27 19:26:34,778] WARNING:  ERROR with Connection.Please check DNS/Connection settings
一直弹出如上日志，修改/etc/resolve.conf中的dns为8.8.8.8也会出现

**Comment by EstrellaXD** [comment]
请升级版本确认使用代理反代等

**Comment by SilentC1ty** [comment]
> 请升级版本确认使用代理反代等

我看2.6.0release不是说自带反代了吗，现在手动把config.json里面的url换成discussion里面提供的那个反代网址好了

**Comment by EstrellaXD** [comment]
> > 请升级版本确认使用代理反代等
> 
> 
> 
> 我看2.6.0release不是说自带反代了吗，现在手动把config.json里面的url换成discussion里面提供的那个反代网址好了

自带反代的前提是你给 ab 挂代理，请等官方文档写完看一下吧，这个issue先关了
