### ISSUE TITLE
[Discussion]: 从2.6开始，重名名时文件夹名的获取从title_raw变成official_title了

### ISSUE THREAD

**Issue by sakuyamaij** [EstrellaXD/Auto_Bangumi#220]
### 项目讨论

rss解析语言为jp
重命名方法为pn
tmdb解析开启

举例：
《我的百合乃工作是也》这部动画
2.5时
文件夹Watashi no Yuri wa Oshigoto desu
文件名Watashi no Yuri wa Oshigoto desu S01E01.mp4

2.6相同配置下
文件夹私の百合はお仕事です！ (2023)
文件名Watashi no Yuri wa Oshigoto desu S01E01.mp4

采用了data.json中的official_title
而不是2.5时的用title_raw

不清楚这是新版本的feature还是bug？

**Comment by EstrellaXD** [comment]
en+tmdb off
