### ISSUE TITLE
[错误报告]订阅【宝可梦地平线】后，自动添加了所有宝可梦的剧集的下载

### ISSUE THREAD

**Issue by lersh** [EstrellaXD/Auto_Bangumi#241]
### 当前程序版本

2.6.9

### 问题类型

WebUI

### 问题描述

使用2.6.6添加了【宝可梦 地平线】的订阅后，会将名称识别为【精灵宝可梦 (1997)】，这个已经在 #239 里反馈了。
然后我更新docker到2.6.9后，发现自动在qb里添加了87个宝可梦的剧集的下载，都是旧的宝可梦的剧集。

**Comment by EstrellaXD** [comment]
这种没太多办法解决，只能订阅之后在 QB 里面自行修改了

**Comment by lersh** [comment]
> 这种没太多办法解决，只能订阅之后在 QB 里面自行修改了

自行修改解决不了以下两个问题：
1.自动命名，每个单集都被自动改名为【精灵宝可梦(1997) S01E001】,这个单集的名字我是没法在QB里设定规则修改的。
2.自动下载旧的宝可梦的剧集，这个要如何阻止AB去下载呢？

**Comment by EstrellaXD** [comment]
> > 这种没太多办法解决，只能订阅之后在 QB 里面自行修改了
> 
> 自行修改解决不了以下两个问题： 1.自动命名，每个单集都被自动改名为【精灵宝可梦(1997) S01E001】,这个单集的名字我是没法在QB里设定规则修改的。 2.自动下载旧的宝可梦的剧集，这个要如何阻止AB去下载呢？

1. 把保存路径修改成正确的就可以了，如 `宝可梦 地平线 (2023)/Season1/`，这里包括自动下载规则和已经下载的种子。这些问题在 FAQ 里面都详细提到了，下次请自行查阅。
2. 在 QB 中删除即可，AB 不会重复添加

**Comment by lersh** [comment]
> > > 这种没太多办法解决，只能订阅之后在 QB 里面自行修改了
> > 
> > 
> > 自行修改解决不了以下两个问题： 1.自动命名，每个单集都被自动改名为【精灵宝可梦(1997) S01E001】,这个单集的名字我是没法在QB里设定规则修改的。 2.自动下载旧的宝可梦的剧集，这个要如何阻止AB去下载呢？
> 
> 1. 把保存路径修改成正确的就可以了，如 `宝可梦 地平线 (2023)/Season1/`，这里包括自动下载规则和已经下载的种子。这些问题在 [FAQ](https://github.com/EstrellaXD/Auto_Bangumi/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E/#%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E7%9A%84%E4%BD%BF%E7%94%A8-autobangumi-%E4%BB%A5%E5%8F%8A-qbittorrent) 里面都详细提到了，下次请自行查阅。
> 2. 在 QB 中删除即可，AB 不会重复添加

谢谢。我在QB已经将规则的保存路径改为`宝可梦 地平线 (2023)/Season1/`了，但是已经下载的视频的名称并没有自动改为`宝可梦 地平线 (2023) S01E001.mp4`这样的名字，是要等新的一集更新后，新下载的才会自动变为`宝可梦 地平线 (2023) S01E005.mp4`这样的名字吗？
