### ISSUE TITLE
[重命名错误]

### ISSUE THREAD

**Issue by wudingmao** [EstrellaXD/Auto_Bangumi#243]
### 当前程序版本

2.6

### 重命名设置

默认：pn

### 种子名称

[ANi] 熊熊勇闖異世界 PUNCH！ - 06 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4

### 文件路径

Bangumi\熊熊勇闯异世界 PUNCH！\Season 1

### 错误命名

熊熊勇闖異世界 PUNCH！ S01E06

### 发生问题时系统日志

```shell
部分番剧如果番剧命中没有类似于“第一季“、”第二季”之类的明确说明是第几季的标题的话有概率识别错误季度，甚至有点时候第一集是正确到第二季的但是第二集却分到了第一季（可能与字幕组命名有关），希望webui中可以增加一个手动修正调试为自己习惯的命名规则的地方

[ANi] 熊熊勇闖異世界 PUNCH！ - 06 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 熊熊勇闖異世界 PUNCH！ S01E06.mp4
```

**Comment by EstrellaXD** [comment]
https://github.com/EstrellaXD/Auto_Bangumi/issues/199#issuecomment-1519853684
未来版本会推出的
