### ISSUE TITLE
[错误报告]把源站链接改成mikanime.tv后添加订阅新番和旧番都出现{ "status": "Failed to parse link" }

### ISSUE THREAD

**Issue by lizi1111** [EstrellaXD/Auto_Bangumi#245]
### 当前程序版本

2.6.9

### 问题类型

其他问题

### 问题描述

把源站链接改成mikanime.tv后添加订阅新番和旧番都出现{ "status": "Failed to parse link" }
rss:https://mikanime.tv/RSS/MyBangumi?token=QmKAXDz7N8jndq4bXKjvEA%3d%3d
https://mikanime.tv/RSS/Bangumi?bangumiId=2831&subgroupid=21

### 发生问题时系统日志

```shell
2023/5/8 23:56:34  INFO:     172.17.0.1:40440 - "GET /api/v1/status HTTP/1.1" 200 OK
2023/5/8 23:56:30  INFO:     172.17.0.1:40440 - "GET /api/v1/status HTTP/1.1" 200 OK
```

**Comment by EstrellaXD** [comment]
挂代理了么

**Comment by lizi1111** [comment]
> 

没挂 这个域名是只限国内的吧
