### ISSUE TITLE
[Feature Request]: 企业微信通知

### ISSUE THREAD

**Issue by Jaie0801** [EstrellaXD/Auto_Bangumi#254]
### 功能改进

可以考虑通知功能，增加企业微信群聊机器人通知和企业微信应用通知，这种是免费的无限制、不用fq的

**Comment by EstrellaXD** [comment]
评估了一下，已经有 Server Chan 微信推送了。我自己不想再申请注册一个微信 BOT，如果有人可以贡献的话我很乐意放进主程序中。
