### ISSUE TITLE
[Feature Request]: Web UI 增加手动拉取 RSS 和手动重命名

### ISSUE THREAD

**Issue by Robotxm** [EstrellaXD/Auto_Bangumi#257]
### 功能改进

一点强迫症需求，有时候不想等 AB 定时触发刷新 RSS 和重命名。如果 Web UI 有个按钮手动执行的话就好了。

**Comment by EstrellaXD** [comment]
3.0 已经有了

**Comment by Robotxm** [comment]
> 3.0 已经有了

感谢，我这就去更新 3.0 试试

**Comment by EstrellaXD** [comment]
> > 3.0 已经有了
> 
> 感谢，我这就去更新 3.0 试试

还在beta中... 😂
