### ISSUE TITLE
[重命名错误]normal模式保留了全部信息

### ISSUE THREAD

**Issue by hot36952** [EstrellaXD/Auto_Bangumi#263]
### 当前程序版本

Version 2.6.9

### 重命名设置

normal

### 种子名称

[Lilith-Raws] Kono Subarashii Sekai ni Bakuen wo! - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4

### 文件路径

/downloads/Media/Bangumi/为美好的世界献上爆焰！/Season 1

### 错误命名

[Lilith-Raws] Kono Subarashii Sekai ni Bakuen wo! S01E01[Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4

### 发生问题时系统日志

```shell
[2023-05-14 16:07:05,520] INFO:     Kono Subarashii Sekai ni Bakuen wo! S01E01.mp4 >> [Lilith-Raws] Kono Subarashii Sekai ni Bakuen wo! S01E01[Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4
-
原来用pn模式，重名为“Kono Subarashii Sekai ni Bakuen wo! S01E01.mp4”，改为normal模式后，重名为“[Lilith-Raws] Kono Subarashii Sekai ni Bakuen wo! S01E01[Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4”，结果保留了全部信息，不知道是错误还是normal保留全部信息？
-
实际上我想要的是“[Lilith-Raws] Boku no Kokoro no Yabai Yatsu S01E01 [1080p][CHT].mp4”，希望开发组能完善重命名规则。
```

**Comment by EstrellaXD** [comment]
结果正常，特殊需求清自己开发。

**Comment by hot36952** [comment]
> 结果正常，特殊需求清自己开发。

我认为这个结果不符合normal模式的说明，或存在歧义，默认是pn模式，保留“番名+SXXEXX”，normal模式的说明“保留字幕组”，按说明理解是保留“字幕组+番名+SXXEXX”，另外我认为这个需求是普遍存在的，希望开发组能考虑下。
