### ISSUE TITLE
[错误报告]

### ISSUE THREAD

**Issue by lq1984** [EstrellaXD/Auto_Bangumi#269]
### 当前程序版本

latest

### 问题类型

程序运行问题

### 问题描述

修改torrent种子文件中的信息将会导致 torrent InfoHash 变动，从而可能会被原有tracker 拒绝

**Comment by EstrellaXD** [comment]
hash 不会变化啊？从哪里获得了该信息会改变 HASH 的信息

**Comment by lq1984** [comment]
> hash 不会变化啊？从哪里获得了该信息会改变 HASH 的信息

首先 torrent 的hash 是通过计算 Torrent.Info得到的， Info中包含了文件名相关信息，如果修改了该信息，将会导致 计算出的Hash有变动

**Comment by EstrellaXD** [comment]
你得到的信息是错误的，info.hash 在种子下载的时候就已经固定了，并不会跟着内部文件更改而更改。如果你有 hash 更改的证据，贴出前后文件更改导致 hash 更改的截图

**Comment by lq1984** [comment]
我建议是 添加种子后 调用qb 的 renameFile 进行对文件的重命名，而不是直接修改
