### ISSUE TITLE
[错误报告]登陆接口存在sql注入

### ISSUE THREAD

**Issue by Belos-pretender** [EstrellaXD/Auto_Bangumi#272]
### 当前程序版本

3.0-beta5

### 问题类型

程序运行问题

### 问题描述

/src/module/database/user.py 44行执行sql时采取了直接将用户输入的用户名字段(username)拼接进sql语句的操作，确认会导致sql注入 基于时间盲注payload如下
- 1' or (case when(substr(sqlite_version(),1,1)='3' ) then randomblob ( 1000000000 )  else 0 end ) /*
使用该payload应该可明显观察到返回等待时间变长
建议将44行写法改为参数化查询规避该风险，也建议将所有涉及sql操作的代码都修改为参数化查询，下为参数化查询示例
self._cursor.execute(f"SELECT * FROM {self.__table_name} WHERE username=?", (username,))

**Comment by EstrellaXD** [comment]
Fix in [f45dcac](https://github.com/EstrellaXD/Auto_Bangumi/commit/f45dcac3d06abb1a620ae40054df73b90b15f15a)
