### ISSUE TITLE
[Feature Request]: Apply 改成 Apply + Restart

### ISSUE THREAD

**Issue by ZIZNAH** [EstrellaXD/Auto_Bangumi#288]
### 功能改进

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/47733889/58f5a318-ac72-4700-a343-6613beea230f)
                       ||
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/47733889/895ba823-5fda-4506-8d53-63c09d1fecd6)
                       +
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/47733889/9bcd7182-a0a3-437b-a651-0f97648c7e65)

**Comment by EstrellaXD** [comment]
下次请用简洁的语言描述

**Comment by ZIZNAH** [comment]
了解
