### ISSUE TITLE
[Feature Request]: 添加企业微信通道推送通知

### ISSUE THREAD

**Issue by umbors** [EstrellaXD/Auto_Bangumi#291]
### 功能改进

现有三种推送方式里，server-chan要收费解锁完全体，bark只有iOS端，tg需要常态挂梯子，用起来都不太方便。之前参考https://github.com/easychen/wecomchan 把企业微信通道集成到ab里，2.0大版本一直用着挺稳定的。今天看到3.0有正式版，更新完又稍微改动了下代码，推送消息效果如下（用了poster_link显示海报图，感觉好看不少）：

![20230604-010635](https://github.com/EstrellaXD/Auto_Bangumi/assets/14857490/49b0b224-e1fa-4189-9bad-4b3b47278d54)

主要是在plugin文件夹里添加了wecom.py，init.py和config.js里添加了wecom有关内容（照葫芦画瓢），如果跟现有计划不冲突的话我就开个PR去。

**Comment by EstrellaXD** [comment]
可以pr
