### ISSUE TITLE
[错误报告] Config中的DownloadPath不生效

### ISSUE THREAD

**Issue by Arcate** [EstrellaXD/Auto_Bangumi#293]
### 当前程序版本

3.1.0

### 问题类型

程序运行问题

### 问题描述

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/29850930/a690c701-2947-4dd5-9246-ebedf7e5a255)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/29850930/961b5697-49d5-4294-a9e7-a23435869be9)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/29850930/d5aa0cc9-2c16-4036-9245-16246af82bb2)

**Comment by EstrellaXD** [comment]
保存config之后是否有重启ab，如果番剧已经添加请删禁用再启用

**Comment by Arcate** [comment]
好了谢谢，原来要去docker里直接重新启动，我以为新WebUI点Restart就行了=.=
