### ISSUE TITLE
bug反馈   扩展名 .!qB

### ISSUE THREAD

**Issue by HoliaMagirl** [EstrellaXD/Auto_Bangumi#3]
环境：arm64（树莓派4b）
  ab版本：V2.2.8
  qb版本：4.4.1

当qb设置（下载/为不完整的文件添加扩展名 .!qB）启用时，通过ab建立的所用qb下载任务均错误

**Comment by EstrellaXD** [comment]
是否有 qBittorrent 的 log，应该在 `/config` 里面可以找到。
