### ISSUE TITLE
路径截取建议改成用pathlib，split("/")导致代码无法在原生windows上运行

### ISSUE THREAD

**Issue by azuse** [EstrellaXD/Auto_Bangumi#30]
https://github.com/EstrellaXD/Auto_Bangumi/blob/20fc2846f5e19730d3a11cf2bc2d74957e3fc536/auto_bangumi/core/renamer.py#L62

**Comment by EstrellaXD** [comment]
在 3733c6c814af941b3a494e36244e271a30070183 中修复
