### ISSUE TITLE
webui上的配置每次apply都会覆盖配置文件

### ISSUE THREAD

**Issue by kof8855** [EstrellaXD/Auto_Bangumi#314]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.3

### 问题类型

WebUI

### 问题描述

建议在webui上需要实时读出最新的配置文件的修改信息，手动vi修改的配置文件webui上也能读取到才行。不然vi改了配置文件，webui上有apply一次，那又被覆盖了

### 发生问题时系统日志

```bash
无
```

**Comment by EstrellaXD** [comment]
@kof8855 没有理解，为什么要同时用编辑器和webui操作配置文件呢？

**Comment by Rewrite0** [comment]
@kof8855 webui只在进入config页时会获取最新的 config, 你也可以点击cancel来恢复至最新的 config
