### ISSUE TITLE
[解析器错误] 无法识别总集篇

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#318]
### 当前程序版本

3.0-beta10

### 解析器语言设置

默认：zh

### TMDB 解析

是

### 字幕组提供的名称

[KitaujiSub] THE iDOLM@STER CINDERELLA GIRLS U149 [7.5][Webrip][1080p][HEVC_AAC][CHS_JP].mp4

### 错误识别名称

无法识别总集篇

**Comment by EstrellaXD** [comment]
@Ovler-Young 这类总集篇暂不做适配，可以移动到别的分类
