### ISSUE TITLE
[错误报告] 部署问题

### ISSUE THREAD

**Issue by xqingting** [EstrellaXD/Auto_Bangumi#323]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0

### 问题类型

其他问题

### 问题描述

部署问题。。。跟着教程第二步就出错了。。Windows

### 发生问题时系统日志

```bash
F:\Downloads\动漫\Auto_Bangumi>((Get-Content -path .\src\main.py -Raw) -replace 'if VERSION != "DEV_VERSION":','if True:') | Set-Content -Path .\src\main.py
此时不应有 -replace。
```

**Comment by bee10301** [comment]
教程是使用 powershell 而非 cmd ，才能更方便執行一些指令。

你可以：
- 改用 powershell 來執行這個指令
- 手動修改 `\backend\src\module\api\web.py` 文檔。將 `if VERSION != "DEV_VERSION":` 改為 `if True:`
