### ISSUE TITLE
海报墙没有图片

### ISSUE THREAD

**Issue by wudingmao** [EstrellaXD/Auto_Bangumi#324]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.3

### 问题类型

WebUI

### 问题描述

海报墙中中不显示图片，数据库中是有图片地址的，请问是否添加相关映射
![图片](https://github.com/EstrellaXD/Auto_Bangumi/assets/59632330/8eb08289-8b25-4c78-808f-e38610f12106)
![图片](https://github.com/EstrellaXD/Auto_Bangumi/assets/59632330/ae7efc2c-2ba2-4149-b8a1-d6193b278e50)

**Comment by EstrellaXD** [comment]
挂梯子
