### ISSUE TITLE
AB_NOT_CONTAIN 这一参数能否支持多个关键词过滤

### ISSUE THREAD

**Issue by yulkey** [EstrellaXD/Auto_Bangumi#34]
AB_NOT_CONTAIN 这一参数能否支持多个关键词过滤，如果可以，使用的是什么分隔符（我翻了下源码，没找到相关的分割）

这一需求的来源是这一季的派对浪客孔明
有一个组提供了两种清晰度的源
[猎户不鸽发布组] 派对浪客诸葛孔明 / 派对咖孔明 Paripi Koumei [10] [1080p+] [简中] [网盘] [2022年4月番] [1,011.5 MB]
[猎户不鸽发布组] 派对浪客诸葛孔明 / 派对咖孔明 Paripi Koumei [10] [1080p] [简中] [网盘] [2022年4月番] [414.2 MB]
其他的组都比它慢2天，因此这个组成了唯一选择

因此产生了需要过滤 1080p+ 这一清晰度的需求，但是我尝试了 `空格`、`;`、`,` 三种分隔符都没有产生预期效果
所以是并未提供多个关键词的功能，还是我的操作有误

**Comment by EstrellaXD** [comment]
这里是使用[正则表达式的语法](https://www.runoob.com/regexp/regexp-syntax.html)
使用 `AB_NOT_CONTAIN=720|1080p+` 可以达到你想要的的过滤效果

**Comment by yulkey** [comment]
明白了（我就这个一个忘了试

谢谢
