### ISSUE TITLE
[Feature Request]: 关于RSS命名一些功能页面的调整建议

### ISSUE THREAD

**Issue by JishuLiu6** [EstrellaXD/Auto_Bangumi#343]
### 功能改进

**亲爱的大佬们，能否做出以下改进：**
本人使用的是windows下基于docker desktop环境部署的服务，提出以下修改意见：

1.  在 `设置 --> Downloader Setting` 模块下是否能取消IP的输入，只输入端口，这样会修改代码中读取IP的位置用docker别名代替，但是能极大减少折腾网络的时间，我相信有一部分人是在 “Please check DNS”类似的问题下劝退的。（也有可能是我打开方式不对）
2.  能否添加识别RSS后，展示一部分通过RSS获取到的番剧列表命名，以供添加适当的 `Exclude`,过滤掉特殊的剧集。
3.  能否添加一个页面，能查看已命名的资源内容，检查番剧是否已经成功命名了 

**感谢大佬们为开源事业作出的贡献！**

**Comment by EstrellaXD** [comment]
1. 不考虑，并不是所有人都在 Docker 中部署 QB 和 AB的
2. 目前 WebUI 已经有这个功能了
3. 没有太大意义

**Comment by JishuLiu6** [comment]
1. 比较适合做分支路线吧，docker那段教程只能启动，不能完美的运行，大部分用户还是docker档吧。
2.并没有看到展示获取到的rss，是直接去下载了，确定后在下载，体验真的会很多
3.可以不提
