### ISSUE TITLE
希望修复历史追番逻辑

### ISSUE THREAD

**Issue by avsba001** [EstrellaXD/Auto_Bangumi#35]
版本2.4.9
问题描述：
               在开启历史追番的情况下，因为没有在mikan取消追番（mikan取消追番真的麻烦......），删除已观看完毕的番剧，bangumi会在下次扫描中重新下载番剧。

**Comment by EstrellaXD** [comment]
请更新到 2.4.11 再进行尝试，应该已经修复。

**Comment by avsba001** [comment]
> 请更新到 2.4.11 再进行尝试，应该已经修复。 如果尝试仍然出错，请打开 `DEBUG` 模式提供一下 `LOG`

docker上latest直接到2.50 b1了，新bug出现，暂时测不了这个issue bug，我另开一贴吧
