### ISSUE TITLE
[错误报告] 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by a342818026** [EstrellaXD/Auto_Bangumi#357]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0

### 问题类型

程序运行问题

### 问题描述

系统是Ubuntu 22lts。昨天设置静态IP之后在重新拉起QB和AutoBangumi，发现新番自动改名的功能失效了，今天再次尝试拉起，一开始能成功，但功能没有恢复，后来AutoBangumi直接无法拉起，报如下错误。似乎是虚拟网卡的问题？ifconfig也查不到veth9307dc9。

### 发生问题时系统日志

```bash
[+] Building 0.0s (0/0)                                                                                                                                                                                       
[+] Running 1/2
 ✔ Container qBittorrent  Running                                                                                                                                                                        0.0s 
 ⠦ Container AutoBangumi  Starting                                                                                                                                                                       0.7s 
Error response from daemon: failed to create endpoint AutoBangumi on network autobangumi_auto_bangumi: adding interface vethfe6c620 to bridge br-b248093c0b5a failed: Device does not exist
```

**Comment by EstrellaXD** [comment]
看着是你docker配置问题，非程序bug

**Comment by a342818026** [comment]
> 看着是你docker配置问题，非程序bug

确实是，不好意思。
弄了一上午没搞定，看jellyfin运行正常才想说会不会是AutoBangumi的问题……
后来发现单独装QBT也有问题，搞到现在才弄好。似乎是docker和之前为bridge-utils有冲突。
