### ISSUE TITLE
有没有办法自定义重命名的格式

### ISSUE THREAD

**Issue by wzl778633** [EstrellaXD/Auto_Bangumi#36]
首先，感谢这个项目解放我的双手
但是现在的重命名规则似乎是定死的：

```
Bangumi
├── bangumi_A_title
│   ├── SO1
│   │   ├── A E01.mp4
│   │   ├── A E02.mp4
│   │   ├── A E03.mp4
│   │   └── A E04.mp4
.............
```
我现在用的是 jellyfin作为流媒体，虽然某种程度上这样的命名规则也被能识别，但由于命名的差异性似乎在个别番剧季度识别上存在点问题。现在的版本有方法能让我修改 或是自定义season 或者 episode 的命名格式吗？ 比如讲SO1 ==> Season 01， A E01.mp4 ==> A S01E01.mp4.

**Comment by EstrellaXD** [comment]
S01 >> Season 01 这样的文件夹命名是可以开放给用户调整的，下个版本就会添加。
E01 >> S01E01 从现在字幕组对番剧命名方式上面会存在一定的问题，开放之后可能会产生更多的季度错乱。
比如 街角魔族 辉夜大小姐 这些并不会在标题中提供明确季度信息的番剧。

**Comment by wzl778633** [comment]
感谢回复，那是不是意味着其实我们只能对 集数 进行解析？
那是否可能 提供一些控制台命令手动导入季信息呢

**Comment by EstrellaXD** [comment]
- AutoBangumi 根据字幕组提供的番剧 title 进行解析，并不会与 IMDB 或者 TMDB 进行比对获取剧集信息。因此字幕组如果没有提供季度信息，AutoBangumi 会统一视为 `S01`。
- 季度信息可以在 qBittorrent 的下载规则里面自行修改，qB 也提供了批量移动文件的功能。
- 根据我的经验，如果上级文件夹已经有季度信息，下级文件不需要有季度信息应该也可以正常刮削，想问一下 jellyfin 出现问题是什么情况，是否可以提供具体案例以便我分析改进。
- 番剧遗漏补全功能是指，如果你在季中突然想要额外追一部番剧，那么 AutoBangumi 会帮你把这部番剧的之前剧集下载并整理。如果要追已经完结的番剧，可以等`2.5.0`版本中提供的历史合集补全 API

**Comment by mikusaa** [comment]
古见同学这种一季度24集但分开放送的番，字幕组是按同一季度连续命名的。
![image](https://user-images.githubusercontent.com/31799398/173334805-55389e18-6eac-4c61-a034-63ba6b8bdb5c.png)
但TMDB分成了2季。
![image](https://user-images.githubusercontent.com/31799398/173335021-89e56db8-9c53-458c-86ad-74f7853139cc.png)
TVDB亦是如此。
![image](https://user-images.githubusercontent.com/31799398/173335322-9c9bc8dd-efc4-455e-bec2-762e89aa2d7c.png)
有什么好办法解决这种问题呢？

**Comment by wzl778633** [comment]
> * AutoBangumi 根据字幕组提供的番剧 title 进行解析，并不会与 IMDB 或者 TMDB 进行比对获取剧集信息。因此字幕组如果没有提供季度信息，AutoBangumi 会统一视为 `S01`。
> * 季度信息可以在 qBittorrent 的下载规则里面自行修改，qB 也提供了批量移动文件的功能。
> * 根据我的经验，如果上级文件夹已经有季度信息，下级文件不需要有季度信息应该也可以正常刮削，想问一下 jellyfin 出现问题是什么情况，是否可以提供具体案例以便我分析改进。
> * 番剧遗漏补全功能是指，如果你在季中突然想要额外追一部番剧，那么 AutoBangumi 会帮你把这部番剧的之前剧集下载并整理。如果要追已经完结的番剧，可以等`2.5.0`版本中提供的历史合集补全 API

jellyfin的命名格式为
```
Bangumi
├── bangumi_A_title
│   ├── Season 01
│   │   ├── A S01E01.mp4
│   │   ├── A S01E02.mp4
│   │   ├── A S01E03.mp4
│   │   └── A S01E04.mp4
```
下图是我刚刚使用的一个example：
![image](https://user-images.githubusercontent.com/55415793/173334531-feb9166b-ff6a-453c-b01a-7146ae6f7b00.png)
jellyfin的刮削器应该是_严格_按照尾部的命名格式来的。也就是说无论是季文件夹还是单集数都是按照这个命名格式单一查询。我所使用的是IMDB。在上面的例子中，我没有对名字做任何调整而是让AutoBangumi自动将文件下载到我已有的文件夹中（我手动修改了已有文件夹的bangumi_A_title以及Season 01以便能被识别），在我jellyfin的网页中，这两集无法被识别。

但我手动将这两集的后缀改为S01E08/S01E09后，jellyfin的刮取器就能正常刮取这两集的元数据了。

又比如以下图的约会大作战为例，即便我的第四季内的文件有我之前以英文命名的文件和AutoBangumi自动生成的中文名，只要后缀格式被我修改正确后，jellyfin刮取器依旧能正常工作。
![image](https://user-images.githubusercontent.com/55415793/173335980-957063c1-6998-438c-b897-de846269d5af.png)

所以对于jellyfin的刮取器而言，文件名格式重要性>>文件结构重要性。

希望有所帮助！

**Comment by EstrellaXD** [comment]
> 古见同学这种一季度24集但分开放送的番，字幕组是按同一季度连续命名的。
> ![image](https://user-images.githubusercontent.com/31799398/173334805-55389e18-6eac-4c61-a034-63ba6b8bdb5c.png)
> 但TMDB分成了2季。
> ![image](https://user-images.githubusercontent.com/31799398/173335021-89e56db8-9c53-458c-86ad-74f7853139cc.png)
> TVDB亦是如此。
> ![image](https://user-images.githubusercontent.com/31799398/173335322-9c9bc8dd-efc4-455e-bec2-762e89aa2d7c.png)
> emby跟着tmdb/tvdb走，元数据上就出了问题。有什么好办法解决这种问题呢？

如果想要自动化的话，存在的问题非常多：
- 如果要对于第二季的剧集进行转换，不确定第一季的最后一集是第几集。
- 如果有番剧是连续的超过一个季度的，这样转换会出更多的问题。

现阶段的方法：
- 手动调整第一季和第二季的规则。
- 和字幕组反馈这个问题，问题的根源是字幕组命名不规范而非 AB 功能问题。
- 使用 TMM 等工具。

如果想要在 AB 解决，需要搭建的基础设施太多，并且需要有稳定能够链接 IMDB/TMDB 的网络环境，目前不在 Roadmap 中。只能先手动调整。

**Comment by EstrellaXD** [comment]
> > * AutoBangumi 根据字幕组提供的番剧 title 进行解析，并不会与 IMDB 或者 TMDB 进行比对获取剧集信息。因此字幕组如果没有提供季度信息，AutoBangumi 会统一视为 `S01`。
> > * 季度信息可以在 qBittorrent 的下载规则里面自行修改，qB 也提供了批量移动文件的功能。
> > * 根据我的经验，如果上级文件夹已经有季度信息，下级文件不需要有季度信息应该也可以正常刮削，想问一下 jellyfin 出现问题是什么情况，是否可以提供具体案例以便我分析改进。
> > * 番剧遗漏补全功能是指，如果你在季中突然想要额外追一部番剧，那么 AutoBangumi 会帮你把这部番剧的之前剧集下载并整理。如果要追已经完结的番剧，可以等`2.5.0`版本中提供的历史合集补全 API
> 
> jellyfin的命名格式为
> 
> ```
> Bangumi
> ├── bangumi_A_title
> │   ├── Season 01
> │   │   ├── A S01E01.mp4
> │   │   ├── A S01E02.mp4
> │   │   ├── A S01E03.mp4
> │   │   └── A S01E04.mp4
> ```
> 
> 下图是我刚刚使用的一个example： ![image](https://user-images.githubusercontent.com/55415793/173334531-feb9166b-ff6a-453c-b01a-7146ae6f7b00.png) jellyfin的刮削器应该是_严格_按照尾部的命名格式来的。也就是说无论是季文件夹还是单集数都是按照这个命名格式单一查询。我所使用的是IMDB。在上面的例子中，我没有对名字做任何调整而是让AutoBangumi自动将文件下载到我已有的文件夹中（我手动修改了已有文件夹的bangumi_A_title以及Season 01以便能被识别），在我jellyfin的网页中，这两集无法被识别。
> 
> 但我手动将这两集的后缀改为S01E08/S01E09后，jellyfin的刮取器就能正常刮取这两集的元数据了。
> 
> 又比如以下图的约会大作战为例，即便我的第四季内的文件有我之前以英文命名的文件和AutoBangumi自动生成的中文名，只要后缀格式被我修改正确后，jellyfin刮取器依旧能正常工作。即使该文件在文件夹之外。 ![image](https://user-images.githubusercontent.com/55415793/173335980-957063c1-6998-438c-b897-de846269d5af.png)
> 
> 所以对于jellyfin的刮取器而言，文件名格式重要性>>文件结构重要性。
> 
> 希望有所帮助！

谢谢回复，看起来 Plex 在模糊识别的准确度上远高于 Jellyfin。
可以添加一个选项，让你们手动选择是否增加剧集信息，但是如果出现类似
街角魔族2丁目 这样的番剧，AB 只能识别为第一季，添加之后也为 `S01E**`，不清楚是否会对 Jellyfin 的刮削产生影响。

推荐也可以去 Jellyfin 那边反馈一下，增加对于 `E**` 这样没有季度名称的识别。还有一些问题可以看 [楼上](https://github.com/EstrellaXD/Auto_Bangumi/issues/36#issuecomment-1153763687)

**Comment by mikusaa** [comment]
> > * AutoBangumi 根据字幕组提供的番剧 title 进行解析，并不会与 IMDB 或者 TMDB 进行比对获取剧集信息。因此字幕组如果没有提供季度信息，AutoBangumi 会统一视为 `S01`。
> > * 季度信息可以在 qBittorrent 的下载规则里面自行修改，qB 也提供了批量移动文件的功能。
> > * 根据我的经验，如果上级文件夹已经有季度信息，下级文件不需要有季度信息应该也可以正常刮削，想问一下 jellyfin 出现问题是什么情况，是否可以提供具体案例以便我分析改进。
> > * 番剧遗漏补全功能是指，如果你在季中突然想要额外追一部番剧，那么 AutoBangumi 会帮你把这部番剧的之前剧集下载并整理。如果要追已经完结的番剧，可以等`2.5.0`版本中提供的历史合集补全 API
> 
> jellyfin的命名格式为
> 
> ```
> Bangumi
> ├── bangumi_A_title
> │   ├── Season 01
> │   │   ├── A S01E01.mp4
> │   │   ├── A S01E02.mp4
> │   │   ├── A S01E03.mp4
> │   │   └── A S01E04.mp4
> ```
> 
> 下图是我刚刚使用的一个example： ![image](https://user-images.githubusercontent.com/55415793/173334531-feb9166b-ff6a-453c-b01a-7146ae6f7b00.png) jellyfin的刮削器应该是_严格_按照尾部的命名格式来的。也就是说无论是季文件夹还是单集数都是按照这个命名格式单一查询。我所使用的是IMDB。在上面的例子中，我没有对名字做任何调整而是让AutoBangumi自动将文件下载到我已有的文件夹中（我手动修改了已有文件夹的bangumi_A_title以及Season 01以便能被识别），在我jellyfin的网页中，这两集无法被识别。
> 
> 但我手动将这两集的后缀改为S01E08/S01E09后，jellyfin的刮取器就能正常刮取这两集的元数据了。
> 
> 又比如以下图的约会大作战为例，即便我的第四季内的文件有我之前以英文命名的文件和AutoBangumi自动生成的中文名，只要后缀格式被我修改正确后，jellyfin刮取器依旧能正常工作。即使该文件在文件夹之外。 ![image](https://user-images.githubusercontent.com/55415793/173335980-957063c1-6998-438c-b897-de846269d5af.png)
> 
> 所以对于jellyfin的刮取器而言，文件名格式重要性>>文件结构重要性。
> 
> 希望有所帮助！

![image](https://user-images.githubusercontent.com/31799398/173339291-15d1a01c-0bec-45bc-afb0-9d2ff0c2eafc.png)
这是我实际测试成功的命名方案，emby/jellyfin都能成功识别，并不是严格按照尾部的命名格式来的

实际上只要最外头的番剧名准确，番剧视频文件名带有S*E*的字样，都能被emby/jellyfin内置的tmdb/tvdb插件识别并索引元数据

**Comment by wzl778633** [comment]
感谢，其实个人认为在AB现如今规则为**一个番剧原则上只允许一个字幕组订阅**的情况下，应该可以适当的对应订阅能允许手动添加命名规则即可。
对于jellyfin，从我曾经修改它的web client时的经验应该是他server底层的逻辑就是按sxxexx的正则匹配先通过一遍检索（大概）。在官方网站的doc是也对命名格式提出了识别上的要求。可能不太会有模糊识别。

“街角魔族2丁目 这样的番剧，AB 只能识别为第一季，添加之后也为 S01E**，不清楚是否会对 Jellyfin 的刮削产生影响。”

不会，只要能按照那个命名格式即可。

**Comment by wzl778633** [comment]
@mikusaa 抱歉是我说明上的失误，我的意思是：
只要你的文件名带有SXXEXX 那文件结构对于jellyfin来说就没有那么重要。
反之，如果你的文件名没有带有SXXEXX 那即使你是按照正确的文件结构放入番剧，大概率不能正常刮削。
这就是我所说的 文件名格式重要性>>文件结构重要性。
如果在你的图片案例中将S03E03 改为 E03，那**很有可能**不能正常刮削。
由于jellyfin从emby分出后几乎从未修改过（仅添加了对Series的支持）所以相对比较古老。

**Comment by EstrellaXD** [comment]
> @EstrellaXD 感谢，其实个人认为在AB现如今规则为**一个番剧原则上只允许一个字幕组订阅**的情况下，应该可以适当的对应订阅能允许手动添加命名规则即可。
> 
> “街角魔族2丁目 这样的番剧，AB 只能识别为第一季，添加之后也为 S01E**，不清楚是否会对 Jellyfin 的刮削产生影响。”
> 
> 规则上不会，但可能会错误识别为第一季第一集。
> 
> 比如针对 街角魔族2丁目 ，如果AB能识别出是它的torrent下载，我想我可以预先储存对应季数甚至自定义名称（带年份什么的），仅从源文件名中获取对应的集数。这样虽然我需要手动提供信息，但一个季度一次并不是什么问题。(单一字幕组的命名规则在单一季度下我觉得大概率不会变)
> 
> 对于jellyfin，从我曾经修改它的web client时的经验应该是他server底层的逻辑就是按sxxexx的正则匹配先通过一遍检索（大概）。在官方网站的doc是也对命名格式提出了识别上的要求。可能不太会有模糊识别。

你说的这个是可行的，只需要吧 AB 的 `config` 文件映射到你的目录中，可以对其中存储的番剧信息进行更改，其中有季度信息

**Comment by EstrellaXD** [comment]
我正在研究从 TMDB 上抓标准数据并且进行对比的可行性，可能会在未来版本更新

**Comment by wzl778633** [comment]
> 我正在研究从 TMDB 上抓标准数据并且进行对比的可行性，可能会在未来版本更新

感谢，我先试试修改config的方式行不行。
个人认为如果需要使用TMDB, 更多的是调用其API查询然后利用web ui什么的让用户自己选择正确的选项 (在我自己的项目里就是这样干的)。毕竟我感觉AB这部分的主要工作还是自动重命名后供其他刮取器正确抓取。当然，一己之言 :(

**Comment by EstrellaXD** [comment]
> > 我正在研究从 TMDB 上抓标准数据并且进行对比的可行性，可能会在未来版本更新
> 
> 感谢，我先试试修改config的方式行不行。 个人认为如果需要使用TMDB, 更多的是调用其API查询然后利用web ui什么的让用户自己选择正确的选项 (在我自己的项目里就是这样干的)。毕竟我感觉AB这部分的主要工作还是自动重命名后供其他刮取器正确抓取。当然，一己之言 :(

抓取 TMDB 的数据仅仅是让 AB 获得规范的 title 和 season 信息，不会再 AB 中放置 TMDB 的接口。

**Comment by wzl778633** [comment]
> > @EstrellaXD 感谢，其实个人认为在AB现如今规则为**一个番剧原则上只允许一个字幕组订阅**的情况下，应该可以适当的对应订阅能允许手动添加命名规则即可。
> > “街角魔族2丁目 这样的番剧，AB 只能识别为第一季，添加之后也为 S01E**，不清楚是否会对 Jellyfin 的刮削产生影响。”
> > 规则上不会，但可能会错误识别为第一季第一集。
> > 比如针对 街角魔族2丁目 ，如果AB能识别出是它的torrent下载，我想我可以预先储存对应季数甚至自定义名称（带年份什么的），仅从源文件名中获取对应的集数。这样虽然我需要手动提供信息，但一个季度一次并不是什么问题。(单一字幕组的命名规则在单一季度下我觉得大概率不会变)
> > 对于jellyfin，从我曾经修改它的web client时的经验应该是他server底层的逻辑就是按sxxexx的正则匹配先通过一遍检索（大概）。在官方网站的doc是也对命名格式提出了识别上的要求。可能不太会有模糊识别。
> 
> 你说的这个是可行的，只需要吧 AB 的 `config` 文件映射到你的目录中，可以对其中存储的番剧信息进行更改，其中有季度信息

hmmm.. 我尝试将config向外映射，但是是空的，是我设置的问题吗？
![image](https://user-images.githubusercontent.com/55415793/173348274-b16632d6-a9f5-4813-a198-d0f0734d2f53.png)

**Comment by EstrellaXD** [comment]
> > > @EstrellaXD 感谢，其实个人认为在AB现如今规则为**一个番剧原则上只允许一个字幕组订阅**的情况下，应该可以适当的对应订阅能允许手动添加命名规则即可。
> > > “街角魔族2丁目 这样的番剧，AB 只能识别为第一季，添加之后也为 S01E**，不清楚是否会对 Jellyfin 的刮削产生影响。”
> > > 规则上不会，但可能会错误识别为第一季第一集。
> > > 比如针对 街角魔族2丁目 ，如果AB能识别出是它的torrent下载，我想我可以预先储存对应季数甚至自定义名称（带年份什么的），仅从源文件名中获取对应的集数。这样虽然我需要手动提供信息，但一个季度一次并不是什么问题。(单一字幕组的命名规则在单一季度下我觉得大概率不会变)
> > > 对于jellyfin，从我曾经修改它的web client时的经验应该是他server底层的逻辑就是按sxxexx的正则匹配先通过一遍检索（大概）。在官方网站的doc是也对命名格式提出了识别上的要求。可能不太会有模糊识别。
> > 
> > 
> > 你说的这个是可行的，只需要吧 AB 的 `config` 文件映射到你的目录中，可以对其中存储的番剧信息进行更改，其中有季度信息
> 
> hmmm.. 我尝试将config向外映射，但是是空的，是我设置的问题吗？ ![image](https://user-images.githubusercontent.com/55415793/173348274-b16632d6-a9f5-4813-a198-d0f0734d2f53.png)

重建 AB

**Comment by Seeger0216** [comment]
![1655123884450](https://user-images.githubusercontent.com/65768435/173355322-61a8757a-0cea-44da-804a-e98f0551e8db.png)
![1655123913147](https://user-images.githubusercontent.com/65768435/173355385-3f089258-bebc-424e-9eb5-cb79887f1caa.png)
![1655123957722](https://user-images.githubusercontent.com/65768435/173355512-ccec5ebc-fa5c-4ca4-8748-699634e47b9c.png)

如图，当仅命名为E10时，Emby识别有误。但若命名为S01E01，则正常。S01E01符合Emby规范。

**Comment by wzl778633** [comment]
@EstrellaXD 我昨天试了试修改config下的bangumi.json，将自动生成的：
```
{
            "title": "Spy x Family",
            "season": "S01",
            "group": "桜都字幕组",
            "subtitle": "简繁内封",
            "source": null,
            "dpi": "1080p",
            "added": true,
            "download_past": false
        },
```
替换为：
```
{
            "title": "SPY x FAMILY (2022)",
            "season": "Season 01",
            "group": "桜都字幕组",
            "subtitle": "简繁内封",
            "source": null,
            "dpi": "1080p",
            "added": true,
            "download_past": false
        },
```
但AB似乎无视了这个object重新生成了一个，请问修改上需要注意些什么吗？

**Comment by EstrellaXD** [comment]
> @EstrellaXD 我昨天试了试修改config下的bangumi.json，将自动生成的：
> 
> ```
> {
>             "title": "Spy x Family",
>             "season": "S01",
>             "group": "桜都字幕组",
>             "subtitle": "简繁内封",
>             "source": null,
>             "dpi": "1080p",
>             "added": true,
>             "download_past": false
>         },
> ```
> 
> 替换为：
> 
> ```
> {
>             "title": "SPY x FAMILY (2022)",
>             "season": "Season 01",
>             "group": "桜都字幕组",
>             "subtitle": "简繁内封",
>             "source": null,
>             "dpi": "1080p",
>             "added": true,
>             "download_past": false
>         },
> ```
> 
> 但AB似乎无视了这个object重新生成了一个新的object，命名也没有改变，请问修改上需要注意些什么吗？

- title 这个属性不允许更改，如果更改会导致错误。
- 你可以更改 `season`，并且把 `added` 改为 false，然后重新运行 AB，等待完成之后在 QB 中把旧规则删除

**Comment by li-guohao** [comment]
自动化重命名这个目前问题确实很多而且非常棘手，我的jellyfin里的剧集太乱的，要么剧集重复，要么番剧重复。

建议最终的文件名称，只加前缀或者后缀E几，而不是直接把原文件名都整没了，没有原文件名，我想手动整理都整理不了

**Comment by EstrellaXD** [comment]
> 自动化重命名这个目前问题确实很多而且非常棘手，我的jellyfin里的剧集太乱的，要么剧集重复，要么番剧重复。
> 
> 建议最终的文件名称，只加前缀或者后缀E几，而不是直接把原文件名都整没了，没有原文件名，我想手动整理都整理不了

你打开 `method` 的 `normal` 模式就行了

**Comment by li-guohao** [comment]
> 感谢，重新尝试后可以了，但是要重启两次才能重命名成功 :( 关于 **等待完成之后在 QB 中把旧规则删除** 这个是在哪里可以看见。
> 
> 还有近期版本能有对自定义title与自定义季度名/后缀名的支持吗，这样我就可以手动将title改成TMDB的格式了。 根据上面其他用户的反应似乎emby和jellyfin都有这个 **SXXEXX** 的问题 :((( 太悲伤了。

记得好像emby和jellyfin同源，你可以把jellyfin当作emby的一个分支，他们两个文件识别的规则基本一致。

**Comment by li-guohao** [comment]
> > 自动化重命名这个目前问题确实很多而且非常棘手，我的jellyfin里的剧集太乱的，要么剧集重复，要么番剧重复。
> > 建议最终的文件名称，只加前缀或者后缀E几，而不是直接把原文件名都整没了，没有原文件名，我想手动整理都整理不了
> 
> 你打开 `method` 的 `normal` 模式就行了

好的，我有时间再试试

**Comment by EstrellaXD** [comment]
> 感谢，重新尝试后可以了，但是要重启两次才能重命名成功 :( 关于 **等待完成之后在 QB 中把旧规则删除** 这个是在哪里可以看见。
> 
> 还有近期版本能有对自定义title与自定义季度名/后缀名的支持吗，这样我就可以手动将title改成TMDB的格式了。 根据上面其他用户的反应似乎emby和jellyfin都有这个 **SXXEXX** 的问题 :((( 太悲伤了。

2.5.0 版本已经经过两次重构了，可能稍晚会上线，关于 Jellyfin 和 emby 识别的问题我还在想如何可以较好的解决，可能需要暂等一段时间

**Comment by EstrellaXD** [comment]
已经在 2.5.0 版本中提供了一系列解决方法

**Comment by wzl778633** [comment]
感谢您 我的超人
