### ISSUE TITLE
[错误报告]已设置代理但提示Please check DNS/Connection settings

### ISSUE THREAD

**Issue by STONE-Git** [EstrellaXD/Auto_Bangumi#368]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.9

### 问题类型

程序运行问题

### 问题描述

在Windows上的docker设置的ab，本地已运行Clash，浏览器可以正常打开mikan rss链接。之前几个版本也会提示，但是功能都正常就没管，现在qb能下载但ab一直连不上就没改名和推送了。查看clash日志也找不到docker访问mikan的记录，已尝试添加8.8.8.8为dns。想知道是不是哪里设置出了问题
![Snipaste_2023-07-01-18-17-55](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/19a31042-95d6-4207-abf1-1288dc5e2347)
![Snipaste_2023-07-01-18-18-20](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/c9f5f013-65c4-4073-b468-1f5ee7b16b5d)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/d139715b-0124-40f6-abe5-f267301ad6d4)
![Snipaste_2023-07-01-18-17-40](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/dc71aa33-10c0-46c8-b237-19e5977f7345)
![Snipaste_2023-07-01-21-19-39](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/bedd5919-96a4-4492-993c-99c15e45bb42)

### 发生问题时系统日志

```bash
[2023-07-01 21:32:02] INFO:     Config loaded
[2023-07-01 21:32:02] INFO:     Program running.
[2023-07-01 21:32:07] WARNING:  [Network] Cannot connect to https://mikanani.me/RSS/MyBangumi?token=X. Wait for 5 seconds.
[2023-07-01 21:32:17] WARNING:  [Network] Cannot connect to https://mikanani.me/RSS/MyBangumi?token=X. Wait for 5 seconds.
[2023-07-01 21:32:27] WARNING:  [Network] Cannot connect to https://mikanani.me/RSS/MyBangumi?token=X. Wait for 5 seconds.
[2023-07-01 21:32:27] ERROR     [Network] Failed connecting to https://mikanani.me/RSS/MyBangumi?token=X
[2023-07-01 21:32:27] WARNING:  [Network] Please check DNS/Connection settings
```

**Comment by zthxxx** [comment]
docker 本身不遵从系统代理设置的，所以浏览器能访问(走了系统代理) 但 docker 内不能访问(不走代理)，

解决办法有几种
- Clash 开 TUN 模式
- 折腾 AutoBangumi 的代理给 qbit 用
- 给 AutoBangumi 和 qbittorrent 的容器上写上 http(s)_proxy 的环境变量，
  - 这样不需要再 ab 上写 proxy 的配置和折腾 qbit 写反代地址


第三种方式写

```yaml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      http_proxy: http://host.docker.internal:7890
      https_proxy: http://host.docker.internal:7890
      all_proxy: socks5://host.docker.internal:7890
      no_proxy: home-lab,docker.internal,local,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
```

![IMG_5674](https://github.com/EstrellaXD/Auto_Bangumi/assets/15135943/c48c150b-2cce-4150-92f1-b6dd2e41d98b)

**Comment by STONE-Git** [comment]
> docker 本身不遵从系统代理设置的，所以浏览器能访问(走了系统代理) 但 docker 内不能访问(不走代理)，
> 
> 解决办法有几种
> 
> * Clash 开 TUN 模式
> * 折腾 AutoBangumi 的代理给 qbit 用
> * 给 AutoBangumi 和 qbittorrent 的容器上写上 http(s)_proxy 的环境变量，
>   
>   * 这样不需要再 ab 上写 proxy 的配置和折腾 qbit 写反代地址
> 
> 第三种方式写
> 
> ```yaml
>     extra_hosts:
>       - 'host.docker.internal:host-gateway'
>     environment:
>       http_proxy: http://host.docker.internal:7890
>       https_proxy: http://host.docker.internal:7890
>       all_proxy: socks5://host.docker.internal:7890
>       no_proxy: home-lab,docker.internal,local,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
> ```
> 
> ![IMG_5674](https://user-images.githubusercontent.com/15135943/250281711-c48c150b-2cce-4150-92f1-b6dd2e41d98b.jpeg)

谢谢您的回复，尝试了第一和第三两种方法
1.Clash 开 TUN 模式之后ab的日志就不报错了，想问一下这种模式下qb的下载上传会不会也变成走代理的？如果是的话有解决办法吗，怕因为这个原因被机场封号
3.第三种方法试了几次也没运行起来，如果直接复制上去会提示 line 25: mapping key "environment" already defined at line 11
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/6fd4ae2f-17c4-4cae-add5-007e8e3c3690)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/39043fc6-8632-41a8-9efe-cdf1886fc591)
手动合并到原有的environment里会提示line 13: did not find expected '-' indicator
![Snipaste_2023-07-01-23-15-58](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/2e0dc2e1-b5cf-4f22-b842-c83608da045b)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/6d8a67ce-7551-4418-9a48-d7e3945aa0a1)
按照提示加上‘-’后提示services.ab.environment.2 must be a string
![Snipaste_2023-07-01-23-15-31](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/5a09756f-721e-4f12-b287-795a7b26f01d)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/63118507/eb076d49-0aec-4029-bd8f-66d6d63d3208)
如果第一种方法不会影响qb下载的话就先用第一种不继续麻烦您了，再次感谢！

**Comment by zthxxx** [comment]
你截图中最后两张图是 yaml 配置文件中语法错误，

在 `docker-compose.yml` 文件中，`environment` 配置用来定义容器的环境变量，就是给容器内的程序提供一些运行需要的信息。有两种常见的写法，一种是列表（list）形式，一种是键值对（key-value）形式。

1. 列表形式（List）：

   列表形式就像我们写购物清单一样，每行一个物品。对于 `environment`，这个清单就是你需要的环境变量和它的值，用等号连接起来。比如：

    ```yaml
    environment:
      - VAR1=value1
      - VAR2=value2
    ```
   这里，我们定义了两个环境变量，一个叫做 "VAR1"，它的值是 "value1"；另一个叫做 "VAR2"，它的值是 "value2"。

2. 键值对形式（Key-Value）：

   键值对形式就像字典一样，每个键（key）对应一个值（value）。比如：

    ```yaml
    environment:
      VAR1: value1
      VAR2: value2
    ```
   同样，我们定义了两个环境变量，"VAR1" 的值是 "value1"，"VAR2" 的值是 "value2"。

不论你选择哪种形式，只能一次保留一种写法，不能混用，截图中问题属于混用的语法错误了。

—-

用 TUN 理论上不会导致 qbit 中使用 ip 方式的 tracker 下载走代理，有走域名 DNS 的 tracker 可能有问题。
