### ISSUE TITLE
[其他问题]Ubuntu本地安装运行出问题。

### ISSUE THREAD

**Issue by kuoluo1995** [EstrellaXD/Auto_Bangumi#378]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.9

### 问题类型

其他问题

### 问题描述

我想直接在ubuntu上安装autobangumi，但运行失败了。

存在的问题：
1. 目前主目录下似乎并没有了src的代码文件。
2. 我尝试直接运行dev.sh脚本发现报错。
a. 主目录下并没有src了。
b. 我怀疑src变成了backend/src/。但这个文件夹的module下面也没有__version__.py文件
4. 我尝试直接运行backend/src/main.py但运行后的界面是FastAPI。（默认主页跳转会在后面加上/docs）

我目前不知道如果直接在linux本地部署，应该怎么运行这个脚本。

**Comment by kuoluo1995** [comment]
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/18499615/c1308ed5-d76b-470e-ab62-db3f1cbecbce)
为何总是会进这里？实在无法理解。我运行的是backend/src/config里的内容。我下载了https://github.com/Rewrite0/Auto_Bangumi_WebUI/releases/download/v2.0.3/dist.zip。
并且也解压改名成templates。

**Comment by kuoluo1995** [comment]
不对，我看了html/index。发现里面的内容是这样的。
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/18499615/7320e012-f25a-4be2-aee1-97cdc9ba098f)
所以不管怎么样运行，我都只能看到api。

求助，到底应该怎么正确的直接在本地运行这个项目？

**Comment by EstrellaXD** [comment]
https://github.com/EstrellaXD/Auto_Bangumi/wiki/local-run#进入源代码目录并且创建版本信息

**Comment by kuoluo1995** [comment]
> [https://github.com/EstrellaXD/Auto_Bangumi/wiki/local-run#进入源代码目录并且创建版本信息](https://github.com/EstrellaXD/Auto_Bangumi/wiki/local-run#%E8%BF%9B%E5%85%A5%E6%BA%90%E4%BB%A3%E7%A0%81%E7%9B%AE%E5%BD%95%E5%B9%B6%E4%B8%94%E5%88%9B%E5%BB%BA%E7%89%88%E6%9C%AC%E4%BF%A1%E6%81%AF)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/18499615/47aa379a-24a6-40ef-9b37-9b176ee2c327)
你好，你们的代码命名修改了。在我并没有在module下面找到__version__.py的文件。

**Comment by EstrellaXD** [comment]
@kuoluo1995 你进不去webui就是因为没生成version版本信息。

**Comment by kuoluo1995** [comment]
> @kuoluo1995 你进不去webui就是因为没生成version版本信息。
好的，但能询问一下怎么解决这个问题吗？我没有找到__version__.py这个文件。我试过加在__init__.py上。但没有效果。

**Comment by kuoluo1995** [comment]
> @kuoluo1995 你进不去webui就是因为没生成version版本信息。
你好，再度打扰了。
但目前官方文档中我似乎也没找到__version__.py这个文件？
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/18499615/94f11598-300e-4ef0-897b-55901d0ed829)

**Comment by Rewrite0** [comment]
@kuoluo1995

**Comment by Rewrite0** [comment]
@kuoluo1995 手动创建 __version__.py 文件.

**Comment by kuoluo1995** [comment]
> @kuoluo1995 手动创建 `__version__.py` 文件.
非常感谢!解决了!
