### ISSUE TITLE
[重命名错误]设置Offset没有效果。

### ISSUE THREAD

**Issue by hot36952** [EstrellaXD/Auto_Bangumi#380]
### 当前程序版本

v3.0.9

### 重命名设置

advance

### 种子名称

[Lilith-Raws] 咒術迴戰 / Jujutsu Kaisen S02 - 01 [Baha][WebDL 1080p AVC AAC][CHT]

### 文件路径

/咒术回战 (2020)/Season 1

### 错误命名

咒术回战 (2020) S01E01.mp4

### 发生问题时系统日志

```shell
咒术回战S2在tmdb归类到S1里面，S1共24集，S2从25集开始，即S02E01应该变为S01E25，设置Offset:25，没有效果。
```

**Comment by hot36952** [comment]
![QQ截图20230709153815](https://github.com/EstrellaXD/Auto_Bangumi/assets/21011227/45a01069-2f5b-47f2-8cc1-6c1e1714ab68)

**Comment by EstrellaXD** [comment]
目前这个功能还没做，请等待后续更新

**Comment by hot36952** [comment]
希望尽快完成该功能，很需要。
