### ISSUE TITLE
[错误报告]Interval Time of Rss 不管设置多少最后都会变成 30min

### ISSUE THREAD

**Issue by 9bingyin** [EstrellaXD/Auto_Bangumi#387]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.10

### 问题类型

其他问题

### 问题描述

`Interval Time of Rss` 不管设置多少，最后重启 AB 后 QB 里 RSS 的订阅更新间隔都会变成 30 分钟
![AB](https://github.com/EstrellaXD/Auto_Bangumi/assets/37502927/08347b20-2136-430d-9a17-de794cc6c349)

**Comment by EstrellaXD** [comment]
这个参数跟 QB 中 RSS 的轮询时间不相关。
