### ISSUE TITLE
a typo in webUI

### ISSUE THREAD

**Issue by THU-Pieris** [EstrellaXD/Auto_Bangumi#390]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://github.com/EstrellaXD/Auto_Bangumi/wiki/排错流程)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://github.com/EstrellaXD/Auto_Bangumi/wiki/常见问题)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.10

### 问题类型

WebUI

### 问题描述

webUI里有一个typo，见截图
<img width="377" alt="image" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/49369792/197bb2af-b6d8-449a-8a96-1e87e97988fd">
`Officical Ttile` -> `Official Title`
位置在webUI仓库的这里
https://github.com/Rewrite0/Auto_Bangumi_WebUI/blob/b6bf41ed760c2839f59af55f2aeab2fe901a58c2/src/components/ab-rule.vue#L12C10-L12C10
但是它归档了，提不了issue或pr 

### 发生问题时系统日志

```bash
N/A
```

**Comment by Kasper4649** [comment]
可以在 [3.1-dev](https://github.com/EstrellaXD/Auto_Bangumi/blob/152869fbe4951675e1d87bce35a965267bb014ea/webui/src/components/ab-rule.vue#L13) 分支下提 PR
