### ISSUE TITLE
[解析器错误]

### ISSUE THREAD

**Issue by ss22219** [EstrellaXD/Auto_Bangumi#392]
### 当前程序版本

3.0.10

### 解析器语言设置

默认：zh

### TMDB 解析

否

### 字幕组提供的名称

Lilith-Raws

### 错误识别名称

[Lilith-Raws] Inu ni Nattara Suki na Hito ni Hirowareta. - OVA02 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4

**Comment by ss22219** [comment]
fix: https://github.com/ss22219/Auto_Bangumi/commit/5af46f6aa19a18c25b6f6a4cd340028908cea19c

**Comment by EstrellaXD** [comment]
OVA的话目前不会这么修复，因为按照刮削会归类到S0，这个执行逻辑还需要再斟酌
