### ISSUE TITLE
[Feature Request] qBittorrent 下载完成后创建硬连接，将文件连接到其他目录下管理

### ISSUE THREAD

**Issue by daiyeqi** [EstrellaXD/Auto_Bangumi#401]
### 背景 or 问题

当 AB 调用 qBittorrent 下载时，Plex 或 Jellyfin 就会扫描到正在下载的文件，因为未进行合理的重命名，可能会导致刮削的信息不正确，希望能在下载完成后创建一个文件硬链接的副本，副本存放在 Plex 媒体所在目录。

### 目标 & 方案简述

AB 调用 qBittorrent 下载时，可以不关注 qBittorrent 的下载目录和文件名，等下载完成后，在所配置的预设的目录下创建文件夹，并将文件通过硬链接的方式创建副本。可以参考 Sonarr 的 [Use Hardlinks instead of Copy](https://wiki.servarr.com/docker-guide#Consistent_and_well_planned_paths) 功能。

### 方案设计 & 实现步骤

前提需要 Plex，AB，qBittorrent 在一台宿主机上。

Docker 映射目录结构
```
Plex
/mnt/user/public/media:/data/media

qBittorent
/mnt/user/public/downloads:/data/downloads

AB
/mnt/user/public:/data
```

假设订阅了 “无职转生第二季”

当 AB 调用 qBittorrent 下载时，由 qBittorrent 创建文件 “[ANi] 無職轉生～到了異世界就拿出真本事 第二季 - 0X [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4”。

下载完成后，AB 预设的目录在 `/data/media/bangumi` 文件夹下创建 ` 無職轉生～到了異世界就拿出真本事` / `Season 2` 目录

接着创建 `[ANi] 無職轉生～到了異世界就拿出真本事 第二季 - 0X [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4` 的硬链接，命名为 `无职转生～到了异世界就拿出真本事 S02E0X.mp4`。

**Comment by EstrellaXD** [comment]
1. 这个 issue 属于 Feature Request，下次提交请注意。
2. 这个问题可以通过 qBittorrent 下载暂存 temp 文件夹解决。
3. 硬连接需要改动非常多底层代码，如果是 RFC 请提出具体改动方案。
4. 很多用户 AB QB 媒体服务器并不在同一台机器上。
