### ISSUE TITLE
[错误报告]"死神少爺與黑女僕 第二季"识别为 S01

### ISSUE THREAD

**Issue by zhiwen95** [EstrellaXD/Auto_Bangumi#404]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.11

### 问题类型

程序运行问题

### 问题描述

死神少爺與黑女僕 第二季未识别
实际：死神少爺與黑女僕 第二季 S01E03.mp4
应为：死神少爺與黑女僕 S02E03.mp4

### 发生问题时系统日志

```bash
[2023-07-24 18:51:21] INFO:     [ANi] 死神少爺與黑女僕 第二季（僅限港澳台地區） - 03 [1080P][Bilibili][WEB-DL][AAC AVC][CHT CHS].mp4 >> 死神少爺與黑女僕 第二季 S01E03.mp4
```

**Comment by zhiwen95** [comment]
print(raw_parser("[ANi] 死神少爺與黑女僕 第二季（僅限港澳台地區） - 03 [1080P][Bilibili][WEB-DL][AAC AVC][CHT CHS]"))

Episode(title_en=None, title_zh='死神少爺與黑女僕 （僅限港澳台地區）', title_jp=None, season=2, season_raw='第二季', episode=3, sub='CHS', group='ANi', resolution='1080P', source='Bilibili')

**Comment by zhiwen95** [comment]
> 啊这不是第二季吗

死神少爷与黑女仆 (2021)/Season 1/死神少爺與黑女僕 第二季 S01E03.mp4

**Comment by EstrellaXD** [comment]
请问是否开启 TMDB 解析。

**Comment by zhiwen95** [comment]
> 请问是否开启 TMDB 解析。

开启

**Comment by EstrellaXD** [comment]
这个问题是 TMDB 上只有一季，AB 的逻辑是 TMDB 优先，如果你需要改成第二季手动在 WebUI 中修正一下即可。
