### ISSUE TITLE
[错误报告]webui显示问题,解析设置中排除文本tag过长导致显示不全,无法点x取消

### ISSUE THREAD

**Issue by Amarsimos** [EstrellaXD/Auto_Bangumi#407]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.11

### 问题类型

WebUI

### 问题描述

解析设置中排除文本tag过长导致显示不全,无法点x取消
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/48476733/5ef652d4-bec6-4949-ae13-9aaab4794368)

**Comment by EstrellaXD** [comment]
你可以一条一条加，而且`，`并不会正确运行。

**Comment by Amarsimos** [comment]
感谢回复，现在就是，恩，我想取消掉但是取消不了

**Comment by Rewrite0** [comment]
啊这, 等我之后修一下, 你可以先按下面的步骤给移除掉:
1. 按 `f12` 打开控制台, 找到左上角的箭头
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/49576640/9a23b3d5-a211-47fd-b52b-3f20324f89e8)
2. 然后点击 tag 部分
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/49576640/ce0591a6-4b7b-48ed-9661-afb522260a3b)
3. 现在控制台应该已经调到了左边框起来的元素, 然后再右边框起来的地方加入 `overflow: auto`
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/49576640/f6f18def-d0ac-43a1-a538-98a91f352e80)
4. 现在 tag 部分就有拖动条了
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/49576640/9f453902-8a06-4793-8116-792fbebd0f01)

**Comment by Amarsimos** [comment]
好的，已解决，感谢回复
