### ISSUE TITLE
海报无法显示是什么原因

### ISSUE THREAD

**Issue by tao08ms** [EstrellaXD/Auto_Bangumi#409]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

301

### 问题类型

WebUI

### 问题描述

蜜柑能正常访问，但是这边autobangumi就是不能显示海报

**Comment by EstrellaXD** [comment]
访问ab的主机挂梯子了没

**Comment by nexmoe** [comment]
> 访问ab的主机挂梯子了没

建议图片地址跟随 Parser Setting 的 Custom Url

**Comment by InDimension** [comment]
> 访问ab的主机挂梯子了没

附议图片地址跟随custom Url
捣鼓cloudflare workers反代的时候发现图片地址还是原域名所以无法加载图片（需要梯子）
另外提一下wiki里面关于cloudflare workers反代的配置把后续添加trigger自定义域名的操作也一并附上可能会好一些。（单纯复制代码部署workers并不能直接使用域名反代，我找了openai的例子参考才解决。）
