### ISSUE TITLE
[问题汇总]字幕组命名失败/改名器改名失败汇总报告

### ISSUE THREAD

**Issue by EstrellaXD** [EstrellaXD/Auto_Bangumi#41]
## 请按照如下格式反馈：
报错地点：
- 解析器：`Not match` 类型错误
- 改名器：`rename failed`类型错误

原文件名称/字幕组命名名称：

## 注：
目前 AB 不支持识别的类型
- 所有非单集如：[1-2]、[1-12] 这样的合集
- 剧场版 OVA SP 

本 issue 只针对支持的识别类型报错

**Comment by ztx0079** [comment]
改名器错误 Rename failed.

单集

2022-06-21 18:17:55 WARNING: [MingY] Aharen-san wa Hakarenai [11][1080p][CHS].mp4 rename failed

**Comment by EstrellaXD** [comment]
> 报错地点: 改名器错误 Rename failed.
> 原文件名称:[MingY] Aharen-san wa Hakarenai [11][1080p][CHS].mp4
> 字幕组命名名称:[MingY] 测不准的阿波连同学 / Aharen-san wa Hakarenai [11][1080p][简体内嵌] [284.59 MB]

文件路径是否正确 正确路径应为`XXXX/Season 1/XXXX 11.mp4

**Comment by mikusaa** [comment]
报错地点：
改名器：rename failed类型错误
原文件名称/字幕组命名名称：[MingY] Spy x Family [11][1080p][CHS&JPN].mp4
重命名无误，但后缀被删除了。
![image](https://user-images.githubusercontent.com/31799398/174939588-4cbf2c27-d10d-4ba3-913e-27f98712c160.png)

**Comment by EstrellaXD** [comment]
> 报错地点：
> 改名器：rename failed类型错误
> 原文件名称/字幕组命名名称：[MingY] Spy x Family [11][1080p][CHS&JPN].mp4
> 重命名无误，但后缀被删除了。
> ![image](https://user-images.githubusercontent.com/31799398/174939588-4cbf2c27-d10d-4ba3-913e-27f98712c160.png)

我这边测试没有出现相同错误，暂时无法定位到错误问题

**Comment by Moyuuko** [comment]
报错地点: 改名器错误 Rename failed.
原文件名称:[黑岩射手吧字幕组] Black Rock Shooter - Dawn Fall [12 END][1080p][简繁内挂].mkv

**Comment by EstrellaXD** [comment]
> 



> 报错地点: 改名器错误 Rename failed.
> 原文件名称:[黑岩射手吧字幕组] Black Rock Shooter - Dawn Fall [12 END][1080p][简繁内挂].mkv

已经在 46af5e586639361b25718749a1ac24d434254b64 中修复

**Comment by dracula-s** [comment]
报错地点: 改名器错误 Rename failed.
原文件名称: [Nekomoe kissaten][Summer Time Rendering][11][1080p][JPTC].mp4
字幕组命名名称:【喵萌奶茶屋】★04月新番★[夏日重现/Summer Time Rendering][11][1080p][简日双语][招募翻译] [539.35 MB]
![image](https://user-images.githubusercontent.com/99948063/176102652-bf80335a-f590-4629-9c80-cfa412f2b13b.png)

**Comment by EstrellaXD** [comment]
> 报错地点: 改名器错误 Rename failed.
> 原文件名称: [Nekomoe kissaten][Summer Time Rendering][11][1080p][JPTC].mp4
> 字幕组命名名称:【喵萌奶茶屋】★04月新番★[夏日重现/Summer Time Rendering][11][1080p][简日双语][招募翻译] [539.35 MB]
> ![image](https://user-images.githubusercontent.com/99948063/176102652-bf80335a-f590-4629-9c80-cfa412f2b13b.png)
> 好像是最新版出现的问题，之前都正常，删了重下也不行。

已经修复

**Comment by Moyuuko** [comment]
![image](https://user-images.githubusercontent.com/59927366/177252745-a69a6fdc-f9d1-452f-8ab6-66b27c3ac7ca.png)
这种带文件夹是否可以重命名

**Comment by EstrellaXD** [comment]
> ![image](https://user-images.githubusercontent.com/59927366/177252745-a69a6fdc-f9d1-452f-8ab6-66b27c3ac7ca.png)
> 这种带文件夹是否可以重命名

下个大版本会支持

**Comment by EstrellaXD** [comment]
> 报错地点： 解析器：Not match
> 推测，添加ani组的overload之后开始出现错误，好像导致之前其他的ani组作品也识别成了ACC AVC。
> 完整日志：https://act.jiawei.xin:10086/tmp/tmp/estrellaxd-auto_bangumi1.html

这是最早的日志了么，从日志上看似乎没有发现引发报错的组名，现在临时的解决方法是进入容器的 `/config` 目录把 `AAC AVC` 这条规则删除，然后再检查后续日志才能定位原因

**Comment by xinjiawei** [comment]
> > 报错地点： 解析器：Not match
> > 推测，添加ani组的overload之后开始出现错误，好像导致之前其他的ani组作品也识别成了ACC AVC。
> > 完整日志：https://act.jiawei.xin:10086/tmp/tmp/estrellaxd-auto_bangumi1.html
> 
> 这是最早的日志了么，从日志上看似乎没有发现引发报错的组名，现在临时的解决方法是进入容器的 `/config` 目录把 `AAC AVC` 这条规则删除，然后再检查后续日志才能定位原因

新的日志: https://act.jiawei.xin:10086/tmp/tmp/estrellaxd-auto_bangumi1.csv 从13:03:10开始, 删掉之后重启的日志. 看样子好像不是ani的overload导致的.
附一张截图,删掉之后ACC AVC又加到后边了 https://act.jiawei.xin:10086/tmp/tmp/0415485.png
删之前ACC AVC 在第二个条目, 附上原配置文件: https://act.jiawei.xin:10086/tmp/tmp/bangumi.json

**Comment by EstrellaXD** [comment]
> > > 报错地点： 解析器：Not match
> > > 推测，添加ani组的overload之后开始出现错误，好像导致之前其他的ani组作品也识别成了ACC AVC。
> > > 完整日志：https://act.jiawei.xin:10086/tmp/tmp/estrellaxd-auto_bangumi1.html
> > 
> > 
> > 这是最早的日志了么，从日志上看似乎没有发现引发报错的组名，现在临时的解决方法是进入容器的 `/config` 目录把 `AAC AVC` 这条规则删除，然后再检查后续日志才能定位原因
> 
> 新的日志: https://act.jiawei.xin:10086/tmp/tmp/estrellaxd-auto_bangumi1.csv 从13:03:10开始, 删掉之后重启的日志. 看样子好像不是ani的overload导致的. 附一张截图,删掉之后ACC AVC又加到后边了 https://act.jiawei.xin:10086/tmp/tmp/0415485.png 删之前ACC AVC 在第二个条目, 附上原配置文件: https://act.jiawei.xin:10086/tmp/tmp/bangumi.json 文件夹结构: https://act.jiawei.xin:10086/tmp/tmp/folder.png 源文件名: [ANi] Overlord S4 - OVERLORD 第四季 - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]

更新 2.5.6 请升级或者重新部署一下，看看是否还有这个 bug 存在，如果仍然存在，请尝试访问 `host:7892/api/v1/resetRule` 来重置

**Comment by foxlesbiao** [comment]
报错地点：

改名器：rename failed类型错误
原文件名称: [Warau Arsnotoria Sun!][01][BIG5][1080P].mp4
字幕组命名名称：NC-Raws] 绽放的阿尔斯诺特利亚 / Warau Arsnotoria Sun! - 01 (B-Global 1920x1080 HEVC AAC MKV)
![image](https://user-images.githubusercontent.com/41581909/177872768-ddd4c413-edf1-4d0b-859a-674825d02b81.png)
![image](https://user-images.githubusercontent.com/41581909/177872820-65088a9f-3f7e-4f55-8520-bfbbc57a376e.png)
他会重命名为 BIG5 ，而不是绽放的阿尔斯诺特利亚

**Comment by EstrellaXD** [comment]
> 报错地点：
> 
> 改名器：rename failed类型错误 原文件名称: [Warau Arsnotoria Sun!][01][BIG5][1080P].mp4 字幕组命名名称：NC-Raws] 绽放的阿尔斯诺特利亚 / Warau Arsnotoria Sun! - 01 (B-Global 1920x1080 HEVC AAC MKV) ![image](https://user-images.githubusercontent.com/41581909/177872768-ddd4c413-edf1-4d0b-859a-674825d02b81.png) ![image](https://user-images.githubusercontent.com/41581909/177872820-65088a9f-3f7e-4f55-8520-bfbbc57a376e.png) 他会重命名为 BIG5 ，而不是绽放的阿尔斯诺特利亚

已经修复，会在下个版本推送

**Comment by foxlesbiao** [comment]
> > 报错地点：
> > 改名器：rename failed类型错误 原文件名称: [Warau Arsnotoria Sun!][01][BIG5][1080P].mp4 字幕组命名名称：NC-Raws] 绽放的阿尔斯诺特利亚 / Warau Arsnotoria Sun! - 01 (B-Global 1920x1080 HEVC AAC MKV) ![image](https://user-images.githubusercontent.com/41581909/177872768-ddd4c413-edf1-4d0b-859a-674825d02b81.png) ![image](https://user-images.githubusercontent.com/41581909/177872820-65088a9f-3f7e-4f55-8520-bfbbc57a376e.png) 他会重命名为 BIG5 ，而不是绽放的阿尔斯诺特利亚
> 
> 解析器错误是否更新到2.5.6？ 重命名已经修复，会在下个版本推送

srroy,我的错误

**Comment by foxlesbiao** [comment]
抱歉，我来报告一个比较特殊的情况
![image](https://user-images.githubusercontent.com/41581909/178119667-6656f2ea-409e-4e4b-9d12-4f85c96983da.png)
这个剧集，字幕组推出了两个版本，但是解析器认为是两个文件

**Comment by EstrellaXD** [comment]
> 抱歉，我来报告一个比较特殊的情况
> ![image](https://user-images.githubusercontent.com/41581909/178119667-6656f2ea-409e-4e4b-9d12-4f85c96983da.png)
> 这个剧集，字幕组推出了两个版本，但是解析器认为是两个文件

是生成了两个规则吗？有具体生成规则的 LOG 或者使用 API 访问一下 `host:7892/api/v1/data` 提供一下具体数据

**Comment by foxlesbiao** [comment]
> > 抱歉，我来报告一个比较特殊的情况
> > ![image](https://user-images.githubusercontent.com/41581909/178119667-6656f2ea-409e-4e4b-9d12-4f85c96983da.png)
> > 这个剧集，字幕组推出了两个版本，但是解析器认为是两个文件
> 
> 是生成了两个规则吗？有具体生成规则的 LOG 或者使用 API 访问一下 `host:7892/api/v1/data` 提供一下具体数据

是的，没有log，不知道为什么我无法访问 api

**Comment by EstrellaXD** [comment]
> > > 抱歉，我来报告一个比较特殊的情况
> > > ![image](https://user-images.githubusercontent.com/41581909/178119667-6656f2ea-409e-4e4b-9d12-4f85c96983da.png)
> > > 这个剧集，字幕组推出了两个版本，但是解析器认为是两个文件
> > 
> > 
> > 是生成了两个规则吗？有具体生成规则的 LOG 或者使用 API 访问一下 `host:7892/api/v1/data` 提供一下具体数据
> 
> 是的，没有log，不知道为什么我无法访问 api ，api拒绝我的连接

需要在 Docker 中映射出端口号

**Comment by foxlesbiao** [comment]
> > > > 抱歉，我来报告一个比较特殊的情况
> > > > ![image](https://user-images.githubusercontent.com/41581909/178119667-6656f2ea-409e-4e4b-9d12-4f85c96983da.png)
> > > > 这个剧集，字幕组推出了两个版本，但是解析器认为是两个文件
> > > 
> > > 
> > > 是生成了两个规则吗？有具体生成规则的 LOG 或者使用 API 访问一下 `host:7892/api/v1/data` 提供一下具体数据
> > 
> > 
> > 是的，没有 log，不知道为什么我无法访问 api ，api 拒绝我的连接
> 
> 需要在 Docker 中映射出端口号

查看 api data 没有这个数据，被清除了

**Comment by EstrellaXD** [comment]
> > > > > 抱歉，我来报告一个比较特殊的情况
> > > > > ![image](https://user-images.githubusercontent.com/41581909/178119667-6656f2ea-409e-4e4b-9d12-4f85c96983da.png)
> > > > > 这个剧集，字幕组推出了两个版本，但是解析器认为是两个文件
> > > > 
> > > > 
> > > > 是生成了两个规则吗？有具体生成规则的 LOG 或者使用 API 访问一下 `host:7892/api/v1/data` 提供一下具体数据
> > > 
> > > 
> > > 是的，没有 log，不知道为什么我无法访问 api ，api 拒绝我的连接
> > 
> > 
> > 需要在 Docker 中映射出端口号
> 
> 查看 api data 没有这个数据，被清除了

请去 #54 提供 LOG，或者 DATA

**Comment by EstrellaXD** [comment]
![IMAGE 2022-07-14 11:18:39](https://user-images.githubusercontent.com/33726646/178890761-47d358d8-8822-4c6a-99c9-c2bc362e28b1.jpg)
解析器错误

**Comment by Moyuuko** [comment]
![image](https://user-images.githubusercontent.com/59927366/178911238-5586721a-77c9-4606-aa4a-47d580699c3c.png)
源文件名：[Lilith-Raws] Made in Abyss - Retsujitsu no Ougonkyou - 02 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4，[HYSUB]Jashin-chan Dropkick X[02][BIG5_MP4][1920X1080].mp4
重命名后均识别为第一季

**Comment by EstrellaXD** [comment]
> ![image](https://user-images.githubusercontent.com/59927366/178911238-5586721a-77c9-4606-aa4a-47d580699c3c.png)
> 源文件名：[Lilith-Raws] Made in Abyss - Retsujitsu no Ougonkyou - 02 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4，[HYSUB]Jashin-chan Dropkick X[02][BIG5_MP4][1920X1080].mp4
> 重命名后均识别为第一季

手动在 QB 中改一下 Season 文件夹和下载规则即可

**Comment by lilifan105** [comment]
报错地点：

    改名器：rename failed类型错误

原文件名称:
[Nekomoe kissaten][Kanojo, Okarishimasu][15][1080p][JPSC]

字幕组命名名称：
【喵萌奶茶屋】★07月新番★[彼女、お借りします/租借女友/理想女友/出租女友/女朋友，借我一下/Kanojo, Okarishimasu][15][1080p][简日双语][招募翻译校对] [497.07 MB]

文件路径：
/Animation/Bangumi/租借女友 (2020)/Season 2/[Nekomoe kissaten][Kanojo, Okarishimasu][15][1080p][JPSC]

<img width="1614" alt="截屏2022-07-19 16 59 28" src="https://user-images.githubusercontent.com/83329310/179699108-9e537a3f-1d8c-41a9-ad2f-8961a7f8bef2.png">

**Comment by lilifan105** [comment]
> 

我是7/18直接拉取的latest，版本号不知道在哪里查看，所以不知道是不是2.5.14，不过文件确实是在season下产生一个同名文件夹，然后里面保存了MP4文件，我先升级下容器试试

**Comment by EstrellaXD** [comment]
> 我是7/18直接拉取的latest，版本号不知道在哪里查看，所以不知道是不是2.5.14，不过文件确实是在season下产生一个同名文件夹，然后里面保存了MP4文件，我先升级下容器试试

如果是上层有文件夹的话，目前解决不了，等下一次大版本更新吧～

**Comment by mikusaa** [comment]
- 解析器：Not match 类型错误
- 幻樱的传颂之物被识别成了2006版
- 附蜜柑链接：https://mikanani.me/Home/Bangumi/2750#21
![image](https://user-images.githubusercontent.com/31799398/180027463-59384a31-6681-4c3f-a0bb-8ed181edb66c.png)

**Comment by EstrellaXD** [comment]
> * 解析器：Not match 类型错误
> * 幻樱的传颂之物被识别成了2006版
> * 附蜜柑链接：https://mikanani.me/Home/Bangumi/2750#21
>   ![image](https://user-images.githubusercontent.com/31799398/180027463-59384a31-6681-4c3f-a0bb-8ed181edb66c.png)

手动调整一下吧，目前没有太好的解决方法

**Comment by bzxyme** [comment]
报错地点：解析器：Not match 类型错误
原文件名称：[Billion Meta Lab] Lycoris Recoil - 04_x264_1080p_CHS.mkv
字幕组命名名称：[Billion Meta Lab] Lycoris Recoil - 04_x264_1080p_CHS_简体内封 [276.3MB]
蜜柑链接：https://mikanani.me/Home/Bangumi/2754#598
日志：
[2022-07-24 16:07:25,185] INFO:     Start collecting RSS info.
[2022-07-24 16:07:27,461] ERROR     Parser cannot analyse [Billion Meta Lab] Lycoris Recoil - 04_x264_1080p_CHS_简体内封 'NoneType' object has no attribute 'groups'
[2022-07-24 16:07:27,461] ERROR     Parser cannot analyse [Billion Meta Lab] Lycoris Recoil - 03_x264_1080p_CHS_v2 'NoneType' object has no attribute 'groups'
[2022-07-24 16:07:27,461] ERROR     Parser cannot analyse [Billion Meta Lab] Lycoris Recoil - 02_x264_1080p_CHS_v2 'NoneType' object has no attribute 'groups'
[2022-07-24 16:07:27,461] ERROR     Parser cannot analyse [Billion Meta Lab] Lycoris Recoil - 01_x264_1080p_CHS_v2 'NoneType' object has no attribute 'groups'
[2022-07-24 16:07:27,461] ERROR     Parser cannot analyse [Billion Meta Lab] Lycoris Recoil - 02_1080p_CHS.mkv 'NoneType' object has no attribute 'groups'
[2022-07-24 16:07:27,461] ERROR     Parser cannot analyse [Billion Meta Lab] Lycoris Recoil - 03_x264_1080p 'NoneType' object has no attribute 'groups'
[2022-07-24 16:07:27,461] INFO:     Finished
[2022-07-24 16:07:27,462] INFO:     Running....

**Comment by ubitsp** [comment]
改名器：rename failed类型错误
原文件名称:[Tensei Kenja no Isekai Life][02]
字幕组命名名称:[c.c动漫][7月新番][转生贤者的异世界生活][04][简繁内挂][AVC_AAC][1080P][MKV] 
日志报错:
[2022-07-25 13:33:32,907] WARNING:  [Tensei Kenja no Isekai Life][02][ASSx2][1080P].mkv rename failed
[2022-07-25 13:33:32,908] DEBUG:    不允许使用绝对路径：「/ S01E02.mkv」。
[2022-07-25 13:33:32,908] DEBUG:    Name: \, File type: .mp4, Season 1
环境是在windows server 2022 中使用WSL2运行的docker

**Comment by EstrellaXD** [comment]
> 报错地点：改名器
> 原文件名称:[Tensei Kenja no Isekai Life][02]
> 字幕组命名名称:[c.c动漫][7月新番][转生贤者的异世界生活][02][简繁内挂][AVC_AAC][1080P][MKV]
> 日志报错:
> [2022-07-25 13:33:32,907] WARNING: [Tensei Kenja no Isekai Life][02][ASSx2][1080P].mkv rename failed
> [2022-07-25 13:33:32,908] DEBUG: 不允许使用绝对路径：「/ S01E02.mkv」。
> [2022-07-25 13:33:32,908] DEBUG: Name: , File type: .mp4, Season 1
> 环境是在windows server 2022 中使用WSL2运行的docker

在 Linux 下重命名 win 会统一在下个版本修复，可以线尝试关闭 Windows Defender 看看是否可以重命名。选用 pn 格式也可以让重命名生效。

**Comment by nagori-yuki** [comment]
报错地点：解析器

原文件名称：
[NC-Raws] Kakkou no Iinazuke (A Couple of Cuckoos) - 13 (CR 1920x1080 AVC AAC MKV) [0976E9A9].mkv
[NC-Raws] 杜鹃的婚约 - 13 (B-Global 3840x2160 HEVC AAC MKV) [00E61A7C].mkv
[NC-Raws] 杜鹃的婚约 - SP12 (B-Global 3840x2160 HEVC AAC MKV) [5BCD718C]
[Nekomoe kissaten&LoliHouse] Kakkou no Iinazuke - 12 [WebRip 1080p HEVC-10bit AAC ASSx2].mkv

字幕组命名名称：
[NC-Raws] 杜鹃的婚约 / Kakkou no Iinazuke (A Couple of Cuckoos) - 13 (CR 1920x1080 AVC AAC MKV) [1.3 GB]
[NC-Raws] 杜鹃的婚约 / Kakkou no Iinazuke (A Couple of Cuckoos) - 13 (B-Global 3840x2160 HEVC AAC MKV) [339.97 MB]
[NC-Raws] 杜鹃的婚约 / Kakkou no Iinazuke (A Couple of Cuckoos) - SP12 (B-Global 3840x2160 HEVC AAC MKV) [70.7MB]
[喵萌奶茶屋&LoliHouse] 杜鹃的婚约 / Kakkou no Iinazuke - 12 [WebRip 1080p HEVC-10bit AAC][简繁内封字幕] [560.47 MB]

版本：2.5.18

问题：此片的下载规则在反复添加入qb。
![3](https://user-images.githubusercontent.com/109912052/180769858-430da7ba-2558-449e-a325-772f342b9cdb.PNG)
![4](https://user-images.githubusercontent.com/109912052/180770468-96769f5c-27ac-414a-bec5-d1efb2c7ba56.PNG)
![5](https://user-images.githubusercontent.com/109912052/180770472-28196ed9-33d6-445f-a140-362de5b33784.PNG)

**Comment by zoooo0** [comment]
报错地点：
改名器：rename failed类型错误
原文件名称/字幕组命名名称：
DEBUG: name 'name' is not defined
[2022-07-29 23:11:11,342] DEBUG: Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1
[2022-07-29 23:11:11,342] WARNING: [Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC][v2].mp4 rename failed

**Comment by Arcate** [comment]
重命名似乎会报这么个错，然后完全无法重命名
Traceback (most recent call last):
  File "/src/app.py", line 111, in <module>
    run()
  File "/src/app.py", line 107, in run
    main_process(bangumi_data, download_client)
  File "/src/app.py", line 79, in main_process
    rename.run()
  File "/src/core/renamer.py", line 60, in run
    path_name, season, folder_name, suffix, _ = self.split_path(info.content_path)
  File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/_attrdict.py", line 149, in __getattr__
    raise AttributeError(
AttributeError: 'TorrentDictionary' instance has no attribute 'content_path'

data大概这样
{"rss_link":"https://mikanani.me/RSS/MyBangumi?token=krNkt6UoevhqreNzL%2fZKAQ%3d%3d","data_version":4.0,"bangumi_info":[{"official_title":"Isekai Ojisan","title_raw":"Isekai Ojisan","season":1,"season_raw":"","group":"悠哈璃羽字幕社","dpi":"1080p","source":null,"subtitle":"简体内嵌","added":true,"eps_collect":true},{"official_title":"Kinsou no Vermeil","title_raw":"Kinsou no Vermeil","season":1,"season_raw":"","group":"喵萌奶茶屋&LoliHouse","dpi":"1080p","source":"WebRip","subtitle":"简繁日内封字幕","added":true,"eps_collect":true},{"official_title":"Lycoris Recoil","title_raw":"Lycoris Recoil","season":1,"season_raw":"","group":"悠哈璃羽字幕社","dpi":"1080p","source":null,"subtitle":"CHS","added":true,"eps_collect":true},{"official_title":"Summer Time Rendering","title_raw":"Summer Time Rendering","season":1,"season_raw":"","group":"幻樱字幕组","dpi":"1920X1080","source":null,"subtitle":"GB","added":true,"eps_collect":true}]}

![image](https://user-images.githubusercontent.com/29850930/181802621-d42c0f1e-62f9-4929-8289-4359f561d9ac.png)
文件结构大概这样

**Comment by EstrellaXD** [comment]
> 重命名似乎会报这么个错，然后完全无法重命名 Traceback (most recent call last): File "/src/app.py", line 111, in run() File "/src/app.py", line 107, in run main_process(bangumi_data, download_client) File "/src/app.py", line 79, in main_process rename.run() File "/src/core/renamer.py", line 60, in run path_name, season, folder_name, suffix, _ = self.split_path(info.content_path) File "/usr/local/lib/python3.10/site-packages/qbittorrentapi/_attrdict.py", line 149, in **getattr** raise AttributeError( AttributeError: 'TorrentDictionary' instance has no attribute 'content_path'
> 
> data大概这样 {"rss_link":"[https://mikanani.me/RSS/MyBangumi?token=krNkt6UoevhqreNzL%2fZKAQ%3d%3d","data_version":4.0,"bangumi_info":[{"official_title":"Isekai](https://mikanani.me/RSS/MyBangumi?token=krNkt6UoevhqreNzL%2fZKAQ%3d%3d%22,%22data_version%22:4.0,%22bangumi_info%22:%5B%7B%22official_title%22:%22Isekai) Ojisan","title_raw":"Isekai Ojisan","season":1,"season_raw":"","group":"悠哈璃羽字幕社","dpi":"1080p","source":null,"subtitle":"简体内嵌","added":true,"eps_collect":true},{"official_title":"Kinsou no Vermeil","title_raw":"Kinsou no Vermeil","season":1,"season_raw":"","group":"喵萌奶茶屋&LoliHouse","dpi":"1080p","source":"WebRip","subtitle":"简繁日内封字幕","added":true,"eps_collect":true},{"official_title":"Lycoris Recoil","title_raw":"Lycoris Recoil","season":1,"season_raw":"","group":"悠哈璃羽字幕社","dpi":"1080p","source":null,"subtitle":"CHS","added":true,"eps_collect":true},{"official_title":"Summer Time Rendering","title_raw":"Summer Time Rendering","season":1,"season_raw":"","group":"幻樱字幕组","dpi":"1920X1080","source":null,"subtitle":"GB","added":true,"eps_collect":true}]}
> 
> ![image](https://user-images.githubusercontent.com/29850930/181802621-d42c0f1e-62f9-4929-8289-4359f561d9ac.png) 文件结构大概这样
> 
> 看了下源代码，难道是因为我qb版本不对，拿不到种子信息？我下的80x86的4.2.1……

可能老版本的 QB API 和新版本对不上，目测是 API 问题

**Comment by EstrellaXD** [comment]
> 报错地点：
> 改名器：rename failed类型错误
> 原文件名称/字幕组命名名称：
> DEBUG: name 'name' is not defined
> [2022-07-29 23:11:11,342] DEBUG: Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1
> [2022-07-29 23:11:11,342] WARNING: [Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC][v2].mp4 rename failed

测试了一下没发现具体问题，打开的模式是normal么？是否有更加详细的log和文件路径提供一下

**Comment by EstrellaXD** [comment]
> 报错地点：
> 改名器：rename failed类型错误
> 原文件名称/字幕组命名名称：
> DEBUG: name 'name' is not defined
> [2022-07-29 23:11:11,342] DEBUG: Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1
> [2022-07-29 23:11:11,342] WARNING: [Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC][v2].mp4 rename failed

测试了一下没发现具体问题，打开的模式是normal么？是否有更加详细的log和文件路径提供一下

**Comment by EstrellaXD** [comment]
该 issue 关闭，未来新 bug 请使用模板提问，本 issue 内的问题还会继续跟踪。

**Comment by zoooo0** [comment]
> 报错地点： 改名器：rename failed类型错误 原文件名称/字幕组命名名称： DEBUG: name 'name' is not defined [2022-07-29 23:11:11,342] DEBUG: Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1 [2022-07-29 23:11:11,342] WARNING: [Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC][v2].mp4 rename failed

qb: 映射路径 /root/AutoBangumi/Downloads —— qb容器路径 /Downloads
AB_DOWNLOAD_PATH=/Downloads/AutoBangumi
下载完成种子实际路径：/root/AutoBangumi/Downloads/AutoBangumi/异世界归来的舅舅 (2022)/Season 1/[Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC].mp4
                  容器内路径：/Downloads/AutoBangumi/异世界归来的舅舅 (2022)/Season 1/[Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC].mp4

[2022-07-30 11:27:39,921] DEBUG:    Start adding rules.
[2022-07-30 11:27:39,922] DEBUG:    Finished.
[2022-07-30 11:27:39,922] INFO:     Finished
[2022-07-30 11:27:39,922] INFO:     Running....
[2022-07-30 11:27:39,922] DEBUG:    Saved
[2022-07-30 11:27:40,005] DEBUG:    http://```````:8989 "POST /api/v2/torrents/info HTTP/1.1" 200 9185
[2022-07-30 11:27:40,008] DEBUG:    Name: 租借女友 (2020), File type: .mp4, Season 2
[2022-07-30 11:27:40,008] WARNING:  [云光字幕组] 租借女友 - Kanojo, Okarishimasu  [14][简体双语][1080p]招募时轴.mp4.mp4 rename failed
[2022-07-30 11:27:40,008] DEBUG:    name 'name' is not defined
[2022-07-30 11:27:40,008] DEBUG:    Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1
[2022-07-30 11:27:40,008] WARNING:  [Nekomoe kissaten][Isekai Ojisan][01][1080p][JPSC].mp4 rename failed
[2022-07-30 11:27:40,008] DEBUG:    name 'name' is not defined
[2022-07-30 11:27:40,009] DEBUG:    Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1
[2022-07-30 11:27:40,009] WARNING:  [Nekomoe kissaten][Isekai Ojisan][02][1080p][JPSC].mp4 rename failed
[2022-07-30 11:27:40,009] DEBUG:    name 'name' is not defined
[2022-07-30 11:27:40,009] DEBUG:    Name: 租借女友 (2020), File type: .mp4, Season 2
[2022-07-30 11:27:40,009] WARNING:  [云光字幕组] 租借女友 - Kanojo, Okarishimasu  [13][简体双语][1080p]招募时轴.mp4.mp4 rename failed
[2022-07-30 11:27:40,009] DEBUG:    name 'name' is not defined
[2022-07-30 11:27:40,009] DEBUG:    Name: 彻夜之歌 (2022), File type: .mp4, Season 1
[2022-07-30 11:27:40,009] WARNING:  [UHA-WINGS][Yofukashi no Uta][03][x264 1080p][CHS].mp4 rename failed
[2022-07-30 11:27:40,009] DEBUG:    name 'name' is not defined
[2022-07-30 11:27:40,009] DEBUG:    Name: 异世界归来的舅舅 (2022), File type: .mp4, Season 1
[2022-07-30 11:27:40,009] WARNING:  [Nekomoe kissaten][Isekai Ojisan][03][1080p][JPSC].mp4 rename failed
