### ISSUE TITLE
重命名路径后，原文件夹没有被删除

### ISSUE THREAD

**Issue by nvmiku39** [EstrellaXD/Auto_Bangumi#415]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.11

### 问题类型

其他问题

### 问题描述

windows本地部署下，在webui中修改年份后，qb会将其移动到以“间谍教室 (2023)”这样形式的文件夹下，但完成该操作后，原文件夹没有被删除。
![QQ截图20230804124812](https://github.com/EstrellaXD/Auto_Bangumi/assets/82427934/fbfae9b9-50b0-4fee-908f-8e000a9784bc)

**Comment by EstrellaXD** [comment]
AB 没有权限管理用户文件夹。可以自行删除或者检测脚本。
