### ISSUE TITLE
[Feature Request] 请求增加对ipv6的支持

### ISSUE THREAD

**Issue by ShimonZhan** [EstrellaXD/Auto_Bangumi#416]
### 功能改进

因为家里公网只有ipv6，请求增加对ipv6的支持，谢谢

**Comment by zthxxx** [comment]
现在是哪项功能不支持 IPv6，能详细描述下你遇到的问题吗？

**Comment by ShimonZhan** [comment]
是这样的，我使用docker的host模式部署在truenas scale 22.12.3.3，在容器内命令行ifconfig能成功看见宿主的ipv6地址，但是无法使用ipv6地址访问

**Comment by Nchyn** [comment]
> 没用的，现在不能从外部直接访问家宽IPv6地址，我之前问过运营商了，建议使用花生壳或者ngrok这类软件。

不能从外部直接访问是因为光猫防火墙默认block了入站请求，打开就行。

**Comment by pboymt** [comment]
> > 没用的，现在不能从外部直接访问家宽IPv6地址，我之前问过运营商了，建议使用花生壳或者ngrok这类软件。
> 
> 不能从外部直接访问是因为光猫防火墙默认block了入站请求，打开就行。

那他这个情况只需要再部署一个nginx反代就行了。

**Comment by ShimonZhan** [comment]
> > > 没用的，现在不能从外部直接访问家宽IPv6地址，我之前问过运营商了，建议使用花生壳或者ngrok这类软件。
> > 
> > 
> > 不能从外部直接访问是因为光猫防火墙默认block了入站请求，打开就行。
> 
> 那他这个情况只需要再部署一个nginx反代就行了。

是的 后面这样解决了

**Comment by pboymt** [comment]
> > > > 没用的，现在不能从外部直接访问家宽IPv6地址，我之前问过运营商了，建议使用花生壳或者ngrok这类软件。
> > > 
> > > 
> > > 不能从外部直接访问是因为光猫防火墙默认block了入站请求，打开就行。
> > 
> > 那他这个情况只需要再部署一个nginx反代就行了。
> 
> 是的 后面这样解决了

因为你监听的是127.0.0.1，是本地回环，如果想让外部访问，除了防火墙打开以外，还得监听0.0.0.0
