### ISSUE TITLE
创建项目时报错拉取不到镜像，报错如图

### ISSUE THREAD

**Issue by LastSongz** [EstrellaXD/Auto_Bangumi#417]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0.11

### 问题类型

其他问题

### 问题描述

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/49801242/ac43f6c8-a649-4848-8712-49d98c3d2112)

**Comment by EstrellaXD** [comment]
请仔细阅读文档

**Comment by EstrellaXD** [comment]
看了下文档有些错误，你只要在报错路径下创建相应文件夹即可。

**Comment by LastSongz** [comment]
> 

收到，我已发现问题，感谢回复
