### ISSUE TITLE
海贼王订阅下载失败

### ISSUE THREAD

**Issue by Ignatius-Ye** [EstrellaXD/Auto_Bangumi#42]
![微信图片_20220624144422](https://user-images.githubusercontent.com/37823715/175478565-d79497fa-bf67-47d7-821b-acf4ed13da8a.png)
![微信图片_20220624144428](https://user-images.githubusercontent.com/37823715/175478579-f49e0546-4167-468d-9f8e-57db7930310b.png)
海贼王订阅下载识别
最新版本
系统 群晖7.1

**Comment by EstrellaXD** [comment]
详见 #41
