### ISSUE TITLE
[Feature Request]TMDB解析增加使用API的方式

### ISSUE THREAD

**Issue by tang-bai** [EstrellaXD/Auto_Bangumi#439]
### 功能改进

TMDB增加api的访问可以使用api.tmdb.org/api.themoviedb.org 之类访问可以解决国内因为网络的相关问题无法使用TMDB的解析方式

**Comment by EstrellaXD** [comment]
是想自定义api url解析么

**Comment by tang-bai** [comment]
对的类似于这样子
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/71223830/082b9481-fa46-405b-aed8-a559af3bffad)
因为目前使用tmdb进行解析可能需要挂梯子如果可以支持自定义api就可以进行裸连解析处理

**Comment by alex-oos** [comment]
感觉很不错
