### ISSUE TITLE
[Discussion] 全都不太好用

### ISSUE THREAD

**Issue by datefate** [EstrellaXD/Auto_Bangumi#447]
## 文档问题
首先登录界面就和截图不一致（v4.5.5），配置界面有点说明说不清。
## 日志问题
` Uvicorn running on http://0.0.0.0:7892 `  应该是127.0.0.1；其次给出问题排查，没法用日志错误来查找

**Comment by EstrellaXD** [comment]
你在说什么？请确认是否发对了地方

**Comment by zthxxx** [comment]
离谱，这位是找错仓库了吧

**Comment by datefate** [comment]
对不起,半夜脑袋不清醒*((*^(^*&(^*(9(吐白沫
si mi ma se n
