### ISSUE TITLE
[解析器错误]  星空字幕组&LoliHouse 五等分的新娘∽ / Go-toubun no Hanayome 

### ISSUE THREAD

**Issue by sirongzi** [EstrellaXD/Auto_Bangumi#449]
### 当前程序版本

3.0.12

### 解析器语言设置

默认：zh

### TMDB 解析

否

### 字幕组提供的名称

[星空字幕组&LoliHouse] 五等分的新娘∽ / Go-toubun no Hanayome ∽ 01 [WebRip 1080p HEVC-10bit AAC][简繁日内封字幕]（检索用：暑假篇）

### 错误识别名称

WARNING:  Cannot parse [星空字幕组&LoliHouse] 五等分的新娘∽ / Go-toubun no Hanayome ∽ 01 [WebRip 1080p HEVC-10bit AAC][简繁日内封字幕]（检索用：暑假篇）.

**Comment by EstrellaXD** [comment]
应该是特殊符号导致的，下个版本调整。
