### ISSUE TITLE
[Feature Request]能否将海报图片的源地址改为mikanime.tv

### ISSUE THREAD

**Issue by Angelyeye** [EstrellaXD/Auto_Bangumi#450]
### 功能改进

能否将海报图片的源地址改为mikanime.tv，或者增加一个可选项，选择使用.tv还是.me，如果使用代理方法那QB也要设置代理，整个流程就比较复杂了，直接改源会更方便些

**Comment by EstrellaXD** [comment]
Already done in v3.1
