### ISSUE TITLE
蜜柑的 RSS 生成似乎有些 bug

### ISSUE THREAD

**Issue by ash0080** [EstrellaXD/Auto_Bangumi#46]
目前发现的问题有:

 1. 单字幕组订阅无法触发更新, 只有全部订阅才会有;
 2. 取消订阅RSS链接也不会清空; 
 2022.7.3

![Screen Shot 2022-07-03 at 02 48 13](https://user-images.githubusercontent.com/2803210/177012889-b8ab4fd6-3948-446d-a947-222f1d50babf.png)

**Comment by EstrellaXD** [comment]
请联系蜜柑计划
