### ISSUE TITLE
[错误报告]番剧补全不生效

### ISSUE THREAD

**Issue by spirytuslove** [EstrellaXD/Auto_Bangumi#469]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.1

### 问题类型

WebUI

### 问题描述

订阅后番剧补全不生效 后台看了下也没有错误日志 问下是需要其他设置吗

**Comment by EstrellaXD** [comment]
设置里打开番剧补全

**Comment by spirytuslove** [comment]
已经开了 日志也正常 但就是没补全

**Comment by JKSTAFF** [comment]
3.1.11存在相同问题，因为服务器停机错过某一周的下载，即使开启了番剧补全选项卡，再下一周的更新也不会重新下载上周错过的下载集数

**Comment by okatu-loli** [comment]
3.1.11存在相同问题，设置里打开了番剧补全，不会下载错过的集数
