### ISSUE TITLE
[Discussion] 能否支持国漫呀

### ISSUE THREAD

**Issue by xiatian12345** [EstrellaXD/Auto_Bangumi#471]
### 项目讨论

虽然但是，理论上可以支持国漫吧

**Comment by EstrellaXD** [comment]
取决于字幕组命名，现在国漫命名千奇百怪，会给开发增加非常多的负担。如果能让国漫组统一命名规范实现起来是不难的。

**Comment by xiatian12345** [comment]
> 取决于字幕组命名，现在国漫命名千奇百怪，会给开发增加非常多的负担。如果能让国漫组统一命名规范实现起来是不难的。

是呢，国漫命名确实千奇百怪
