### ISSUE TITLE
[Feature Request] 为Bark通知增加番剧封面图标

### ISSUE THREAD

**Issue by tjljw2000** [EstrellaXD/Auto_Bangumi#477]
### 功能改进

在请求中附加番剧海报链接以显示图标

根据[Bark使用教程](https://bark.day.app/#/tutorial?id=%e8%af%b7%e6%b1%82%e5%8f%82%e6%95%b0)，在data中添加icon属性：
```python
# file: /backend/src/module/notification/plugin/bark.py
    def post_msg(self, notify: Notification) -> bool:
        text = self.gen_message(notify)
        data = {"title": notify.official_title, "body": text, "icon": notify.poster_path, "device_key": self.token}
        resp = self.post_data(self.notification_url, data)
        logger.debug(f"Bark notification: {resp.status_code}")
        return resp.status_code == 200
```

预览测试例
```
https://api.day.app/{token}/庙不可言/更新集数：第10集?icon=https://mikanani.me/images/Bangumi/202307/3fbb135e.jpg
```
使用效果
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/15904439/8fb7a2b1-2c70-43d5-946f-9722627d3fbe)

**Comment by hot36952** [comment]
> ```
> icon=https://mikanani.me/images/Bangumi/202307/3fbb135e.jpg
> ```
请问手机端是否要挂梯子？通知才能显示这个图标

**Comment by Eiranya** [comment]
好像不太行？消息显示

```
更新集数：第x集
posters/xxxx.jpg
```

**Comment by tjljw2000** [comment]
> @tjljw2000
> 
> > ```
> > icon=https://mikanani.me/images/Bangumi/202307/3fbb135e.jpg
> > ```
> 
> 请问手机端是否要挂梯子？通知才能显示这个图标

要的

**Comment by tjljw2000** [comment]
> 好像不太行？消息显示
> 
> ```
> 番剧名称：XXXX
> 季度：第X季
> 更新集数：第x集
> posters/xxxx.jpg
> ```

@EstrellaXD 我测试的番剧poster_path写的远程地址，这种用的本地路径的会出错。感觉应该用poster_link，而不是poster_path（没验证）。

**Comment by Eiranya** [comment]
> > 好像不太行？消息显示
> > ```
> > 番剧名称：XXXX
> > 季度：第X季
> > 更新集数：第x集
> > posters/xxxx.jpg
> > ```
> 
> @EstrellaXD 我测试的番剧poster_path写的远程地址，这种用的本地路径的会出错。感觉应该用poster_link，而不是poster_path（没验证）。

我也没改啥呀，怎么会变成用本地路径呢？

**Comment by KuroiCc** [comment]
pr #515 3.1.5发布以后, 海报转为本地缓存了`bangumi.poster_link`变成了本地路径, `poster_path`自然变成了本地路径
而bark配置通知icon需要指定一个可以公开访问的链接, 此为bug

@EstrellaXD 是否需要开一个新的issue?
