### ISSUE TITLE
[重命名错误] 悠哈璃羽字幕社 死神 千年血战篇

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#488]
### 当前程序版本

3.1.2

### 重命名设置

默认：pn

### 种子名称

 [UHA-Wing] [Bleach - Thousand-Year Blood War][24] [x264 1080p] [CHS].mp4

### 文件路径

/死神 千年血战篇 (2023)/Season 1

### 错误命名

S01E24.mp4

### 发生问题时系统日志

```shell
[2023-09-29 01:30:52] INFO:     [UHA-Wing] [Bleach - Thousand-Year Blood War][24] [x264 1080p] [CHS].mp4 >>  S01E24.mp4
```

**Comment by EstrellaXD** [comment]
其他重命名没有 bug 么

**Comment by Ovler-Young** [comment]
> 其他重命名没有 bug 么

悠哈璃羽之前的灵能百分百第三季没有这个问题；其他片好像也没有发现这个情况
