### ISSUE TITLE
有关下载规则全局黑名单关键词缺点

### ISSUE THREAD

**Issue by VEWION** [EstrellaXD/Auto_Bangumi#49]
比如喵萌不同番剧会提供各种版本
繁体(内嵌) 简体(内嵌) 简繁内封 等
我想要优先下载"简繁内封"但不是每一部番都有提供内封，没有内封才下载"简体"或者"繁体"(内嵌)
这样如果在AB_NOT_COTAIN加入"简体"或者"繁体"的话会导致没内封的番完全没法匹配
如何避免有提供内封的番同时下载到简繁内封和内嵌，又能在没内封的番下载简体/繁体内嵌版本?

**Comment by EstrellaXD** [comment]
可以在qb里面对每个规则的关键词单独定义
