### ISSUE TITLE
[Discussion] 请问番剧补全在哪里设置呢？项目说明的FAQ里有提到这个[番剧补全]的参数。

### ISSUE THREAD

**Issue by crazyhonor** [EstrellaXD/Auto_Bangumi#490]
### 项目讨论

找了下web的设置和安装时的参数设置，并没有找到这个[番剧补全]相关的设置，请教一下如何设置。现在只能获取订阅当天及以后更新变得种子，之前更新的种子无法获取。

**Comment by EstrellaXD** [comment]
<img width="731" alt="image" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/33726646/023b472c-4b6e-4d53-bfbf-a6b8f61062ec">
在这里
