### ISSUE TITLE
[Feature Request] 重命名

### ISSUE THREAD

**Issue by Michael7711** [EstrellaXD/Auto_Bangumi#499]
### 功能改进

希望增加 类似 TVDB 的 [Aired Order], 或 [DVD Order], 命名方法

例如: [Nekomoe kissaten][Spy Room][13][1080p][JPTC].mp4    

现在的命名方式是: .../Season 2/Spy Room S01E13.mp4

希望改进的是: .../Season 2/Spy Room S02E1.mp4      這樣可以變成第二季第一集

**Comment by EstrellaXD** [comment]
#279
