### ISSUE TITLE
能否提供 Linux/macOS/Windows 安装包吗？

### ISSUE THREAD

**Issue by taotieren** [EstrellaXD/Auto_Bangumi#5]
可以配置 Github 的 Actions CI/CD 仓库。使用 docker 没那么方便，一些软件包在 linux 下已经有了。再装一次是不是太占空间了。

**Comment by EstrellaXD** [comment]
> 可以配置 Github 的 Actions CI/CD 仓库。使用 docker 没那么方便，一些软件包在 linux 下已经有了。再装一次是不是太占空间了。

qb和媒体库不需要装在docker中，只需要部署 AutoBangumi 即可

**Comment by masquevil** [comment]
windows 的 docker 非常难用，真的如果能有个安装包就太好了…

**Comment by EstrellaXD** [comment]
> 建议添加一个非 docker 部署的教程吧（其实是因为我的 htpc 虚拟化打不开，开了就视频播放卡顿，HDMI 没有音频输出）。Windows 部署到本地的大致步骤如下：
> 
> 1. 克隆当前仓库: `git clone https://github.com/EstrellaXD/Auto_Bangumi.git`
> 2. 创建一个新的分支:
>    ```powershell
>    cd Auto_Bungumi
>    git checkout -n non-docker-deployment
>    ```
> 3. 修改 `auto_bangumi/api.py` 和 `auto_bangumi/conf/const.py` 中的几个 docker 挂载相关的绝对路径：
>    ```diff
>    # api.py
>    14a15,17
>    > import os
>    > PKG_DIR = os.path.dirname(os.path.realpath(__file__))
>    >
>    58c61
>    <     json_config.save("/config/config.json", data)
>    ---
>    >     json_config.save(os.path.join(PKG_DIR, "config/config.json"), data)
>    
>    # const.py
>    2a3,5
>    > import os
>    > PKG_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
>    >
>    14c17
>    <     "info_path": "/config/bangumi.json",
>    ---
>    >     "info_path": os.path.join(PKG_DIR, "config/bangumi.json"),
>    ```
> 4. 根据自己的需要修改配置，直接在 `const.py` 里修改 `DEFAULT_SETTINGS` 可以免去设置 Windows 环境变量的麻烦，比如添加一项 `rss_link` 直接填入自己的链接，`download_path`用 r string 填上自己的下载地址什么的。
> 5. 新建虚拟环境并安装依赖:
>    ```powershell
>    python -m venv env
>    .\env\Scripts\Activate.ps1
>    python -m pip install -r requirements.txt
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    这时就可以测试一下运行是否正常了，正常的话就 `commit`.
> 6. 接下来配置成服务做到开机自启:
>    ```powershell
>    (Get-Command python).Source # 这是虚拟环境中 python 解释器的位置
>    sudo nssm isntall AutoBangumiAPI
>    sudo nssm install AutoBangumi
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    在 NSSM 窗口中填上对应内容，即可执行文件为 python 解释器，参数为 `api.py` 和 `app.py`，工作路径就是含有这两个文件的位置。当然，全部用绝对路径更保险。其中，在安装 `AutoBangumi` 的时候记得在 dependency 标签页填写 `AutoBangumiAPI`.
>    然后去服务里调整一下启动方式为延迟自动启动（其实是我懒，qBittorrent 有图形界面，也配置成服务好麻烦，NSSM 其实可以在启动 hook 里写一个脚本等待 qBittorrent 开始运行来达到类似效果，有兴趣的自己尝试吧）。
> 
> 当然，这些都是以已经安装了 `git`, `python` (添加进 `PATH`), `nssm`, `sudo`, `venv` 和 qBittorrent 为前提的，没有安装的建议直接用 [`scoop`](https://scoop.sh/) 安装，比如 `scoop install qbittorrent-enhanced`. 需要更新的时候 `checkout` 到 `main` 分支进行 `pull` 再回 `non-docker-deployment` 分支 `merge` 一下就好了 (应该也不会有什么 conflict)。
> 
> 总体来说感觉比 `flexget` 胜在自带了刮削，`flexget` 灵活度更高吧，自己定义 filter 和下载器之类的，而且部署起来很方便 `pip install` 就好了 (虽然我是还是因为种种原因只能从 source 安装)。

感谢回复，个人觉得这样对于新手来说门槛过高了。可能之后有空会做个非 docker 的分支。

**Comment by EstrellaXD** [comment]
> 建议添加一个非 docker 部署的教程吧（其实是因为我的 htpc 虚拟化打不开，开了就视频播放卡顿，HDMI 没有音频输出）。Windows 部署到本地的大致步骤如下：
> 
> 1. 克隆当前仓库: `git clone https://github.com/EstrellaXD/Auto_Bangumi.git`
> 2. 创建一个新的分支:
>    ```powershell
>    cd Auto_Bungumi
>    git checkout -n non-docker-deployment
>    ```
> 3. 修改 `auto_bangumi/api.py` 和 `auto_bangumi/conf/const.py` 中的几个 docker 挂载相关的绝对路径：
>    ```diff
>    # api.py
>    14a15,17
>    > import os
>    > PKG_DIR = os.path.dirname(os.path.realpath(__file__))
>    >
>    58c61
>    <     json_config.save("/config/config.json", data)
>    ---
>    >     json_config.save(os.path.join(PKG_DIR, "config/config.json"), data)
>    
>    # const.py
>    2a3,5
>    > import os
>    > PKG_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
>    >
>    14c17
>    <     "info_path": "/config/bangumi.json",
>    ---
>    >     "info_path": os.path.join(PKG_DIR, "config/bangumi.json"),
>    ```
> 4. 根据自己的需要修改配置，直接在 `const.py` 里修改 `DEFAULT_SETTINGS` 可以免去设置 Windows 环境变量的麻烦，比如添加一项 `rss_link` 直接填入自己的链接，`download_path`用 r string 填上自己的下载地址什么的。
> 5. 新建虚拟环境并安装依赖:
>    ```powershell
>    python -m venv env
>    .\env\Scripts\Activate.ps1
>    python -m pip install -r requirements.txt
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    这时就可以测试一下运行是否正常了，正常的话就 `commit`.
> 6. 接下来配置成服务做到开机自启:
>    ```powershell
>    (Get-Command python).Source # 这是虚拟环境中 python 解释器的位置
>    sudo nssm isntall AutoBangumiAPI
>    sudo nssm install AutoBangumi
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    在 NSSM 窗口中填上对应内容，即可执行文件为 python 解释器，参数为 `api.py` 和 `app.py`，工作路径就是含有这两个文件的位置。当然，全部用绝对路径更保险。其中，在安装 `AutoBangumi` 的时候记得在 dependency 标签页填写 `AutoBangumiAPI`.
>    然后去服务里调整一下启动方式为延迟自动启动（其实是我懒，qBittorrent 有图形界面，也配置成服务好麻烦，NSSM 其实可以在启动 hook 里写一个脚本等待 qBittorrent 开始运行来达到类似效果，有兴趣的自己尝试吧）。
> 
> 当然，这些都是以已经安装了 `git`, `python` (添加进 `PATH`), `nssm`, `sudo`, `venv` 和 qBittorrent 为前提的，没有安装的建议直接用 [`scoop`](https://scoop.sh/) 安装，比如 `scoop install qbittorrent-enhanced`. 需要更新的时候 `checkout` 到 `main` 分支进行 `pull` 再回 `non-docker-deployment` 分支 `merge` 一下就好了 (应该也不会有什么 conflict)。
> 
> 总体来说感觉比 `flexget` 胜在自带了刮削，`flexget` 灵活度更高吧，自己定义 filter 和下载器之类的，而且部署起来很方便 `pip install` 就好了 (虽然我是还是因为种种原因只能从 source 安装)。

已更新至 Wiki
