### ISSUE TITLE
重复下载

### ISSUE THREAD

**Issue by foxlesbiao** [EstrellaXD/Auto_Bangumi#50]
![image](https://user-images.githubusercontent.com/41581909/177717375-f3dc1e27-a14c-46bb-8506-4ce5ca261502.png)
![image](https://user-images.githubusercontent.com/41581909/177717463-63cdde37-b996-4d76-8c0c-f1a7c41bd138.png)

autobangumi 会重复添加下载任务和新建文件夹

**Comment by EstrellaXD** [comment]
> ![image](https://user-images.githubusercontent.com/41581909/177717375-f3dc1e27-a14c-46bb-8506-4ce5ca261502.png) ![image](https://user-images.githubusercontent.com/41581909/177717463-63cdde37-b996-4d76-8c0c-f1a7c41bd138.png)
> 
> autobangumi 会重复添加下载任务和新建文件夹

请使用蜜柑的高级订阅，只订阅一种字幕，并且在 `AB_NOT_CONTAIN` 中配置过滤关键词

**Comment by foxlesbiao** [comment]
我有使用了，但是我重启容器就会重新下载

**Comment by EstrellaXD** [comment]
> 我有使用了，但是我重启容器就会重新下载

请提供一下 log
