### ISSUE TITLE
[错误报告]用另一个帖子里的unraid模板安装ab 启动后就自动停止 找不出是哪里的问题

### ISSUE THREAD

**Issue by tao08ms** [EstrellaXD/Auto_Bangumi#501]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.3

### 问题类型

程序运行问题

### 问题描述

用另一个帖子里的unraid模板安装ab 启动后就自动停止 找不出是哪里的问题
模板是这贴里的https://github.com/EstrellaXD/Auto_Bangumi/issues/132

**Comment by shininome** [comment]
使用docker-comepose部署呢,没用过unraid

**Comment by EstrellaXD** [comment]
看了下模板，应该是2.5版本的，我看下怎么写新版模板。

**Comment by 9bingyin** [comment]
```
<?xml version="1.0"?>
<Container version="2">
  <Name>AutoBangumi</Name>
  <Repository>ghcr.io/estrellaxd/auto_bangumi</Repository>
  <Registry>https://github.com/EstrellaXD/Auto_Bangumi</Registry>
  <Network>bridge</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support/>
  <Project/>
  <Overview/>
  <Category/>
  <WebUI>http://[IP]:[PORT:7892]</WebUI>
  <TemplateURL/>
  <Icon>https://quantil.jsdelivr.net/gh/9bingyin/static@main/images/AutoBangumi.png</Icon>
  <ExtraParams/>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1696399635</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="WebUI" Target="7892" Default="7892" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">7892</Config>
  <Config Name="Config" Target="/app/config" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/AutoBangumi/config</Config>
  <Config Name="Data" Target="/app/data" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/AutoBangumi/data</Config>
</Container>
```

**Comment by greenhat616** [comment]
😂你还另开贴了啊

问题在这，cc @EstrellaXD https://github.com/EstrellaXD/Auto_Bangumi/issues/132#issuecomment-1745426507

**Comment by tao08ms** [comment]
> 😂你还另开贴了啊
> 
> 问题在这，cc @EstrellaXD [#132 (comment)](https://github.com/EstrellaXD/Auto_Bangumi/issues/132#issuecomment-1745426507)

根据上面的模板改了下 已经可以正常使用了

**Comment by tao08ms** [comment]
> ```
> <?xml version="1.0"?>
> <Container version="2">
>   <Name>AutoBangumi</Name>
>   <Repository>ghcr.io/estrellaxd/auto_bangumi</Repository>
>   <Registry>https://github.com/EstrellaXD/Auto_Bangumi</Registry>
>   <Network>bridge</Network>
>   <MyIP/>
>   <Shell>sh</Shell>
>   <Privileged>false</Privileged>
>   <Support/>
>   <Project/>
>   <Overview/>
>   <Category/>
>   <WebUI>http://[IP]:[PORT:7892]</WebUI>
>   <TemplateURL/>
>   <Icon>https://quantil.jsdelivr.net/gh/9bingyin/static@main/images/AutoBangumi.png</Icon>
>   <ExtraParams/>
>   <PostArgs/>
>   <CPUset/>
>   <DateInstalled>1696399635</DateInstalled>
>   <DonateText/>
>   <DonateLink/>
>   <Requires/>
>   <Config Name="WebUI" Target="7892" Default="7892" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">7892</Config>
>   <Config Name="Config" Target="/app/config" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/AutoBangumi/config</Config>
>   <Config Name="Data" Target="/app/data" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/AutoBangumi/data</Config>
> </Container>
> ```
 多谢 这个模版可以正常使用了
