### ISSUE TITLE
[错误报告] WARNING:  Failed to send notification: [Errno 21] Is a directory: 'data/'

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#522]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.6-fix

### 问题类型

WebUI

### 问题描述

发送消息失败：WARNING:  Failed to send notification: [Errno 21] Is a directory: 'data/'

发送服务为Telegram，之前发送均无问题

### 发生问题时系统日志

```bash
[2023-10-05 10:55:30] INFO:     [ANi] 16bit 的感動 ANOTHER LAYER - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 16bit 的感動 ANOTHER LAYER S01E01.mp4
[2023-10-05 10:55:31] WARNING:  Failed to send notification: [Errno 21] Is a directory: 'data/'
```

**Comment by shininome** [comment]
@Ovler-Young 这个是图片没下载下来，不过下载下来也发送不了，放心

**Comment by EstrellaXD** [comment]
看下海报地址是否为本地，是否有海报地址。

**Comment by Ovler-Young** [comment]
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/44089074/e9c802c5-d2ee-49cf-8a66-1a5ebdcbf460)
并且对应的 AB域名/posters/8df6be63.jpg 可以正确返回海报
