### ISSUE TITLE
[错误报告]删除订阅时如果重复删除会重复报错

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#523]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.6-fix

### 问题类型

WebUI

### 问题描述

删除后对话框没缩回去 又~手贱~点了下 就没法关了 刷新后正常
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/44089074/4659efb2-0b47-462a-8962-a6a5e6e32bef)
预期处理方法：如果报错 Cannot find bangumi id 则返回已删除

### 发生问题时系统日志

```bash
WARNING:  [Database] Cannot find bangumi id: 52.
```

**Comment by EstrellaXD** [comment]
刷新一下规则应该就没了？前端问题我再看看。

**Comment by Ovler-Young** [comment]
的确刷新了就没了

**Comment by Ovler-Young** [comment]
Upd：RSS Item部分并未删除该RSS
