### ISSUE TITLE
[错误报告]切换搜索引擎时搜索栏内容被清空

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#528]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.7

### 问题类型

WebUI

### 问题描述

切换搜索引擎时搜索栏内容被清空

**Comment by EstrellaXD** [comment]
这个设计是这样的，我看看能不能优化
