### ISSUE TITLE
[文档] wiki的侧边栏少数链接指向错误

### ISSUE THREAD

**Issue by xiaoyv404** [EstrellaXD/Auto_Bangumi#53]
错误的页面有：
- API
- 环境变量
- 常见问题

**Comment by xiaoyv404** [comment]
原本说想发pr贡献一下的，发现github这个wiki是在新的一个存储库的，贡献方式也奇奇怪怪的。。。
我觉得最好是开一个新的项目，专门放wiki

**Comment by EstrellaXD** [comment]
> 原本说想发pr贡献一下的，发现github这个wiki是在新的一个存储库的，贡献方式也奇奇怪怪的。。。
> 我觉得最好是开一个新的项目，专门放文档

感谢建议，可以在 https://github.com/EstrellaXD/ab_resource 贡献

**Comment by xiaoyv404** [comment]
> 感谢建议，可以在 https://github.com/EstrellaXD/ab_resource 贡献
嗯嗯

**Comment by xiaoyv404** [comment]
既然这个问题解决了，那我先关掉这个issue了
