### ISSUE TITLE
[错误报告]docker-compose重新部署导致rss失效

### ISSUE THREAD

**Issue by QNV5** [EstrellaXD/Auto_Bangumi#536]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.7

### 问题类型

程序运行问题

### 问题描述

使用docker重新部署后，rss无法自动下载番剧，日志未输出rss相关信息，使用下载软件qBittorrent-nox 4.1.9
且首页删除应番剧时，对应RSS不会自动删除

**Comment by QNV5** [comment]
rss时定时刷新吗，时间间隔是多少

**Comment by EYW-015** [comment]
我这里使用docker cli部署，webui使用vuetorrent
- 重启容器会报`Program failed to start.`，切换为默认UI并重启ab可正常运行
- 容器重启后不会再对rss进行订阅，需要手动移除rss并重新添加，直到下次重启容器之前都可以正常订阅rss

**Comment by EstrellaXD** [comment]
> 我这里使用docker cli部署版本3.1.11，webui使用vuetorrent
> 
> * 重启容器会报`Program failed to start.`，切换为默认UI并重启ab可正常运行
> * 容器重启后不会再对rss进行订阅，需要手动移除rss并重新添加，直到下次重启容器之前都可以正常订阅rss

VueTorrent 会改变发送的 header，目前没做兼容处理。
不知道你说的 RSS 不能订阅是什么情况，3.1 之后不会在 QB 中订阅 RSS 了

**Comment by EYW-015** [comment]
@EstrellaXD
容器重启之后，即使蜜柑的rss有内容更新，ab日志中也没有订阅反应，qb中也没有添加新种子
在容器正常运行周期中，手动添加的rss会在此次运行中每周持续正常更新订阅
直至容器停止运行，所有订阅不再向qb添加新内容，需要手动重新添加
日志简洁没有任何反应，也不知道ab有没有对订阅更新成功，还是对qb推送失效

**Comment by EstrellaXD** [comment]
@EYW-015 请打开debug提供日志，记得重启容器

**Comment by EstrellaXD** [comment]
请在新 ISSUE 中提供相关信息。
