### ISSUE TITLE
[错误报告]天月動漫發佈組  腼腆英雄 重命名出错

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#537]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.7

### 问题类型

程序运行问题

### 问题描述

Rename Method从pn改为advance后
在处理如下种子时：https://mikanani.me/Home/Episode/8ded324a395f93a572dc4a6f8e3e249ebc397ae4 出错
种子内包含如下内容：
```
[Skymoon-Raws] Shy - 01 [ViuTV][WEB-DL][1080p][AVC AAC].mp4
[繁體中文 (Annotation)] SHY 靦腆英雄 ep 1 .ass
[繁體中文] SHY 靦腆英雄 ep 1 .ass
WeiRuanYaHei-1.ttf
```
包含两个ass的确非常奇怪……

### 发生问题时系统日志

```bash
[2023-10-07 00:47:48] INFO:     Shy S01E01.zh-tw.ass >> 腼腆英雄 (2023) S01E01.zh-tw.ass
[2023-10-07 00:47:48] WARNING:  [Renamer] Shy S01E01.zh-tw.ass rename failed
```

**Comment by EstrellaXD** [comment]
没办法解决，请找字幕组
