### ISSUE TITLE
[错误报告]之前版本中订阅的番剧海报无法正常显示

### ISSUE THREAD

**Issue by Ovler-Young** [EstrellaXD/Auto_Bangumi#538]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.7

### 问题类型

WebUI

### 问题描述

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/44089074/7f498993-9e81-4041-824e-421df3252fd0)
之前版本中订阅的番剧海报出错
原因为mikanime.tv的跳转会忽略大小写。
例如，https://mikanime.tv/images/Bangumi/202307/aa29da18.jpg 会跳到 https://mikanani.me/images/bangumi/202307/aa29da18.jpg，`Bangumi`变成`bangumi`，大小写发生变化导致图片获取失败，若手动替换为正确的大小写得到的链接 https://mikanani.me/images/Bangumi/202307/aa29da18.jpg 就是正常的。

预计的处理方式有俩，一是直接忽略它重新从TMDB获取，二是将mikanime.tv直接替换为mikanime.me。

**Comment by Ovler-Young** [comment]
1. 可以直接修改以下这行，加上mikanime.tv的判断，是mikanime.tv的就直接重新获取TMDB海报 https://github.com/EstrellaXD/Auto_Bangumi/blob/ed2acb96f31682d56015fa7f6084ee10f27f5191/backend/src/module/manager/torrent.py#L139 
```
if not bangumi.poster_link or "mikanime.tv" in bangumi.poster_link:
```
---
2. 也可以直接进行替换
https://github.com/EstrellaXD/Auto_Bangumi/blob/ed2acb96f31682d56015fa7f6084ee10f27f5191/backend/src/module/manager/torrent.py#L136-L147
```
def refresh_poster(self):
    bangumis = self.bangumi.search_all()
    for bangumi in bangumis:
        if not bangumi.poster_link:
            TitleParser().tmdb_poster_parser(bangumi)
        elif "mikanime.tv" in bangumi.poster_link:
            corrected_link = bangumi.poster_link.replace("mikanime.tv", "mikanime.me")
            bangumi.poster_link = corrected_link
    self.bangumi.update_all(bangumis)
    return ResponseModel(
        status_code=200,
        status=True,
        msg_en="Refresh poster link successfully.",
        msg_zh="刷新海报链接成功。",
    )
 ```

**Comment by EstrellaXD** [comment]
3.1.6升级的时候应该强制本地缓存了，没缓存是不是在升级的时候手动终止了

**Comment by Ovler-Young** [comment]
> 3.1.6升级的时候应该强制本地缓存了，没缓存是不是在升级的时候手动终止了

有可能是watchtower直接跳过了3.1.6升级到了3.1.7…

**Comment by EstrellaXD** [comment]
> > 3.1.6升级的时候应该强制本地缓存了，没缓存是不是在升级的时候手动终止了
> 
> 有可能是watchtower直接跳过了3.1.6升级到了3.1.7…

那也会有本地缓存，检查一下你的 `data/posters` 下是否有东西，删除 `posters` 文件夹重启。

**Comment by Ovler-Young** [comment]
理解了，因为在3.1.6之前就订阅了新番导致 `data/posters` 不为空未触发

**Comment by EstrellaXD** [comment]
> 理解了，因为在3.1.6之前就订阅了新番导致 `data/posters` 不为空未触发

更新之后是否解决问题？如果解决本 ISSUE 将关闭

**Comment by Ovler-Young** [comment]
因之前用的mikan反代关站导致一个图片下载失败，遂直接改db解决
