### ISSUE TITLE
部分续作的订阅规则不对

### ISSUE THREAD

**Issue by Icarus-H** [EstrellaXD/Auto_Bangumi#541]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.7

### 问题类型

WebUI

### 问题描述

1. 识别上有些漏洞，以 [ANi] 哥布林杀手 II - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] [451.72 MB] 为例，识别出来是写着第二季，season上却是1
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/53394732/d9d3e716-72ea-41fd-960a-97916799684b)

2. 希望在名称上能够去掉 【XXX 第三季】这种写法，直接写成 【XXX】，下面季度信息直接给数字就好，譬如图中的盾勇，这有两方面的考量。
    一、这样本身不算太规范；
    二、这样ab重命名的名称 是 【盾之勇者成名录 第三季 S03E01.mp4】而不是【盾之勇者成名录 S03E01.mp4】，而聪明的emby不太能识别出来前者
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/53394732/0e212373-043d-4daa-b569-981a2bc6dd7e)

**Comment by 991547436** [comment]
支持，去掉第几季合并成一个文件夹再分Season比较合适，这样emby刮削好些

**Comment by simon300000** [comment]
虽然来晚了，但是在需要和bgm同步的情况下，文件夹名为「盾之勇者成名录 第三季」能自动通过bgm插件搜索到bgm
