### ISSUE TITLE
webui - 实验功能设置 - openai默认模型名称Microsoft Azure OpenAI 无法使用

### ISSUE THREAD

**Issue by shancw96** [EstrellaXD/Auto_Bangumi#542]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.7

### 问题类型

WebUI

### 问题描述

Microsoft Azure OpenAI 部署模型无法添加特殊字符 `.`, 但是webui无法自定义模型名称，只有下拉选项 `gpt-3.5-turbo`，是否考虑提供输入框，允许自定义模型名称？

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/42959141/1eeebf89-63e0-4cef-b153-8f6642e28f3d)

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/42959141/e5b4ab9a-2468-47d6-a17a-aec132d46f6a)

https://github.com/EstrellaXD/Auto_Bangumi/blob/01064881df0a5c86c7010d1d657eff8c1dcb542f/backend/src/module/parser/analyser/openai.py#L52

**Comment by EstrellaXD** [comment]
CC， @100gle

**Comment by 100gle** [comment]
@shancw96 

我没用过 Azure OpenAI，想确认一下这个部署名是和模型名称绑定的吗？（顺便吐槽一下：命名 Azure OpenAI 和 OpenAI 用的是一套东西，竟然模型参数都不一致 orz）

**Comment by shancw96** [comment]
> @shancw96
> 
> 我没用过 Azure OpenAI，想确认一下这个部署名是和模型名称绑定的吗？（顺便吐槽一下：命名 Azure OpenAI 和 OpenAI 用的是一套东西，竟然模型参数都不一致 orz）

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/42959141/fa2492c6-240c-4275-9300-4b4bc5bc45d6)
部署名可以自定义

**Comment by 100gle** [comment]
@shancw96 方便留个联系方式？因为我这边没有Azure的Key，可能后面改的时候联系你这边提供一个base url和key来测试一下~

**Comment by shancw96** [comment]
shancw1996@gmail.com

**Comment by 100gle** [comment]
> [shancw1996@gmail.com](mailto:shancw1996@gmail.com) @100gle

OK，后续我测试时再提前邮箱联系你
