### ISSUE TITLE
[解析器错误][ANi] 竞速 OVERTAKE! - 02话解析错误，01话正常。

### ISSUE THREAD

**Issue by hot36952** [EstrellaXD/Auto_Bangumi#551]
### 当前程序版本

3.1.8

### 解析器语言设置

默认：zh

### TMDB 解析

是

### 字幕组提供的名称

[ANi] 竞速 OVERTAKE! - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]

### 错误识别名称

[2023-10-08 22:06:35] INFO:     [RSS] New bangumi founded: 猪猪侠之竞速小英雄 [2023-10-08 22:08:19] INFO:     [ANi] 競速 OVERTAKE! - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 猪猪侠之竞速小英雄 (2019) S06E02.mp4

**Comment by hot36952** [comment]
![QQ截图20231008223012](https://github.com/EstrellaXD/Auto_Bangumi/assets/21011227/523a9247-81c0-46a6-9c34-cb31ec3509c4)

**Comment by EstrellaXD** [comment]
@hot36952 看了下 TMDB 并没有收录竞速只收录了 OVERTAKE，删除或者自己调整名称都可以。

**Comment by hot36952** [comment]
> @hot36952 看了下 TMDB 并没有收录竞速只收录了 OVERTAKE，删除或者自己调整名称都可以。

删除了会再次[RSS] New bangumi founded: 猪猪侠之竞速小英雄。
自己调整名称的话，首页下方旧的海报要删除吗？

**Comment by EstrellaXD** [comment]
@hot36952 之后版本增加一个重新刷新海报的功能。

**Comment by hot36952** [comment]
![QQ图片20231008232038](https://github.com/EstrellaXD/Auto_Bangumi/assets/21011227/c1c61046-bce9-4ac9-b8df-ddbcb80bd422)
![QQ图片20231008232146](https://github.com/EstrellaXD/Auto_Bangumi/assets/21011227/3e5bd8db-65de-44ed-a76c-479940ba20b9)
`[2023-10-08 23:16:54] INFO:     [RSS] New bangumi founded: 暴食狂战士
[2023-10-08 23:16:55] INFO:     [RSS] New bangumi founded: 猪猪侠之竞速小英雄
[2023-10-08 23:16:56] INFO:     [RSS] New bangumi founded: OVERTAKE!
[2023-10-08 23:17:54] INFO:     [ANi] 暴食狂戰士 - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 >> 暴食狂战士 (2023) S01E02.mp4`

ANi组02话发布名称稍作修改，ab解释了个新的“暴食狂战士”出来。名称、年份、季度，都和之前01话解析的一样。

**Comment by EstrellaXD** [comment]
@hot36952 建议给ANI提意见，AB解析是负责生成下载规则，改变名称匹配字符改变自然视为多个规则。

**Comment by hot36952** [comment]
![ZK(L%7Z4)S}XVT3@81R 74B_tmb](https://github.com/EstrellaXD/Auto_Bangumi/assets/21011227/be61a94b-d001-4ba3-87db-000cd640bac5)
附上ANi的回复。
