### ISSUE TITLE
offset能设置负数吗

### ISSUE THREAD

**Issue by zofnk** [EstrellaXD/Auto_Bangumi#556]
### 功能改进

蜜柑上有的番剧第二季是连着第一季的是集数开始的，例如间谍过家家第二季S02E26，tmdb上边第二季是重新从E01开始了，但是offset是与上述反着的，能设置负数的吗

**Comment by Icarus-H** [comment]
补充，对于已经下载好并重命名的 【间谍过家家第二季S02E26】，我令offset: -25，不起作用。类似的还有【女友成双 第二季 S02E13】，【明日方舟 S01E09】

**Comment by hot36952** [comment]
offset这个设置目前应该是还没实装的。

**Comment by EstrellaXD** [comment]
#279
