### ISSUE TITLE
[解析器错误]  Cannot parse 

### ISSUE THREAD

**Issue by DEAN-Cherry** [EstrellaXD/Auto_Bangumi#558]
### 当前程序版本

3.1.8

### 解析器语言设置

默认：zh

### TMDB 解析

均尝试过，没有变化

### 字幕组提供的名称

[LoliHouse] 想要成为影之实力者！第二季 / 我想成为影之强者！第二季 / Kage no Jitsuryokusha ni Naritakute! S2 - <ep> [WebRip 1080p HEVC-10bit AAC][简繁内封字幕]

### 错误识别名称

 WARNING:  Cannot parse [LoliHouse] 想要成 ....

同时，在使用 搜索环节的时候，如果使用 `advance` 重命名方式，大部分的番剧都会显示 `Cannot parse...`；`normal`的会好一些，但是仍然有大量报错

如图为 `normal` 模式下的报错
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/76607677/73cc5109-a481-4e49-9177-673e7204f567)

`none` 模式下也测试了，并无改善。

**Comment by EstrellaXD** [comment]
warning非报错
