### ISSUE TITLE
下載檔案後qbittorrent狀態錯誤

### ISSUE THREAD

**Issue by Arcelibs** [EstrellaXD/Auto_Bangumi#56]
Synology Docker用戶，附上配置

**qbittorrent 配置**
![image](https://user-images.githubusercontent.com/49543451/178496426-047b2057-bf42-4faa-8d8f-f2ec9492ba17.png)
![image](https://user-images.githubusercontent.com/49543451/178496528-4a6c3a25-a5be-47b5-8f89-26ec5ed59ef9.png)

**qbittorrent 錯誤畫面**
![image](https://user-images.githubusercontent.com/49543451/178496656-1173a1f3-862a-40fa-94c8-5ec8c1e8923c.png)

**Auto_Bangumi 設置**
![image](https://user-images.githubusercontent.com/49543451/178496823-b22149c2-afe0-41b4-ac93-ec6b4e19356f.png)

**Comment by Arcelibs** [comment]
紀錄一下自己嘗試過的方法

1. 檢查qbittorrent 能否正常下載 → 不能
2. 檢查qbittorrent 下載資料夾權限 → 有，不能下載
3. 檢查qbittorrent 執行權限 → 改成UID 0 GID 0 目前可下載

**Comment by EstrellaXD** [comment]
是否还有遗留问题，如果没有本 issue 将关闭
