### ISSUE TITLE
[Feature Request]用最终匹配到的番剧名称决定是否加入bangumi database，避免重复添加

### ISSUE THREAD

**Issue by bocchi-otaku** [EstrellaXD/Auto_Bangumi#569]
### 功能改进

目前发现如果同一个组的片源第一集第二集名称如果出现繁体简体变化，或者大小写变化，会重复添加。或者是同一番剧如果来自不同组也会重复添加。不是很了解目前决定是否添加到database的规则，不知道是不是可以用最后匹配到的番剧名称来决定，以避免重复。
![image_2023-10-11_10-47-02](https://github.com/EstrellaXD/Auto_Bangumi/assets/48517391/2f941171-222b-4d7d-bb98-87ab8043d454)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/48517391/0a676631-8f65-4535-b42c-eed43d018b5b)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/48517391/50ca6d04-e9ab-47cf-92eb-6aeff6d33d1b)

**Comment by EstrellaXD** [comment]
https://github.com/EstrellaXD/Auto_Bangumi/issues/551#issuecomment-1752090790

**Comment by bocchi-otaku** [comment]
啊好吧= =（避免不同组的同一番剧重复添加能考虑一下吗= =

**Comment by shininome** [comment]
@bocchi-otaku 是的,我就是要下不同组的,一组ANI追新,一组xkl收藏

**Comment by bocchi-otaku** [comment]
好吧，我是ani追新，但是同时也会订阅别的字幕组，希望字幕组更新后直接覆盖掉。我的意思是这种情况下database只添加一个，然后海报墙上就只显示一个
