### ISSUE TITLE
[讨论] 关于 Web UI

### ISSUE THREAD

**Issue by Rewrite0** [EstrellaXD/Auto_Bangumi#57]
中午在群里提到打算写个webui,所以想收集下大概的功能  

根据目前的api可以列出以下的功能:  
- 日志查看  
- 查看已经订阅的番剧
- 重置ab数据
- 删除订阅中某番剧
- 订阅正在更新的来自其他来源的新番的rss
- 订阅旧番的rss

可能的功能:  
- 配置修改

**Comment by EstrellaXD** [comment]
一些个人见解：
Web UI 的方向可能还是尽量往番剧管理的角度会更加有用，这边可能会修正数据结构并且提供一些对 AB QB 规则本身编辑的 API 来综合使用。本身现在的 API 更多的还是偏向 DEBUG 的模式。在造 UI 的时候可能偏向前者会更加实用。相关功能的 API 也可以集思广益，我来开发提供。

**Comment by 2ndMan** [comment]
想做Web UI应该是想降低使用门槛，那么用正则表达式排除番剧的那一项能不能做成对小白更友好的形式。

**Comment by Rewrite0** [comment]
> 想做Web UI应该是想降低使用门槛，那么用正则表达式排除番剧的那一项能不能做成对小白更友好的形式。

排除番剧的话一般是用关键字词来排除, 不同的关键字词用`|`隔开我觉得门槛并不高, 如果你有其他排除番剧的形式可以给我说说

**Comment by 2ndMan** [comment]
> > 想做Web UI应该是想降低使用门槛，那么用正则表达式排除番剧的那一项能不能做成对小白更友好的形式。
> 
> 排除番剧的话一般是用关键字词来排除, 不同的关键字词用`|`隔开我觉得门槛并不高, 如果你有其他排除番剧的形式可以给我说说

主要是上个季度遇到了这种情况：有个组提供 1080P 和 1080P+ 两种资源，它们的名字也只有这部分有区别。排除设置里又不能设置 1080P ，所以怎么单独保留这部番剧的 1080P+ 就成了问题。或许正则表达式可以解决，但是仅依靠｜是做不到的吧。所以我在想能不能在 Web UI 中加上可视化的、更细致的筛选。面对某一番剧就可以设置为，排除 720P 或同时满足 XXX（名字）与 1080P 的资源。

**Comment by Rewrite0** [comment]
> > > 想做Web UI应该是想降低使用门槛，那么用正则表达式排除番剧的那一项能不能做成对小白更友好的形式。
> > 
> > 
> > 排除番剧的话一般是用关键字词来排除, 不同的关键字词用`|`隔开我觉得门槛并不高, 如果你有其他排除番剧的形式可以给我说说
> 
> 主要是上个季度遇到了这种情况：有个组提供 1080P 和 1080P+ 两种资源，它们的名字也只有这部分有区别。排除设置里又不能设置 1080P ，所以怎么单独保留这部番剧的 1080P+ 就成了问题。或许正则表达式可以解决，但是仅依靠｜是做不到的吧。所以我在想能不能在 Web UI 中加上可视化的、更细致的筛选。面对某一番剧就可以设置为，排除 720P 或同时满足 XXX（名字）与 1080P 的资源。

目前ab的排除规则是全局范围的, 这种情况需要 @EstrellaXD 提供针对单个番剧的筛选api, 然后我可以把筛选的正则做成模板式的填写以供使用.

**Comment by Rewrite0** [comment]
[https://github.com/Rewrite0/Auto_Bangumi_WebUI](https://github.com/Rewrite0/Auto_Bangumi_WebUI)  

先开了个空仓库, 如果有UI方面的建议, 可以先去提issue, 功能方面还是留在这讨论吧.

**Comment by EstrellaXD** [comment]
> > 主要是上个季度遇到了这种情况：有个组提供 1080P 和 1080P+ 两种资源，它们的名字也只有这部分有区别。排除设置里又不能设置 1080P ，所以怎么单独保留这部番剧的 1080P+ 就成了问题。或许正则表达式可以解决，但是仅依靠｜是做不到的吧。所以我在想能不能在 Web UI 中加上可视化的、更细致的筛选。面对某一番剧就可以设置为，排除 720P 或同时满足 XXX（名字）与 1080P 的资源。
> 
> 目前ab的排除规则是全局范围的, 这种情况需要 @EstrellaXD 提供针对单个番剧的筛选api, 然后我可以把筛选的正则做成模板式的填写以供使用.

这种情况正则表达式依旧可以解决啊，只需要在 qb 的 contain 规则里面改成 `xxx+1080P\+` 即可，不过确实对于一般用户而言门槛稍高，这个之后我会酌情考虑如何实现添加的。

**Comment by Rewrite0** [comment]
> > > 主要是上个季度遇到了这种情况：有个组提供 1080P 和 1080P+ 两种资源，它们的名字也只有这部分有区别。排除设置里又不能设置 1080P ，所以怎么单独保留这部番剧的 1080P+ 就成了问题。或许正则表达式可以解决，但是仅依靠｜是做不到的吧。所以我在想能不能在 Web UI 中加上可视化的、更细致的筛选。面对某一番剧就可以设置为，排除 720P 或同时满足 XXX（名字）与 1080P 的资源。
> > 
> > 
> > 目前ab的排除规则是全局范围的, 这种情况需要 @EstrellaXD 提供针对单个番剧的筛选api, 然后我可以把筛选的正则做成模板式的填写以供使用.
> 
> 这种情况正则表达式依旧可以解决啊，只需要在 qb 的 contain 规则里面改成 `xxx+1080P\+` 即可，不过确实对于一般用户而言门槛稍高，这个之后我会酌情考虑如何实现添加的。

如果可以针对单个番剧设置筛选自然更好, 否则我也只能在全局筛选里通过在正则中塞入指定番名来实现伪指定筛选了. 然而这种方式在做管理页的时候, 把这种伪指定的正则和全局正则区分开就比较掉头发了.

**Comment by EstrellaXD** [comment]
> > 这种情况正则表达式依旧可以解决啊，只需要在 qb 的 contain 规则里面改成 `xxx+1080P\+` 即可，不过确实对于一般用户而言门槛稍高，这个之后我会酌情考虑如何实现添加的。
> 
> 如果可以针对单个番剧设置筛选自然更好, 否则我也只能在全局筛选里通过在正则中塞入指定番名来实现伪指定筛选了. 然而这种方式在做管理页的时候, 把这种伪指定的正则和全局正则区分开就比较掉头发了.

可以针对单个番剧设置的，只需要调用 qb API 就行了

**Comment by Rewrite0** [comment]
> > > 这种情况正则表达式依旧可以解决啊，只需要在 qb 的 contain 规则里面改成 `xxx+1080P\+` 即可，不过确实对于一般用户而言门槛稍高，这个之后我会酌情考虑如何实现添加的。
> > 
> > 
> > 如果可以针对单个番剧设置筛选自然更好, 否则我也只能在全局筛选里通过在正则中塞入指定番名来实现伪指定筛选了. 然而这种方式在做管理页的时候, 把这种伪指定的正则和全局正则区分开就比较掉头发了.
> 
> 可以针对单个番剧设置的，只需要调用 qb API 就行了

挺好, ~~可以少掉头发了~~

**Comment by EstrellaXD** [comment]
已开放新 branch: 2.6.0 用于开发

**Comment by ljjwy168** [comment]
webui里的番剧管理内容多久刷新一次 今天取消了3个订阅但是几个小时了 番剧管理还是那么多番剧也不剔除取消订阅的

**Comment by Rewrite0** [comment]
> webui里的番剧管理内容多久刷新一次 今天取消了3个订阅但是几个小时了 番剧管理还是那么多番剧也不剔除取消订阅的

webui里的番剧管理内容其实是ab建立的番剧规则，取消mikan的rss订阅不会清除已有规则，虽然是有删除规则的api，但是有点问题，所以没有加上去， 你可以通过重置ab数据让ab重新添加规则。 （话说我好像忘记提这个api的问题了）

**Comment by EstrellaXD** [comment]
> webui里的番剧管理内容多久刷新一次 今天取消了3个订阅但是几个小时了 番剧管理还是那么多番剧也不剔除取消订阅的

这个不影响整体功能的，主要还是给大伙儿 debug 用

**Comment by lersh** [comment]
能否增加对未开播的番剧的订阅功能，并能看到播放日历？到了开播时间提醒主人去蜜柑上选择字幕组？
