### ISSUE TITLE
[错误报告]本季度16bit的感动会一直重复创建

### ISSUE THREAD

**Issue by InkSummer** [EstrellaXD/Auto_Bangumi#575]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.0

### 问题类型

WebUI

### 问题描述

16bit的感到会一直创建【的感动】的番剧，哪怕手动改成16bit的感动后续也会一直创建
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/16552853/f1290d88-0d8d-47d2-9340-4ac65dae865f)

**Comment by RinChanNOWWW** [comment]
这种问题的解决办法应该是什么？

**Comment by RinChanNOWWW** [comment]
看起来 #524 修复了这个问题。
