### ISSUE TITLE
希望作者大佬下个版本增加开启TMDB选项后，按照TMDB名字格式，带上年份，修改文件夹名字的功能

### ISSUE THREAD

**Issue by SCGabriel** [EstrellaXD/Auto_Bangumi#58]
> ./
> ├── 测不准的阿波连同学 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 处刑少女的生存之道 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 创之界限 (2021)
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   └── tvshow.nfo
> ├── 骸骨骑士大人异世界冒险中 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 黑岩射手：黎明降临 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 欢迎来到实力至上主义的教室 (2017)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   └── tvshow.nfo
> ├── 辉夜大小姐想让我告白：天才们的恋爱头脑战 (2019)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 03
> │   ├── season03-poster.jpg
> │   └── tvshow.nfo
> ├── 继母的拖油瓶是我的前女友 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 间谍过家家 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 街角魔族 (2019)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   └── tvshow.nfo
> ├── 金装的维尔梅 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 来自深渊 (2017)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   └── tvshow.nfo
> ├── 理科生坠入情网，故尝试证明。 (2020)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   └── tvshow.nfo
> ├── 联盟空军航空魔法音乐队 光辉魔女 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 恋爱游戏世界对路人角色很不友好 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 魔法使黎明期 (2022)
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 派对浪客诸葛孔明 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 平凡职业造就世界最强 (2019)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 00
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   ├── season-specials-poster.jpg
> │   └── tvshow.nfo
> ├── 蔷薇王的葬列 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   └── tvshow.nfo
> ├── 社畜小姐想被幽灵幼女治愈 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 式守同学不只可爱而已 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 相合之物 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 邪神与厨二病少女 (2018)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 03
> │   ├── season03-poster.jpg
> │   └── tvshow.nfo
> ├── 新·东京猫猫 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 异世界归来的舅舅 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 勇者辞职不干了 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   └── tvshow.nfo
> ├── 约会大作战 (2013)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 04
> │   ├── season04-poster.jpg
> │   └── tvshow.nfo
> ├── 在异世界迷宫开后宫 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 绽放的阿尔斯诺特利亚 (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 这个医师超麻烦 (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 指名！ (2022)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── landscape.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── 转生贤者的异世界生活～获得第二职业并成为世界最强～ (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   └── tvshow.nfo
> ├── Estab Life: Great Escape (2022)
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   └── tvshow.nfo
> ├── LoveLive! 虹咲学园学园偶像同好会 (2020)
> │   ├── clearlogo.png
> │   ├── fanart.jpg
> │   ├── poster.jpg
> │   ├── Season 01
> │   ├── season01-poster.jpg
> │   ├── Season 02
> │   ├── season02-poster.jpg
> │   └── tvshow.nfo
> └── RPG不动产 (2022)
>     ├── clearlogo.png
>     ├── fanart.jpg
>     ├── poster.jpg
>     ├── Season 01
>     ├── season01-poster.jpg
>     └── tvshow.nfo
> 

大致类似于这种目录结构，因为极少情况下，TMDB上有完全一样名字的剧集或者电影，只能靠年份来区分
这个问题是群里提过，issues发一下作为提醒

**Comment by EstrellaXD** [comment]
已经在 2.5.11 改进
