### ISSUE TITLE
本地部署过程没反应

### ISSUE THREAD

**Issue by dalaoshi777** [EstrellaXD/Auto_Bangumi#582]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.10

### 问题类型

其他问题

### 问题描述

截图一个为bash 一个是powershell
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/47414347/371012ed-ea27-4934-8320-b827bb0a3f6d)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/47414347/d6da65d4-5b4a-48e2-ad7d-79ae69484d67)

**Comment by EstrellaXD** [comment]
非程序bug，自行检查
