### ISSUE TITLE
[错误报告]在CDN下无法保存配置文件

### ISSUE THREAD

**Issue by ShanshanHY** [EstrellaXD/Auto_Bangumi#583]
### 确认

- [x] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

latest:3.1.10

### 问题类型

WebUI

### 问题描述

本人服务器在国外，使用cdn作为加速服务
在使用cdn套用webui时，出现无法保存配置文件的情况
查看网络信息后发现webui发起了PATCH请求，不被CDN正常转发，CDN直接返回400
![Screenshot_2023-10-17-00-53-45-221_com guoshi httpcanary](https://github.com/EstrellaXD/Auto_Bangumi/assets/29966961/ad2789d2-ed11-4e88-9282-905382eb2a56)

### 发生问题时系统日志

```bash
由于是cdn无法转发非POST/GET数据，因此程序并没有收到请求，也没有日志
```

**Comment by EstrellaXD** [comment]
自行调整代码

**Comment by ShanshanHY** [comment]
> 自行调整代码

如果我知道怎么解决就直接pr而不是在这issue了
况且pr了也不会同意吧，毕竟看您的样子压根就没打算当一个问题去处理
自行调整代码，但也同时失去了watchtower的自动更新，不是么
