### ISSUE TITLE
重命名添加高级功能

### ISSUE THREAD

**Issue by Siskin156** [EstrellaXD/Auto_Bangumi#585]
### 背景 or 问题

现在的重命名会把番剧的字幕清晰度和是否是bd的信息全部删除

### 目标 & 方案简述

建议提供 [Lilith-Raws] 86 - Eighty Six - 01 [Baha][WEB-DL][1080p][AVC AAC][CHT][MKV].mkv 改为 86 - Eighty Six.S01E01.Baha.WEB-DL.1080p.AVC AAC.CHT.MKV.mkv   的功能

**Comment by EstrellaXD** [comment]
#115
