### ISSUE TITLE
[错误报告] collect 单个番剧时，报错，并且番剧无法展示到bangumi list

### ISSUE THREAD

**Issue by ADKcodeXD** [EstrellaXD/Auto_Bangumi#586]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版镜像

### 问题类型

程序运行问题

### 问题描述
在collect单个番剧时 报错
然后在bangumi List里面没有展示出相对应的番剧
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/88375547/844e9ec1-6ddd-4122-b389-d980c817b86c)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/88375547/b65b1301-033a-4902-a7ba-f73554d281aa)
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/88375547/c113a155-c55d-4324-b47f-1e326e52d8ac)

### 发生问题时系统日志

2023-10-18 19:54:10 AutoBangumi  | [2023-10-18 19:54:10] INFO:     Collections of 16bit的感动 ANOTHER LAYER Season 1 completed.
2023-10-18 19:54:10 AutoBangumi  | /usr/lib/python3.11/site-packages/sqlmodel/orm/session.py:133: SAWarning: fully NULL primary key identity cannot load any object.  This condition may raise an error in a future release.
2023-10-18 19:54:10 AutoBangumi  |   return super().get(

_No response_

**Comment by shininome** [comment]
@ADKcodeXD 这时候就要去问下collect 和subscribe的区别了

**Comment by ADKcodeXD** [comment]
> @ADKcodeXD 这时候就要去问下collect 和subscribe的区别了

好吧，我以为这个类似于番剧管理，能将所有通过该程序下载好的番剧展示到这里。

**Comment by shininome** [comment]
@ADKcodeXD 好奇喵,哪里了解到AB的喵,这个主要还是用来追最新的动漫的喵

**Comment by ADKcodeXD** [comment]
> @ADKcodeXD 好奇喵,哪里了解到AB的喵,这个主要还是用来追最新的动漫的喵
之前瞎逛看到有人star了这个项目，最近比较闲就来尝试了一下hh 🤣
