### ISSUE TITLE
[RFC] 某些BDRip资源使用AutoBangumi下载并处理

### ISSUE THREAD

**Issue by AiharaMahiru** [EstrellaXD/Auto_Bangumi#587]
### 背景 or 问题

目前下载完结动漫都是在mikan等平台进行RSS订阅下载的，缺少很多优质资源

### 目标 & 方案简述

有些完结的动画资源例如
`[动漫国字幕组&VCB-Studio] 孤独摇滚！ / BOCCHI THE ROCK! / ぼっち・ざ・ろっく! 10-bit 1080p HEVC BDRip [Fin]`
等等，可以添加磁力链接进行下载、重命名，进而方便入库，让emby等平台刮削

**Comment by shininome** [comment]
@AiharaMahiru 那你遇到了什么问题呢
