### ISSUE TITLE
[功能请求]希望添加重复下载的集数集中到一个文件夹的功能

### ISSUE THREAD

**Issue by lux032** [EstrellaXD/Auto_Bangumi#59]
下载完成后剧集目录只保留单个集数的一个文件，多次下载的文件集中到一个文件夹里面。方便进行管理。保留优先级可以遵照格式和文件大小来进行规则筛选

**Comment by EstrellaXD** [comment]
是否直接删除老版本会更好，感觉需要手动整理反而比较麻烦

**Comment by lux032** [comment]
> 是否直接删除老版本会更好，感觉需要手动整理反而比较麻烦

出于需要做种的考虑 最好保留

**Comment by EstrellaXD** [comment]
> > 是否直接删除老版本会更好，感觉需要手动整理反而比较麻烦
> 
> 出于需要做种的考虑 最好保留

主要是放在同一个文件夹下可能会干扰到刮削，分开放到另一个目录整理起来也比较麻烦。BT 来说保种没有那么重要吧，这点还需要在讨论下。

**Comment by lux032** [comment]
> > > 是否直接删除老版本会更好，感觉需要手动整理反而比较麻烦
> > 
> > 
> > 出于需要做种的考虑 最好保留
> 
> 主要是放在同一个文件夹下可能会干扰到刮削，分开放到另一个目录整理起来也比较麻烦。BT 来说保种没有那么重要吧，这点还需要在讨论下。

个人认为公网bt还是有上传一定分享率的义务的，可以的话指定一个额外的文件夹是一个比较理想的方式。干扰刮削的话增加一级文件夹或者指定另外根目录的文档应该可以解决。

**Comment by EstrellaXD** [comment]
> > > > 是否直接删除老版本会更好，感觉需要手动整理反而比较麻烦
> > > 
> > > 
> > > 出于需要做种的考虑 最好保留
> > 
> > 
> > 主要是放在同一个文件夹下可能会干扰到刮削，分开放到另一个目录整理起来也比较麻烦。BT 来说保种没有那么重要吧，这点还需要在讨论下。
> 
> 个人认为公网bt还是有上传一定分享率的义务的，可以的话指定一个额外的文件夹是一个比较理想的方式。干扰刮削的话增加一级文件夹或者指定另外根目录的文档应该可以解决。

好的，我针对外部建立文件夹评估一下，最后可能还是会做成选项的模式
