### ISSUE TITLE
[Feature Request]针对单条或多条rss的独立筛选规则设置

### ISSUE THREAD

**Issue by Duuck-D** [EstrellaXD/Auto_Bangumi#593]
### 功能改进

有的字幕组只做繁体，有的制作简体，有的是两个一起做，只靠 “解析设置” 里全局共用一个排除规则的话，我无法适用全部的 rss。
希望能够像 qb 的 rss 下载一样，能够针对单条或者多条 rss 来配置独立的筛选规则。下载排除指定关键词和包含指定关键词后的结果

**Comment by EstrellaXD** [comment]
RTFM

**Comment by Duuck-D** [comment]
> RTFM

不好意思，是我眼瞎，重新看了下配置rss的地方就有
