### ISSUE TITLE
[错误报告]使用dokcer-compose设置为host模式之后，WebUI打不开

### ISSUE THREAD

**Issue by GauSyu** [EstrellaXD/Auto_Bangumi#594]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.10

### 问题类型

WebUI

### 问题描述

我安装网站上的docker-compose.yml模版配置，本身能正常访问WebUI. 
但是如果我把`network_mode: bridge`改成`network_mode: host`，就会发生WebUI无法访问的问题。
我想知道这是为什么。

系统环境： MacOS 12.7
Docker Desktop:  Engine: 24.0.6  Compose: v2.22.0-desktop.2 

注：我改成host是想使用Mac上本机安装的qBittorrent. 如果有bridge模式的配置办法也可以。

**Comment by EstrellaXD** [comment]
端口冲突。

**Comment by GauSyu** [comment]
> 端口冲突。

而且删掉
```
ports:
      - "7892:7892"
```
也还是不行。请问host模式应该怎么设置呢？

**Comment by EstrellaXD** [comment]
自行百度/谷歌。请不要把 ISSUE 板块当成免费 QA
