### ISSUE TITLE
希望可以支持Aria2的下载方式

### ISSUE THREAD

**Issue by FSJohn** [EstrellaXD/Auto_Bangumi#6]
可以提一个小小的建议吗？希望可以支持使用aria2来下载番剧。

**Comment by EstrellaXD** [comment]
> 可以提一个小小的建议吗？希望可以支持使用aria2来下载番剧。

在未来的 Roadmap 中，不过 Aria2 本身不支持 RSS 订阅，需要重写 AutoBangumi 的推送功能，所以预计不会很快更新

**Comment by i-iooi-i** [comment]
严重依赖Aria2下载的来求一下~

**Comment by EstrellaXD** [comment]
目前功能与 qb 深度绑定，暂时不考虑支持其他下载器
