### ISSUE TITLE
[Discussion] Issue问题反馈的模板的链接过期了

### ISSUE THREAD

**Issue by RimoChan** [EstrellaXD/Auto_Bangumi#603]
### 项目讨论

「Issue: 问题反馈」中的「我已经查阅了[排错流程](https://autobangumi.org/faq/%E6%8E%92%E9%94%99%E6%B5%81%E7%A8%8B.html)，确保提出的问题不在其中。」和「我已经查阅了[已知问题](https://autobangumi.org/faq/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)，并确认我的问题不在其中。」，它们的链接是错的……

**Comment by EstrellaXD** [comment]
已经修正
