### ISSUE TITLE
使用聚合方式订阅，链接用的是mikan.tv开头，但是补全的时候看日志自动使用mikan.me，被墙导致补全无法使用

### ISSUE THREAD

**Issue by huzilaoge** [EstrellaXD/Auto_Bangumi#612]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1

### 问题类型

WebUI

### 问题描述

使用聚合方式订阅，链接用的是mikan.tv开头，但是补全的时候看日志自动使用mikan.me，因为.me被墙导致补全无法使用，希望能自定义补全开头的网址或者有什么其他办法优化一下
订阅链接：
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/3351495/7b0fda55-e13b-4c6d-bc51-250b3e8fec78)
补全地址：
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/3351495/98379d58-ee55-4010-9e97-042062d4e127)

**Comment by EstrellaXD** [comment]
@huzilaoge 修改search_provider链接就行

**Comment by huzilaoge** [comment]
> @huzilaoge 修改search_provider链接就行

感谢大佬回复，是我仓促了没仔细看配置文件
