### ISSUE TITLE
[错误报告]Downloader页面为空

### ISSUE THREAD

**Issue by NaT5uK1** [EstrellaXD/Auto_Bangumi#613]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[排错流程](https://autobangumi.org/faq/排错流程.html)，确保提出的问题不在其中。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/常见问题.html)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.1.11

### 问题类型

WebUI

### 问题描述

问题：系统运行正常，qb下载正常，downloader页面为空
环境：
+ 浏览器：Microsoft Edge 119.0.2151.44
+ 部署方式：Synology Docker 独立部署 ab和qb
控制台报错：502

![屏幕截图 2023-11-06 012846](https://github.com/EstrellaXD/Auto_Bangumi/assets/33252881/f48e0a3e-6e2d-46af-9656-514c9e31aa3b)
![屏幕截图 2023-11-06 014016](https://github.com/EstrellaXD/Auto_Bangumi/assets/33252881/24988784-c711-41c2-9456-b44210a80a43)

**Comment by EstrellaXD** [comment]
cc @Rewrite0

**Comment by Rewrite0** [comment]
请提供 `downloader` 设置

**Comment by NaT5uK1** [comment]
> 请提供 `downloader` 设置

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/33252881/4ba9a08d-5099-4795-ab38-844586b03c75)

**Comment by Rewrite0** [comment]
> > 请提供 `downloader` 设置
> 
> ![image](https://user-images.githubusercontent.com/33252881/281071014-4ba9a08d-5099-4795-ab38-844586b03c75.png)

嵌套的qb web是需要能实际访问的地址，你这里是docker里的ip，所以浏览器无法访问，可以考虑把docker改成host模式用本机ip，或者等我想想其他法子

**Comment by NaT5uK1** [comment]
> > > 请提供 `downloader` 设置
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/33252881/281071014-4ba9a08d-5099-4795-ab38-844586b03c75.png)
> 
> 嵌套的qb web是需要能实际访问的地址，你这里是docker里的ip，所以浏览器无法访问，可以考虑把docker改成host模式用本机ip，或者等我想想其他法子

在qb和ab都是独立容器且为bridge模式下，下载器只需要填写宿主ip+映射端口就可以了，这里page/downloader拿的url就是宿主ip+映射端口，但是这样就会触发浏览器同源策略限制，一种解决方案为：
在App挂载到root之前，从状态管理库取到downloader的host url，更改Content-Security-Policy策略，将host url作为iframe标签的祖先。
示例：
```
app.config.globalProperties.$meta = {
  'http-equiv': {
    'Content-Security-Policy': `default-src 'self'; frame-ancestors 'self' ${host}`
  }  
}
```

**Comment by moesakura** [comment]
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/5019609/3f06b2b5-eda9-4725-bf98-de82eadf50e3)
可以在qbittorrent的webui选项中取消这两项

**Comment by viazure** [comment]
我的 qb 是安装在宿主机（Windows）上的，按照楼上的方法进入到了 qb 的登录界面，但登录按钮点击后没有跳转。最后通过勾选 qb 的 Web UI 「对 IP 子网白名单中的客户端跳过身份验证」，填入宿主机的 ip 段解决了此问题。暂不清楚问题缘由，留个言希望能帮到后面遇到相同问题的朋友吧。

**Comment by LoSiTeE** [comment]
> 我的 qb 是安装在宿主机（Windows）上的，按照楼上的方法进入到了 qb 的登录界面，但登录按钮点击后没有跳转。最后通过勾选 qb 的 Web UI 「对 IP 子网白名单中的客户端跳过身份验证」，填入宿主机的 ip 段解决了此问题。暂不清楚问题缘由，留个言希望能帮到后面遇到相同问题的朋友吧。

同样的问题。我也是必须填白名单才能显示webui，不然的话就一直在登录验证的界面上，输入用户名密码也无法进入qb的界面
