### ISSUE TITLE
[Feature Request] 增加启动失败后尝试重启的功能。

### ISSUE THREAD

**Issue by ZhaoGY-N** [EstrellaXD/Auto_Bangumi#617]
### 功能改进

由于qbittorrent启动比AutoBangumi慢，即使在配置qbittorrent的容器先启动，AutoBangumi也会发现Downloader不存在，所以希望增加启动失败后尝试重启的功能，在启动失败后间隔一定时间重启

**Comment by ZhangTianrong** [comment]
只是为了解决启动时的问题的话，目前可以先简单修改一下 entrypoint 为 `/bin/sh -c set -e; echo "Waiting for qBittorrent"; while ! nc -z <qbittorrent_addr> <qbittorrent_port>; do sleep 1; done; echo "qBittorrent is available"; /sbin/tini -g -- /entrypoint.sh`. 在 TrueNAS Scale 系统上改起来是挺方便的，其他 NAS 系统像 Unraid 貌似也很容易。

**Comment by EstrellaXD** [comment]
Repeat FR #597
