### ISSUE TITLE
[BUG]最新的2.5.15似乎存在添加rss下载规则和自动下载的bug

### ISSUE THREAD

**Issue by wdmywm3** [EstrellaXD/Auto_Bangumi#63]
具体表现：
启动容器后，能自动向qb添加rss订阅，但是无法添加rss下载规则，也无法自动开启下载，日志会一直显示retry，多次重装及重启都无法解决
最后通过滚回老版本暂时解决

因为我是第一次弄，时间正好介于2.5.15更新前后，中间重新pull了一次，结果莫名其妙就卡在了那里，还以为是哪里出问题了，足足折腾了一个晚上，终于在想是不是新版本bug
然后试了一下重新pull了2.5.14版本，立刻就可以重新添加了

**Comment by EstrellaXD** [comment]
已经在 6131e50f24c2a62a8674fa934d473f62253af554 中修复，请重新拉取最新版本
