### ISSUE TITLE
[Feature Request]支持直接解析磁力链接

### ISSUE THREAD

**Issue by AiharaMahiru** [EstrellaXD/Auto_Bangumi#639]
### 功能改进

非当季番剧或剧场版可能要下磁力合集，目前只能通过内置的搜索来添加？有没有什么好的解决方案，后面有空我也来pr。

**Comment by EstrellaXD** [comment]
磁力链接解析需要内置bittorrent库，会让整个程序变得过于臃肿，暂时不考虑。
非当季的可以直接添加番剧 RSS 链接地址来下载，剧场版暂不支持。
