### ISSUE TITLE
[Feature Request]希望添加消息推送功能

### ISSUE THREAD

**Issue by staringX** [EstrellaXD/Auto_Bangumi#64]
比如调用bark的api，提供对手机进行消息推送的选项，
因为字幕组更新时间往往不确定，这样番剧下载完成后可以第一时间知道，不用反复刷新查看媒体库

**Comment by EstrellaXD** [comment]
> 比如调用bark的api，提供对手机进行消息推送的选项，
> 因为字幕组更新时间往往不确定，这样番剧下载完成后可以第一时间知道，不用反复刷新查看媒体库

下个大版本更新会加上
