### ISSUE TITLE
[Feature Request] 同步重命名 NFO 文件

### ISSUE THREAD

**Issue by Robotxm** [EstrellaXD/Auto_Bangumi#644]
### 功能改进

某些情况下 AB 的重命名操作会在 Jellyfin 自动刮削完之后完成，这个时候重命名视频文件会让 Jellyfin 再生成一个新的 nfo 文件。能否添加功能，使得在检测到和视频文件重名的 nfo 文件时也能对其自动重命名？

**Comment by shininome** [comment]
@Robotxm qb里面让未完成的添加!qb

**Comment by EstrellaXD** [comment]
AB 不直接管理目录，这个功能比较难实现。
