### ISSUE TITLE
[RFC]希望能添加先下载到临时目录再复制到指定目录的功能

### ISSUE THREAD

**Issue by XiChenBaBa** [EstrellaXD/Auto_Bangumi#648]
### 背景 or 问题

服务器硬盘空间不够大，放不下多部番
qbit无法直接下载到rclone挂载的网盘目录

### 目标 & 方案简述

先下载到临时目录再复制进去
这样就能用下载到网盘了

**Comment by EstrellaXD** [comment]
AB 不管理硬盘
