### ISSUE TITLE
[BUG] 部分番剧RSS会新增两个订阅规则

### ISSUE THREAD

**Issue by Mabinogi-Cichol** [EstrellaXD/Auto_Bangumi#65]
比如OVERLORD这种有多季度的，RSS会生成两种不同的规则重复下载。
![image](https://user-images.githubusercontent.com/52227273/180613253-8ec310de-915b-4e12-97fe-2f41492e0608.png)
![image](https://user-images.githubusercontent.com/52227273/180613270-02309d84-f294-473e-814f-bac449854c04.png)
![image](https://user-images.githubusercontent.com/52227273/180613286-c56413a1-f5a1-4360-8f7b-865c362035da.png)

**Comment by EstrellaXD** [comment]
理论上不应该，版本是最新版本么。可以用 API 导出一份 data 看看么。
```bash
curl host:7892/api/v1/data
```

**Comment by nagori-yuki** [comment]
为了评论特意注册了账号，因为有一个问题类似，故评论在这个issue中了
首先说下我的使用场景，我每部新番会同时加入两个字幕组但不会去使用更名，一个保证更新速度的字幕组or搬运组，一个保证翻译质量/压制质量的字幕组，个人习惯。

![1](https://user-images.githubusercontent.com/109912052/180654223-859c48eb-99b3-471b-9391-1cb37f930971.PNG)
问题一
我今天刚更新2.5.16版本，图一中所有罗马音标题的规则均为新加入，如图中红框中存在重复规则。
是否为我添加多字幕组原因？所有重复的规则中，除了overlord，RSS匹配的内容其实不一样。

问题二
还是如图一，所有中文规则名均是在2.5.14版本中加入，更新2.5.16后又加入了罗马音的规则名，下载地址一样为罗马音文件夹。
请问这个规则名的匹配原则是什么？因为每次看到有版本更新我都会第一时间更新，在2.5.14版本之前每次更新其实也多次出现同部片子反复添加不同译名的规则名这样反复横跳，不过记录重置后都已清理。这样反复更改其实蛮头疼。。。特别是下载位置改变了
PS. 我的配置自始至终没有变过的

问题三
如图二，这部片子的下载规则反复在加入qb。我在qb中删除了它，它在加入；我没在qb删除它，日志中显示它还是在反复加入。。
![2](https://user-images.githubusercontent.com/109912052/180655328-bef086ed-2bb4-4a14-95aa-9ea731a7bcca.PNG)

如果是个人原因导致的以上问题，那先表示抱歉， 除了qb的使用，其他各方面都是新手。

**Comment by EstrellaXD** [comment]
> 问题一 我今天刚更新2.5.16版本，图一中所有罗马音标题的规则均为新加入，如图中红框中存在重复规则。 是否为我添加多字幕组原因？所有重复的规则中，除了overlord，RSS匹配的内容其实不一样。

这个是因为字幕组明明 + AB 解析的问题，从图上看似乎一个字幕组使用了长命名，一个是短命名，所以 AB 以长命名的规则检测短命名失败使得添加了两组。可以看一下里面匹配的内容，选取一个保留。但是你这样的话有可能会造成该名失败，生成重复文件夹。

> 问题二 还是如图一，所有中文规则名均是在2.5.14版本中加入，更新2.5.16后又加入了罗马音的规则名，下载地址一样为罗马音文件夹。 请问这个规则名的匹配原则是什么？因为每次看到有版本更新我都会第一时间更新，在2.5.14版本之前每次更新其实也多次出现同部片子反复添加不同译名的规则名这样反复横跳，不过记录重置后都已清理。这样反复更改其实蛮头疼。。。特别是下载位置改变了 PS. 我的配置自始至终没有变过的

2.5.14 版本采用了 中文解析，但是因为bug 16调整回英文为主。如果要确定语言，请设置 `AB_LANGUAGE`

> 问题三 如图二，这部片子的下载规则反复在加入qb。我在qb中删除了它，它在加入；我没在qb删除它，日志中显示它还是在反复加入。。

看起来是解析器出现了 bug 请去 #41 反馈

**Comment by nagori-yuki** [comment]
> 这个是因为字幕组明明 + AB 解析的问题，从图上看似乎一个字幕组使用了长命名，一个是短命名，所以 AB 以长命名的规则检测短命名失败使得添加了两组。可以看一下里面匹配的内容，选取一个保留。但是你这样的话有可能会造成该名失败，生成重复文件夹。

是的，2.5.14之前使用时也遇到过这个问题，我都是手动改的，2.5.14中文规则后倒是没有了这个问题。当然后面能解决是最好~
但Overlord这部，只是大小写的区别，RSS匹配的内容也是完全一致的。之前的版本其实出现过一次加入三个规则的情况，还有一个是去掉了希腊数字IV。
重命名功能我没有在使用，pt党多年养成的不改文件名的习惯。用这个项目我只是为了让自己省点心，不用自己一个个去qb写。

>  2.5.14 版本采用了 中文解析，但是因为bug 16调整回英文为主。如果要确定语言，请设置 `AB_LANGUAGE`

这一项我一直有设置的，并没有起到作用呀。如下图，我的版本是2.5.18
我自己是习惯罗马音的，但是“舍友”不习惯罢了。
如果能选择用中文那是最好的~~
![6](https://user-images.githubusercontent.com/109912052/180774029-b7a1683d-870d-4878-a5a0-f67d48948571.PNG)

> 看起来是解析器出现了 bug 请去 #41 反馈

已反馈

**Comment by EstrellaXD** [comment]
> 是的，2.5.14之前使用时也遇到过这个问题，我都是手动改的，2.5.14中文规则后倒是没有了这个问题。当然后面能解决是最好~ 但Overlord这部，只是大小写的区别，RSS匹配的内容也是完全一致的。之前的版本其实出现过一次加入三个规则的情况，还有一个是去掉了希腊数字IV。 重命名功能我没有在使用，pt党多年养成的不改文件名的习惯。用这个项目我只是为了让自己省点心，不用自己一个个去qb写。

如果是大小写问题哪我明白原因了，不过会在大版本修复。
 
> 这一项我一直有设置的，并没有起到作用呀。如下图，我的版本是2.5.18 我自己是习惯罗马音的，但是“舍友”不习惯罢了。 如果能选择用中文那是最好的~~ 

已经确认是 bug，下个版本会修复。

**Comment by EstrellaXD** [comment]
过长时间未反馈，关闭issue
