### ISSUE TITLE
[Discussion] 如何对已经下载好的番剧进行整理?

### ISSUE THREAD

**Issue by moesakura** [EstrellaXD/Auto_Bangumi#656]
### 项目讨论

1.除了正在更新的番剧，有一些番剧是已经下载好的，可以使用本项目进行文件整理(包括重命名和刮削)吗?
2.本项目能将刮削好的数据生成nfo文件吗？

**Comment by shininome** [comment]
@moesakura 牡蛎~看不了文件

**Comment by moesakura** [comment]
> @moesakura 牡蛎~看不了文件

可以转需求吗，这个功能还是有一定实用性的

**Comment by Rewrite0** [comment]
@moesakura ab不参与文件管理，刮削请交给媒体服务器

**Comment by moesakura** [comment]
> @moesakura ab不参与文件管理，刮削请交给媒体服务器

目前从我的角度看来，对于订阅RSS的内容 ab是有做文件整理的

抛开刮削的话 能否提供统一的文件整理方式

因为现在一部分数据是 ab的文件格式 另一部分是我自己下载的

不统一有点难受

**Comment by Rewrite0** [comment]
@moesakura 重命名是借助qb的api完成的，ab没有介入文件管理
ab毕竟是用来追新的，所以你可以单独提供一个目录给ab，以便和你自己的媒体库区分开

**Comment by moesakura** [comment]
> @moesakura 重命名是借助qb的api完成的，ab没有介入文件管理 ab毕竟是用来追新的，所以你可以单独提供一个目录给ab，以便和你自己的媒体库区分开

是用的https://github.com/Abcuders/AutoAnimeMv 这个项目做重命名吗?(因为我看目录结构和用法差不多)
