### ISSUE TITLE
[错误报告]Mikan标题变更导致番剧没有正常下载

### ISSUE THREAD

**Issue by aowubulao** [EstrellaXD/Auto_Bangumi#672]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.11

### 问题类型

程序运行问题

### 问题描述

出现问题的rss订阅：https://mikanime.tv/RSS/Bangumi?bangumiId=3265&subgroupid=583

我自己设置的official_title为：梦想成为魔法少女。

番剧添加时，会解析一个title_raw和official_title，但是在bangumi.py 120:

```python
if match_data.title_raw in torrent.name:
```

仅会添加名字中存在title_raw的种子。在上述rss url中，title发生了变化：

```
[ANi] 憧憬成为魔法少女 [年龄限制版] - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]
[ANi] Mahou Shoujo ni Akogarete / 梦想成为魔法少女 [年龄限制版] - 03 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]
```

由憧憬成为魔法少女->梦想成为魔法少女，导致最新的一话没有正常下载。

是否可以将official_title也作为一个判断条件或者添加一个高级功能允许用户修改部分配置以规避这类问题？

**Comment by EstrellaXD** [comment]
这个是字幕组规范问题，AB 没有义务修正，请去给字幕组提意见。
