### ISSUE TITLE
[Feature Request] 是否会添加对萌番组的支持？

### ISSUE THREAD

**Issue by fwder** [EstrellaXD/Auto_Bangumi#68]
AutoBangumi 在之后的版本中会添加对 [萌番组](https://bangumi.moe/) 的支持嘛？

**Comment by EstrellaXD** [comment]
看起来和动漫花园一样，都需要自己在网站上建立过滤器。现有的 API 可以满足，但是相比蜜柑计划来说我觉得操作还是过于繁琐了

**Comment by fwder** [comment]
感谢回答.
