### ISSUE TITLE
[Feature Request]  希望添加本地内容扫描

### ISSUE THREAD

**Issue by starlayer** [EstrellaXD/Auto_Bangumi#686]
### 功能改进

类似的提案：#660
因为某些原因之前电脑重装了AB的数据没了，但已经下好的番还在硬盘里没事，在重新添加追番时会把前面已经下过的部分都再下回来一次，需要手动删除

**Comment by Ding-Kyoma** [comment]
用Docker-cli 部署，可以将AB的数据储存起来

**Comment by EstrellaXD** [comment]
自行备份
