### ISSUE TITLE
[Feature Request]希望新增打包一个armv8的docker

### ISSUE THREAD

**Issue by czlizy** [EstrellaXD/Auto_Bangumi#69]
古董外贸盒子，coreelec系统，使用以下指令安装auto_bangumi
`docker pull estrellaxd/auto_bangumi`
安装失败，提示信息如下
`no matching manifest for linux/arm/v8 in the manifest list entries`

希望下个版本能打包个armv8版的，感谢

**Comment by EstrellaXD** [comment]
已经在 2.5.20 中解决了 lxml 冲突问题，请重新拉取。如果有问题请及时反馈
