### ISSUE TITLE
[BUG]2.5.20版本RSS xml解析问题

### ISSUE THREAD

**Issue by czlizy** [EstrellaXD/Auto_Bangumi#70]
新版本2.5.20的docker支持armv7，可以部署了，感谢
解析蜜柑RSS时日志显示
`Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?`
无法解析RSS内容，直接在docker内运行`pip install lxml`无法安装lxml
后来运行`apt-get install libxml2-dev` `apt-get install libxslt1-dev` `apt-get install libz-dev` `apt-get install gcc`后安装lxml成功，之后RSS就可以正常解析了

**Comment by EstrellaXD** [comment]
> 新版本2.5.20的docker支持armv7，可以部署了，感谢
> 解析蜜柑RSS时日志显示
> `Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?`
> 无法解析RSS内容，直接在docker内运行`pip install lxml`无法安装lxml
> 后来运行`apt-get install libxml2-dev` `apt-get install libxslt1-dev` `apt-get install libz-dev` `apt-get install gcc`后安装lxml成功，之后RSS就可以正常解析了

感谢 DEBUG，下个版本会修复

**Comment by EstrellaXD** [comment]
经过测试，GitHub Action 无法正常在 ARMv7 中安装 lxml，可能后续还是需要自己安装

**Comment by EstrellaXD** [comment]
Update 修复了，后续版本也无需自己安装 lxml
