### ISSUE TITLE
番剧被重复添加

### ISSUE THREAD

**Issue by Misaka-Aki** [EstrellaXD/Auto_Bangumi#709]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.12

### 问题类型

程序运行问题

### 问题描述

通过搜索mikan添加的rss链接，番剧被重复添加

<img width="952" alt="屏幕截图 2024-03-02 234538" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/66006338/46a67db1-eeed-40a8-876a-897b69296394">
<img width="930" alt="屏幕截图 2024-03-02 234801" src="https://github.com/EstrellaXD/Auto_Bangumi/assets/66006338/8395517e-74e2-4ab7-9fc5-05e1e623d903">

### 发生问题时系统日志

```bash
[2024-03-02 23:45:11] INFO:     Config loaded
[2024-03-02 23:45:11] INFO:     Program running.
[2024-03-02 23:45:16] INFO:     [RSS] New bangumi founded: 【我推的孩子】
[2024-03-02 23:45:18] INFO:     [RSS] New bangumi founded: 【我推的孩子】
```

**Comment by EstrellaXD** [comment]
字幕组问题
