### ISSUE TITLE
[BUG]   历史番剧功能部分生效

### ISSUE THREAD

**Issue by ljjwy168** [EstrellaXD/Auto_Bangumi#71]
已经把AB_EP_COMPLETE选项设置为True 但是有的剧只能下当前最新 有的只能从第一集开始下
看了下正规则也没包含关键字

**Comment by EstrellaXD** [comment]
请提供 LOG 以及更具体的信息

**Comment by ljjwy168** [comment]
> 请提供LOG 以及更具体的信息

仔细看了下教程 应该是我自己问题 订阅的动画是21年的了
