### ISSUE TITLE
[Feature Request]希望webui的RSS管理可以完整显示名称和URL

### ISSUE THREAD

**Issue by VCE1** [EstrellaXD/Auto_Bangumi#715]
### 功能改进

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/79588027/5a4b13b9-0304-45a8-8692-4c9847835755)

**Comment by Rewrite0** [comment]
https://github.com/EstrellaXD/Auto_Bangumi/commit/b3f6255768956174f18eac375bebd59f5c56f925 等待下个版本更新
