### ISSUE TITLE
[错误报告]同一个剧集（第一季跟第二季）只能生成一个海报墙。

### ISSUE THREAD

**Issue by abo2029** [EstrellaXD/Auto_Bangumi#720]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.12

### 问题类型

WebUI

### 问题描述

RSS添加《XXXX 第一季》解析识别后能生成海报墙并下载文件，然后再《XXXX 第二季》的RSS后，能获取下载文件，但无法生成第二季的海报墙。只能看到第一季的海报墙。

尝试处理方式：
在Wiki查找处理方式（失败）
在ISSUE查找处理方式（失败）
互换两季的RSS添加顺序（失败）只能生成第一个添加的RSS的海报墙。
尝试在RSS管理下 选择 Collect 方式（失败）
尝试在RSS管理下 选择 Subscribe 方式（失败）

疑问：
以上情况是正常的吗？是设计就是这样的，还是属于异常？我是打算用来管理所有剧集的。

还有一个地方，就是解析番剧里面有一个默认的排除项  \d+-\d+ 写成  \d+-\d 了

**Comment by abo2029** [comment]
![20240320_150254](https://github.com/EstrellaXD/Auto_Bangumi/assets/23325792/470d153d-ad2d-4296-9c26-d3e16a3dff7a)
设置图

**Comment by abo2029** [comment]
> @abo2029 嘛，是这样的，下载多季会变得不幸运的

那就是每一部更新完就得删除吗？

**Comment by shininome** [comment]
因为主要还是用来追新的,所有有了第二季后第一季就牡蛎~

**Comment by abo2029** [comment]
> 因为主要还是用来追新的,所有有了第二季后第一季就牡蛎~

好的，谢谢解答，看来只能用来管理追新的番剧，没办法做到管理旧番剧。
使用上感觉还是有点奇怪，如果是追新的话，能否实现，当添加第二季的时候自动删除第一季的规则，并保留第一季的下载文件。
不然我添加第二季了，但还是保留了第一季的海报墙，有点别扭，要删了重新添加第二季。
