### ISSUE TITLE
[错误报告]番剧补全功能失效，只能下载最新一集，然后设置里开关我也是打开的【已解决，重启几次后等一段时间就自动下载了】

### ISSUE THREAD

**Issue by 52Lolita** [EstrellaXD/Auto_Bangumi#722]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1

### 问题类型

其他问题

### 问题描述

番剧补全功能失效，只能下载最新一集，然后设置里开关我也是打开的

### 发生问题时系统日志

```bash
没有错误日志
```

**Comment by xx1847289725** [comment]
而且还重启了好几次，难受

**Comment by crazyhonor** [comment]
我也是这个问题，请问你是挂了代理吗？

**Comment by 52Lolita** [comment]
> 我也是这个问题，请问你是挂了代理吗？

最好挂代理，有个api访问不到
