### ISSUE TITLE
[Feature Request]老哥后期能不能加入订阅老番也能补全剧集，比如现在2024年订阅2020年的番剧，然后自动补全

### ISSUE THREAD

**Issue by 52Lolita** [EstrellaXD/Auto_Bangumi#723]
### 功能改进

老哥后期能不能加入订阅老番也能补全剧集，比如现在2024年订阅2020年的番剧，然后自动补全

**Comment by Slinet6056** [comment]
老番添加 RSS 的时候选 Collect 就好了啊

**Comment by 52Lolita** [comment]
> 老番添加 RSS 的时候选 Collect 就好了啊

主要是老番订阅后不会出现在总的订阅链接里，会无法导致Collect
比如说：https://mikanime.tv/RSS/MyBangumi?token=fmseC9这个订阅网址，返回的是订阅的最近更新的番剧，但是老番很早就更新完了，然后就获取不了老番的数据，

**Comment by Rewrite0** [comment]
@52Lolita 找单独的番剧RSS
