### ISSUE TITLE
[BUG]: 容器启动时提示 JSONDecodeError

### ISSUE THREAD

**Issue by Gtyrande** [EstrellaXD/Auto_Bangumi#75]
### 当前程序版本

2.5.22 2.5.16

### 问题类型

RSS 解析器

### 问题描述

![image](https://user-images.githubusercontent.com/11093614/181905510-e17a856e-7b28-4277-838d-27f146d0dfbf.png)
如上图所示，启动后 logs 显示 JSONDecodeError 这一段，今天升级 2.5.22 问题依旧

目前尚有一两部番没有创建 RSS 自动下载规则（大部分创建好了），新下载的动画没有自动改名，启用自动补全也是部分生效，不知道是否和这个 JSON 报错有关

烦请协助

### 发生问题时系统日志

```shell
Traceback (most recent call last):
  File "/src/app.py", line 111, in <module>
    run()
  File "/src/app.py", line 105, in run
    bangumi_data = load_data_file()
  File "/src/app.py", line 33, in load_data_file
    bangumi_data = json_config.load(info_path)
  File "/src/utils/json_config.py", line 7, in load
    return json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by EstrellaXD** [comment]
是否绑定了 config 到外部，需要提供一下 bangumi.json 文件做进一步排查
谢谢

**Comment by Gtyrande** [comment]
> 

感谢回复，有绑定出去 
![image](https://user-images.githubusercontent.com/11093614/181908484-1f18c493-50d2-43f0-8a2c-954ff8911ca7.png)
我看了下 bangumi.json 是空的……

**Comment by EstrellaXD** [comment]
目前没有其他人出现过这个问题。
可以先尝试用
```json
{
    "rss_link":  "YOUR RSS LINK",
    "data_version": 4.0,
    "bangumi_info": []
}
```
写入 `bangumi.json` 文件再重新运行一下。
顺便问一下运行的平台是 x86-64 还是 ARM64

**Comment by Gtyrande** [comment]
我试试看手动写入
应该是 X86-64，运行在 i7-7700HQ 上面的 UNRAID

**Comment by Gtyrande** [comment]
受你启发，我删掉 bangumi.json 再重启 docker 它运行正常了
有几个新的小问题如下，需要重开 ISSUE 的话我另起一个

- 骨王的识别有问题
![image](https://user-images.githubusercontent.com/11093614/181914840-03ee2986-7bcd-40fa-87fd-23ea2222f9e0.png)

- 来自深渊识别为第一季（创建的 qBit 规则中路径是 Season 1），我手动修改为 Season 2 了不知道会不会有隐患

- RSS 里有地下城，也有自动规则，但没有触发下载，是不是等下周更新第二集它会把上一集也自动补上？
![image](https://user-images.githubusercontent.com/11093614/181914918-fafcda90-ede8-456c-b717-e49bba546848.png)

**Comment by EstrellaXD** [comment]
设计的时候就考虑过由于解析器失败的因素。
- 在 QB 里面手动修改 AB 会识别到，后续要不用额外更改，之后识别错误直接手动修改即可，没有隐患。
- 没有触发下载感觉是 QB 的问题，检查一下 RSS 里面是不是读取过了。也可以删除 RSS 再重新添加。
---
解析器问题可以另开 issue
