### ISSUE TITLE
[错误报告]添加订阅提示下载失败

### ISSUE THREAD

**Issue by JeanneAlt** [EstrellaXD/Auto_Bangumi#757]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.13

### 问题类型

程序运行问题

### 问题描述

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/42638734/4e79d429-ce02-4030-a95c-fecb95f58633)
添加订阅时提示下载失败，日志中没有任何报错，试了几个其他的RSS也是下载失败
https://[mikanani.me/RSS/Bangumi?bangumiId=3298&subgroupid=370](https://mikanani.me/RSS/Bangumi?bangumiId=3298&subgroupid=370)

**Comment by abigailsothoth0** [comment]
我也是，并且我发现只有LoliHouse的订阅会失败
