### ISSUE TITLE
[BUG]: 部分番剧自动补全未生效

### ISSUE THREAD

**Issue by Gtyrande** [EstrellaXD/Auto_Bangumi#77]
### 当前程序版本

2.5.22

### 问题类型

RSS 解析器

### 问题描述

截图的这个异世界舅舅，自动下载、改名好了 04 话，但是没有自动补全前面的
（大部分的自动补全是成功的）

包括 RSS 中有的第 03 话也没有下载（04 是 AB 运行后出的）

![image](https://user-images.githubusercontent.com/11093614/181915574-02b6ef69-2446-468f-886d-16b6ec3c0bb3.png)
![image](https://user-images.githubusercontent.com/11093614/181915575-474115d8-12fc-4545-9e49-64e3ea6de803.png)

有什么手动触发自动补全的方法吗

**Comment by EstrellaXD** [comment]
目前没有，请提供一下 `bangumi.json` 或者使用 API 获取一下 data 数据以便分析

**Comment by Gtyrande** [comment]
[bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9229097/bangumi.zip)

PFA

**异世界舅舅** 我通过 取消订阅 - 重启 docker - 重新订阅 的方式，他重新下载补全了
翻了一下还有一个 **在异世界迷宫开后宫 (2022)** 有类似的问题

**Comment by ljjwy168** [comment]
> [bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9229097/bangumi.zip)
> 
> PFA
> 
> **异世界舅舅** 我通过 取消订阅 - 重启 docker - 重新订阅 的方式，他重新下载补全了 翻了一下还有一个 **在异世界迷宫开后宫 (2022)** 有类似的问题

和我一样 我下传颂之物也是只下3456 不下12 很蛋疼

**Comment by EstrellaXD** [comment]
> > [bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9229097/bangumi.zip)
> > PFA
> > **异世界舅舅** 我通过 取消订阅 - 重启 docker - 重新订阅 的方式，他重新下载补全了 翻了一下还有一个 **在异世界迷宫开后宫 (2022)** 有类似的问题
> 
> 和我一样 我下传颂之物也是只下3456 不下12 很蛋疼

看一下 12 的分辨率是不是后 3456 不一样

**Comment by ljjwy168** [comment]
> > > [bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9229097/bangumi.zip)
> > > PFA
> > > **异世界舅舅** 我通过 取消订阅 - 重启 docker - 重新订阅 的方式，他重新下载补全了 翻了一下还有一个 **在异世界迷宫开后宫 (2022)** 有类似的问题
> > 
> > 
> > 和我一样 我下传颂之物也是只下3456 不下12 很蛋疼
> 
> 看一下 12 的分辨率是不是和 3456 不一样

都是1080 区别是1 2是联播 没发现屏蔽关键字

**Comment by EstrellaXD** [comment]
> > > > [bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9229097/bangumi.zip)
> > > > PFA
> > > > **异世界舅舅** 我通过 取消订阅 - 重启 docker - 重新订阅 的方式，他重新下载补全了 翻了一下还有一个 **在异世界迷宫开后宫 (2022)** 有类似的问题
> > > 
> > > 
> > > 和我一样 我下传颂之物也是只下3456 不下12 很蛋疼
> > 
> > 
> > 看一下 12 的分辨率是不是和 3456 不一样
> 
> 都是1080 区别是1 2是联播 没发现屏蔽关键字

好的我知道问题出在哪里了，这个还得再看怎么修正

**Comment by ljjwy168** [comment]
> > > > > [bangumi.zip](https://github.com/EstrellaXD/Auto_Bangumi/files/9229097/bangumi.zip)
> > > > > PFA
> > > > > **异世界舅舅** 我通过 取消订阅 - 重启 docker - 重新订阅 的方式，他重新下载补全了 翻了一下还有一个 **在异世界迷宫开后宫 (2022)** 有类似的问题
> > > > 
> > > > 
> > > > 和我一样 我下传颂之物也是只下3456 不下12 很蛋疼
> > > 
> > > 
> > > 看一下 12 的分辨率是不是和 3456 不一样
> > 
> > 
> > 都是1080 区别是1 2是联播 没发现屏蔽关键字
> 
> 好的我知道问题出在哪里了，这个还得再看怎么修正

比如开了重命名后 以前下过的会全部重新下 
如果订阅2021年前的也不能下
我这个1~2不能下 标题名是 【澄空学园&动漫国字幕组】★07月新番[传颂之物 二人的白皇][01-02][1080P][简体][MP4] [650.2MB]

**Comment by EstrellaXD** [comment]
> 比如开了重命名后 以前下过的会全部重新下 

这个问题不应该发生，是否删掉原本种子了？如果没有在重命名之后删掉种子那么请单开一个issue具体的描述一下问题
