### ISSUE TITLE
[Feature Request] RSS能否选择匹配而不是排除

### ISSUE THREAD

**Issue by terloo** [EstrellaXD/Auto_Bangumi#780]
### 功能改进

RSS规则编辑页面，通过排除没法筛选掉下图的第二个，能否增加一个匹配（而不是排除）用正则或者关键字进行匹配
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/49900070/8a8b6436-e4d4-4849-80e9-cfdb1952643b)

**Comment by KotaHv** [comment]
\[1080p]
