### ISSUE TITLE
[错误报告]获取RSS后，没有跳出番剧订阅筛选窗口

### ISSUE THREAD

**Issue by UCHIHAHA103** [EstrellaXD/Auto_Bangumi#781]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

Version 3.1.14

### 问题类型

WebUI

### 问题描述

新增RSS链接后，会直接开始下载，没有跳出订阅筛选的窗口。下面是我在别人的教程上看到的，我这边看不到这个窗口。

![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/61904674/cf18b8ef-4b21-427a-adea-6a071a9ae631)

产生的结果是这样的：我在全局筛选中剔除了720的资源，但是某些老番只有720p，我订阅rss后，该番剧会自动应用全局规则，把720的资源剔除掉，导致什么资源都下载不到。
![image](https://github.com/EstrellaXD/Auto_Bangumi/assets/61904674/4650f3d1-53dd-4ad8-8703-47b95eb95b1b)
![野良神2](https://github.com/EstrellaXD/Auto_Bangumi/assets/61904674/0033f712-6ecf-4c1a-a364-c05332d7ba4e)
我试过等番剧创建好后，手动把720的规则删掉，但是AB没有应用新规则，依然下载不到资源（修改规则后，无法应用新规则，不清楚这是bug还是我的操作不当？）
![recording](https://github.com/EstrellaXD/Auto_Bangumi/assets/61904674/1677e14a-1437-46b9-9807-004a06563332)

订阅链接：https://mikanani.me/RSS/Bangumi?bangumiId=257&subgroupid=92

**Comment by KotaHv** [comment]
第一个是因为你点了聚合RSS，当订阅番剧合集时不要点聚合。
