### ISSUE TITLE
[错误报告]RSS订阅为国内域名(mikanime.tv)，但torrent获取仍为mikanime.me，以致出现网络连接失败问题

### ISSUE THREAD

**Issue by TedzcTan** [EstrellaXD/Auto_Bangumi#804]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.13

### 问题类型

程序运行问题

### 问题描述

RSS订阅为国内域名(mikanime.tv)，但torrent获取仍为mikanime.me，以致出现网络连接失败问题

### 发生问题时系统日志

```bash
[2024-07-13 22:37:27]
INFO
Start collecting 【我推的孩子】 Season 1...
[2024-07-13 22:38:07]
ERROR
ERROR [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=桜都字幕组+Oshi+no+Ko++2024++简日内嵌+1080p, Please check your network settings
[2024-07-13 22:38:07]
WARNING
[Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=桜都字幕组+Oshi+no+Ko++2024++简日内嵌+1080p
[2024-07-13 22:38:07]
WARNING
Already collected 【我推的孩子】 Season 1.
[2024-07-13 22:38:07]
INFO
Start collecting 前辈是男孩子 Season 1...
[2024-07-13 22:38:47]
ERROR
ERROR [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=MingY+Senpai+wa+Otokonoko+简繁日内封+1080p, Please check your network settings
[2024-07-13 22:38:47]
WARNING
[Network] Failed to get torrents: https://mikanani.me/RSS/Search?searchstr=MingY+Senpai+wa+Otokonoko+简繁日内封+1080p
[2024-07-13 22:38:47]
WARNING
Already collected 前辈是男孩子 Season 1.
[2024-07-13 22:38:47]
INFO
Start collecting 黄昏光影 Season 1...
[2024-07-13 22:39:28]
ERROR
ERROR [Network] Unable to connect to https://mikanani.me/RSS/Search?searchstr=ANi+Tasogare+Out+Focus+CHT+Baha+1080P, Please check your network settings
```

**Comment by jqtmviyu** [comment]
这是mikan站长设置的, 检测到国外ip就给mikanani.me, 国内就给mikanime.tv

直接在服务器上curl 订阅的rss地址就能看到了.

**Comment by ProudBenzene** [comment]
在设置为番剧补全时，即便订阅中填写的是.tv域名，在尝试获取整季时，进行检索使用的链接依然是.me链接，这应该是autobangumi的bug吧

**Comment by MWTJC** [comment]
同上，客观确有此事，添加rss源用的是`.tv`域名，设置番剧补全为开时，日志显示“种子获取失败”，且用的是`.me`结尾域名，

经调试认为，番剧补全的行为与添加rss源的域名文本无关，而是更类似于[搜索功能](https://www.autobangumi.org/feature/search.html)的行为，会以[config/search_provider.json](https://www.autobangumi.org/feature/search.html)中的mikanani源作为拼接搜索url的前缀，然后使用这个拼接url进行补全搜索，这里面写的就是`.me`结尾域名，造成番剧补全就不会去`.tv`那边搜。

但是问题来了，我尝试直接把拼接搜索url中的域名从me改成tv，却发现更改后的url会跳转两次，并不返回搜索结果xml内容，autobangumi没法取得搜索结果，所以这个问题成死路了。

综上，解决问题只用修改[config/search_provider.json](https://www.autobangumi.org/feature/search.html)即可，但`mikanani的tv域名`那边本身也有问题，改了之后也用不了番剧补全，死路

**Comment by MWTJC** [comment]
是我眼瞎了，`mikanani.me`与`mikanime.tv`，域名第一段都不一样，在[config/search_provider.json](https://www.autobangumi.org/feature/search.html)里面改正后，正常解决

**Comment by TedzcTan** [comment]
> 是我眼瞎了，`mikanani.me`与`mikanime.tv`，域名第一段都不一样，在[config/search_provider.json](https://www.autobangumi.org/feature/search.html)里面改正后，正常解决

这个管用，感谢
