### ISSUE TITLE
[重命名错误] 标题带 话話集 的在第二次触发重命名会出错

### ISSUE THREAD

**Issue by jqtmviyu** [EstrellaXD/Auto_Bangumi#805]
### 当前程序版本

3.1.13

### 重命名设置

advance

### 种子名称

[ANi] 不時輕聲地以俄語遮羞的鄰座艾莉同學 - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4

### 文件路径

/不时用俄语小声说真心话的邻桌艾莉同学/Season 1/

### 错误命名

不时用俄语小声说真心话的邻桌艾莉同学 S01E02.mp4

### 发生问题时系统日志

```shell
Cannot parse 不时用俄语小声说真心话的邻桌艾莉同学 S01E02.mp4 with error invalid literal for int() with base 10: ''

https://github.com/EstrellaXD/Auto_Bangumi/blob/7913061f45121f26325e04e913f9afcc94232cf5/backend/src/module/parser/analyser/torrent_parser.py#L15C26-L15C27

这条正则把命名后的也匹配上了: `r"(.*)第?(\d*\.*\d*)[话話集](?:END)?(.*)",`

gpt告诉我用 `r"(?!.*S\d+E\d+\.\w+$)(.*)第?(\d*\.*\d*)[话話集](?:END)?(.*)",`, 麻烦大佬看下.

临时可改成不带"话話集"的其他标题.
```

**Comment by shininome** [comment]
估计是ANI改名了，这个和规则无关

**Comment by jqtmviyu** [comment]
> ```shell
> r"(.*)第?(\d*\.*\d*)[话話集](?:END)?(.*)
> ```

不是 ani 改名, 你可以手动建一个种子, 名为"xxx话xxx S01E01.mp4", 添加bangumi标签, 然后就能看到重命名循环线程一直在报错.

**Comment by jqtmviyu** [comment]
`[Doomdos] -凡人修仙传-第107话-[1080P].mp4` 也会有问题

```python
import re

torrent_name = "[Doomdos] -凡人修仙传-第107话-[1080P].mp4"
rule = r"(.*)第?(\d*\.*\d*)[话話集](?:END)?(.*)"

# rule = r"(.*?)第?(\d*\.*\d*)[话話集](?:END)?(.*)" # 非贪婪模式

match_obj = re.match(rule, torrent_name, re.I)
print(match_obj.group(1))
print(match_obj.group(2))
print(match_obj.group(3))
```
输出
```
[Doomdos] -凡人修仙传-第107

-[1080P].mp4
```

**Comment by shininome** [comment]
Episode(title_en=None, title_zh='-凡人修仙传-', title_jp=None, season=1, season_raw='', e
pisode=107, sub='', group='Doomdos', resolution='1080P', source='')
不知道现在行不行

**Comment by chumoe** [comment]
标题带xx话xx就会出现楼主这个提示，感觉匹配规则可以优化一下
