### ISSUE TITLE
求增加arm64版的AutoBangumi[Discussion] 

### ISSUE THREAD

**Issue by maxddondon** [EstrellaXD/Auto_Bangumi#807]
### 项目讨论

目前版本主要对linux和amd64版本，而目前很多轻型nas上都是arm架构的处理器，故求增加arm64版的。谢谢！

**Comment by Rewrite0** [comment]
有没有可能，arm64也是有的

**Comment by maxddondon** [comment]
> 有没有可能，arm64也是有的

在描述文件里没找到，求arm64版的tag~多谢！

**Comment by Rewrite0** [comment]
> > 有没有可能，arm64也是有的
> 
> 在描述文件里没找到，求arm64版的tag~多谢！

https://hub.docker.com/r/estrellaxd/auto_bangumi/tags

**Comment by maxddondon** [comment]
> > > 有没有可能，arm64也是有的
> > 
> > 
> > 在描述文件里没找到，求arm64版的tag~多谢！
> 
> https://hub.docker.com/r/estrellaxd/auto_bangumi/tags

收到！
