### ISSUE TITLE
[Feature Request] 希望增加异步处理

### ISSUE THREAD

**Issue by ghostry** [EstrellaXD/Auto_Bangumi#813]
### 功能改进

目前有些操作要等待好久，比如添加订阅，第一步到第二步还可以理解，要读取番剧名称后进一步设置。
第二步订阅按钮也要等很久。感觉没有必要。
程序添加到RSS列表后，其他的操作在后台慢慢执行就好了。用户没必要等待。
现在做法好像是要等着拉取信息然后添加到下载器，之后才给用户返回。

**Comment by shininome** [comment]
己经异步了,不知道能不能达到你的期望

**Comment by EstrellaXD** [comment]
在计划中了 #567
