### ISSUE TITLE
[Feature Request]: 关于重命名

### ISSUE THREAD

**Issue by lbr77** [EstrellaXD/Auto_Bangumi#82]
### 功能改进

现在AB的重命名方法是定时获得已下载项目并重命名。

注意到qb有这样一个功能
![image](https://user-images.githubusercontent.com/53066066/182524825-b192ce54-f59c-4016-b86a-94cfeb6ab9de.png)

可以把定时完成这块改成下载完成后通过api上报给ab然后改名

**Comment by EstrellaXD** [comment]
这个经常出bug，不够稳定，轮询重命名我觉得没啥问题。

**Comment by lbr77** [comment]
那或者就加一个api可以吗

**Comment by EstrellaXD** [comment]
> 那或者就加一个api可以吗
> 
> 就提供hash和原名字、路径然后改名
> 
> 如[lbr77@e0e74eb](https://github.com/lbr77/Auto_Bangumi/commit/e0e74eb98d92188a61cb687e4c9cd28a15e92bdc)

这个需求的人比较少推荐自己修改源代码，本身重命名模块也做好接口了，直接调用即可
