### ISSUE TITLE
[解析器错误]日剧字幕组中间多了一对中括号，解析出来以后自动改名不行了

### ISSUE THREAD

**Issue by cy-knight** [EstrellaXD/Auto_Bangumi#834]
### 当前程序版本

3.1.14

### 解析器语言设置

默认：zh

### TMDB 解析

是

### 字幕组提供的名称

【幻月字幕组】【24年日剧】【直到破坏了丈夫的家庭】【第6话】【1080P】【中日双语】

### 错误识别名称

24年日剧

**Comment by cy-knight** [comment]
DEBUG
[2024-08-27 17:30:35]
[Network] Successfully connected to https://comicat.org/rss-%E7%9B%B4%E5%88%B0%E7%A0%B4%E5%9D%8F+%E5%B9%BB%E6%9C%88.xml. Status: 200
DEBUG
[2024-08-27 17:30:35]
RAW:【幻月字幕组】【24年日剧】【直到破坏了丈夫的家庭】【第6话】【1080P】【中日双语】 >> 24年日剧
DEBUG
[2024-08-27 17:30:55]
[Downloader] Authed.

**Comment by cy-knight** [comment]
解析器是否可以提供一个自定义参数的模式，手动调整参数来解析

**Comment by cy-knight** [comment]
WARNING
[2024-08-30 19:33:19]
Cannot parse 【幻月字幕组】【24年日剧】【直到破坏了丈夫的家庭】【第7话】【1080P】【中日双语】.mp4 with error invalid literal for int() with base 10: ''
WARNING
[2024-08-30 19:33:19]
[Renamer] 【幻月字幕组】【24年日剧】【直到破坏了丈夫的家庭】【第7话】【1080P】【中日双语】.mp4 parse failed
WARNING
[2024-08-30 19:33:19]
Cannot parse 【幻月字幕组】【直到破坏了丈夫的家庭】【第2话】【1080P】【中日双语】.mp4 with error invalid literal for int() with base 10: ''
WARNING
[2024-08-30 19:33:19]
[Renamer] 【幻月字幕组】【直到破坏了丈夫的家庭】【第2话】【1080P】【中日双语】.mp4 parse failed
WARNING
[2024-08-30 19:33:19]
Cannot parse 破坏了家庭 S01E04.mp4 with error invalid literal for int() with base 10: ''
WARNING
[2024-08-30 19:33:19]
[Renamer] 破坏了家庭 S01E04.mp4 parse failed

**Comment by cy-knight** [comment]
r"(.*) - (\d{1,4}(?!\d|p)|\d{1,4}\.\d{1,2}(?!\d|p))(?:v\d{1,2})?(?: )?(?:END)?(.*)",
    r"(.*)[\[\ E](\d{1,4}|\d{1,4}\.\d{1,2})(?:v\d{1,2})?(?: )?(?:END)?[\]\ ](.*)",
    r"(.*)\[(?:第)?(\d*\.*\d*)[话集話](?:END)?\](.*)",
    r"(.*)第?(\d*\.*\d*)[话話集](?:END)?(.*)",
    r"(.*)(?:S\d{2})?EP?(\d+)(.*)",

**Comment by shininome** [comment]
日剧一直都不怎么行吧

**Comment by cy-knight** [comment]
调了一下午解析改名都成了，不过和原版的没法兼容了。不过种子解析那边跑出来的结果很奇怪，不确定这个正则本身是不是写错了

**Comment by shininome** [comment]
@shininome tmdb解析内部是写死动漫的，你改这个没太大用

**Comment by cy-knight** [comment]
TMDB解析看了眼有返回消息   但是直接炸 改用parser解析了

**Comment by shininome** [comment]
@cy-knight 别用ab解析动漫以外的了, 到也不是不能, 就是完全没想去兼容, 建议用mp或nt

**Comment by cy-knight** [comment]
确实   哈哈哈  现在自己改完能下能自动改名就算完事了
