### ISSUE TITLE
[错误报告]启用AB_EP_COMPLETE后执行报错

### ISSUE THREAD

**Issue by poiol** [EstrellaXD/Auto_Bangumi#85]
### 当前程序版本

2.5.22

### 问题类型

程序运行问题

### 问题描述

启用AB_EP_COMPLETE=True
docker运行报错

### 发生问题时系统日志

![image](https://user-images.githubusercontent.com/17819401/182836716-b966f1f2-71eb-447e-97c8-9dcd839db4b3.png)

**Comment by EstrellaXD** [comment]
方便使用 API `/api/v1/data` 提供一下 data 数据么
