### ISSUE TITLE
[错误报告]解析成功但无法添加新的rss

### ISSUE THREAD

**Issue by Kisaratsu** [EstrellaXD/Auto_Bangumi#855]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/EstrellaXD/Auto_Bangumi/releases/latest) 相同。
- [X] 我已经查阅了[已知问题](https://autobangumi.org/faq/)，并确认我的问题不在其中。
- [X] 我已经 [issue](https://github.com/EstrellaXD/Auto_Bangumi/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 **描述** 替换为我遇到的问题。

### 当前程序版本

3.1.15

### 问题类型

WebUI

### 问题描述

添加rss时原本设置排除中的正则表达式不会自动导入，也无法编辑，点击订阅或收集无反应。
![image](https://github.com/user-attachments/assets/48e937e5-9f55-4b65-95d3-797d0e548e3f)
![image](https://github.com/user-attachments/assets/c9822ae8-783c-4778-826e-9e758a468562)

### 发生问题时系统日志

```bash
3.1.15新出现的bug，开启了调试模式后没有见到生成系统日志，目测是因为本身添加订阅时配置不完整，没有添加成功故没有留下日志记录。
```

**Comment by silencer404** [comment]
docker compose部署有相同的问题。
此外，图上的“排除”栏对比3.1.14也没有预先配置项和“+”号了，疑似bug
