### ISSUE TITLE
[错误报告]关于历史番剧下载，重命名错误的问题

### ISSUE THREAD

**Issue by yzjmxy** [EstrellaXD/Auto_Bangumi#86]
### 当前程序版本

2.5.22

### 问题类型

程序运行问题

### 问题描述

当程序下载历史番剧时，无法定义到指定番剧所在目录。而是会下载到bangumi目录下。
并且当下载完成后也无法正确自动移动到对应番剧的所在目录。
而是会自动重名为很长的一段名称。
![image](https://user-images.githubusercontent.com/39520103/182841063-276a2545-1b95-437f-a738-d315c21da336.png)
如图所示
截取了部分日志文件，为了防止太长，就上传附件了
[log.txt](https://github.com/EstrellaXD/Auto_Bangumi/files/9259414/log.txt)

**Comment by EstrellaXD** [comment]
可以先在 qb 中移动这些种子到正常的目录下，之后就会正常
检查一下 qb 的设置：
<img width="494" alt="image" src="https://user-images.githubusercontent.com/33726646/182843664-73667403-ca87-4c55-969f-33a2e7f8a4c5.png">
