### ISSUE TITLE
[错误报告]webui添加旧番失败

### ISSUE THREAD

**Issue by mikusaa** [EstrellaXD/Auto_Bangumi#89]
### 当前程序版本

2.5.23

### 问题类型

WebUI

### 问题描述

添加旧番时报错`null`

用的是这条rss：https://mikanani.me/RSS/Bangumi?bangumiId=2621&subgroupid=382

![image](https://user-images.githubusercontent.com/31799398/183239965-92e592ed-e81a-47fe-9a9f-bf46fc1ad532.png)

**Comment by EstrellaXD** [comment]
已经修复
