### ISSUE TITLE
[错误报告] linux 本地部署 api.py 无法启动

### ISSUE THREAD

**Issue by duzhaokun123** [EstrellaXD/Auto_Bangumi#91]
### 当前程序版本

2.5.24 https://github.com/EstrellaXD/Auto_Bangumi/commit/7559ffa1d3c5aa9e835c13871374f42c18eb0be5

### 问题类型

程序运行问题

### 问题描述

按照 wiki 修改文件后 使用`python src/api.py ` 无法启动

### 发生问题时系统日志

```shell
❯ python src/api.py 
Traceback (most recent call last):
  File "/home/admin/Auto_Bangumi/src/api.py", line 31, in <module>
    app.mount("/assets", StaticFiles(directory="/templates/assets"), name="assets")
  File "/home/admin/Auto_Bangumi/venv/lib/python3.10/site-packages/starlette/staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/templates/assets' does not exist
```

**Comment by Rewrite0** [comment]
缺少webui目录，需要下载webui后放置在/templates, 本地运行建议修改webui的路径  
![image](https://user-images.githubusercontent.com/49576640/183257197-12019d68-013e-403a-9655-ef9bfcd8f2b8.png)

**Comment by ZhangTianrong** [comment]
Wiki 里那个有点老了，那个时候的项目结构里甚至没有 `src` 文件夹，但是想法是一样的，只是根据 `Dockerfile` 把相关的挂载点换成真实路径就好。如果想维持之前几个版本 `templates` 在项目目录下的话就稍微修改一下 `getWebUI.sh` 吧，

```
pkgDir=$(git rev-parse --show-toplevel)
webDir=$pkgDir/templates
```

目前 Windows 这里我是在 WSL 里跑的，没怎么用过 git bash, 但是感觉应该是不会有啥问题的。
