### ISSUE TITLE
[解析器错误] 旧番提交报错null

### ISSUE THREAD

**Issue by zoooo0** [EstrellaXD/Auto_Bangumi#93]
### 当前程序版本

2.5.24

### 解析器语言设置

默认：zh

### TMDB 解析

是

### 字幕组提供的名称

【悠哈璃羽字幕社】[异种族风俗娘评鉴指南_Ishuzoku Rebyuazu][01-12][x264][CHT][AT-X 1280x720] [复制磁连]

### 错误识别名称

日志显示：null rss链接：https://mikanani.me/RSS/Bangumi?bangumiId=2134&subgroupid=12

**Comment by EstrellaXD** [comment]
目前不支持合集识别，请等待版本更新

**Comment by virgil724** [comment]
這邊有類似錯誤 在parser裡面好像不支援【】這個字元 我有點忘記是回Wrong API Usage 還是回null 在麻煩作者了
