### ISSUE TITLE
[Feature Request]: 能否添加个重命名完自动转移的功能

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [EstrellaXD/Auto_Bangumi#99]
### 功能改进

能否添加个重命名完自动转移的功能，类似于emby的auto organize插件

**Comment by EstrellaXD** [comment]
请具体描述一下如何转移，最好给出转移前后的目录

**Comment by SchrodingerBarbatos** [comment]
> 请具体描述一下如何转移，最好给出转移前后的目录
例如我挂载了了谷歌云盘在/home/gdrive目录下，我希望/download/AutoBangumi下的文件Autiobangumi在qb下载完成重命名后自动转移到/home/gdrive/AutoBangumi下，这样emby这类可以直接读取gdrive中的文件，节省本地存储空间，方便vps用户

我自己写移动脚本的话，我不知道在我移动文件过后autobangumi是否会因为下载目录/download/AutoBangumi下文件的缺失从而再次下载，所以希望您能添加这样的功能

可能描述有点不清楚，希望您能看懂orz

**Comment by EstrellaXD** [comment]
明白你的意思了
但是 AutoBangumi 并不直接操作文件和文件夹，操作过程是通过 qBittorrent 来完成的。

> 我自己写移动脚本的话，我不知道在我移动文件过后autobangumi是否会因为下载目录/download/AutoBangumi下文件的缺失从而再次下载，所以希望您能添加这样的功能

删除之后取决于你是否重新添加 RSS 订阅链接，如果不添加的话不会重新下载。

**Comment by SchrodingerBarbatos** [comment]
> 明白你的意思了 但是 AutoBangumi 并不直接操作文件和文件夹，操作过程是通过 qBittorrent 来完成的。所以对于文件目录的权限会被 qBittorrent 限制。
> 
> > 我自己写移动脚本的话，我不知道在我移动文件过后autobangumi是否会因为下载目录/download/AutoBangumi下文件的缺失从而再次下载，所以希望您能添加这样的功能
> 
> 删除之后取决于你是否重新添加 RSS 订阅链接，如果不添加的话不会重新下载。



> 明白你的意思了 但是 AutoBangumi 并不直接操作文件和文件夹，操作过程是通过 qBittorrent 来完成的。所以对于文件目录的权限会被 qBittorrent 限制。
> 
> > 我自己写移动脚本的话，我不知道在我移动文件过后autobangumi是否会因为下载目录/download/AutoBangumi下文件的缺失从而再次下载，所以希望您能添加这样的功能
> 
> 删除之后取决于你是否重新添加 RSS 订阅链接，如果不添加的话不会重新下载。移动之后，qbittorrent 中应该会出现报错状态，到时候自己手动删一下报错种子就行了。

明白了谢谢
